// PatriaSoul – Baština
// 100 pitanja iz hrvatske kulturne, tradicijske, nematerijalne i sakralne baštine.
// Format je usklađen s centralnim quiz engineom.
(function(){
  const q = [
    ['Koji je tradicionalni hrvatski suvenir od čipke poznat po otoku Pagu?','Paška čipka','Lička kapa','Baranjski vez','Sinjska alka'],
    ['Koja je hrvatska čipka upisana na UNESCO-ov popis nematerijalne baštine?','Paška čipka','Dubrovnička čipka','Istarska čipka','Zadarska čipka'],
    ['Po čemu je posebno poznata lepoglavska čipka?','Čipkarstvu','Glazbenim orguljama','Drvenim brodovima','Keramici'],
    ['Koji je materijal tradicionalno najvažniji za lepoglavsku čipku?','Lan','Svila','Vuna','Koža'],
    ['Koji je grad poznat po licitarima?','Zagreb','Dubrovnik','Pula','Šibenik'],
    ['Što je licitar?','Ukrašeni medičarski proizvod','Vrsta tamburice','Tradicionalni nož','Vrsta vina'],
    ['Koji je običaj iz sjeverne Hrvatske povezan s drvenim dječjim igračkama?','Izrada drvenih igračaka Hrvatskog zagorja','Izrada paške čipke','Moreška','Sinjska alka'],
    ['Kako se zove tradicionalna drvena igračka često izrađivana u Hrvatskom zagorju?','Drvena svirala','Tambura','Gusle','Diple'],
    ['Koji je hrvatski običaj poznat po zvončarima?','Pokladni ophodi','Uskrsna procesija','Žetvena svečanost','Vinogradarska berba'],
    ['U kojem su kraju posebno poznati kastavski zvončari?','Kvarneru','Baranji','Dubrovniku','Podravini'],
    ['Što zvončari tradicionalno nose oko struka?','Velika zvona','Čipkane trake','Drvene križeve','Mačeve'],
    ['Koji je običaj poznat po skupinama muškaraca koji obilaze sela u vrijeme poklada?','Zvončari','Moreška','Klapsko pjevanje','Alka'],
    ['Koji je hrvatski plesni običaj povezan s otokom Korčulom?','Moreška','Linđo','Kolo na dva štuka','Drmeš'],
    ['Na kojem se otoku tradicionalno izvodi moreška?','Korčuli','Krku','Braču','Rabu'],
    ['Koji je ples tradicionalno vezan uz Dubrovnik?','Linđo','Moreška','Drmeš','Nijemo kolo'],
    ['Kako se zove tradicionalni ples dubrovačkog kraja?','Linđo','Poskočica','Kolo','Prigorski drmeš'],
    ['Koji je plesni oblik posebno poznat u Slavoniji?','Šokačko kolo','Linđo','Moreška','Nijemo kolo'],
    ['Koji je tradicionalni ples Dalmatinske zagore poznat po snažnim poskocima?','Nijemo kolo','Šokačko kolo','Drmeš','Linđo'],
    ['Koji je element hrvatske baštine povezan s guslama?','Usmeno pripovijedanje i epsko pjevanje','Izrada čipke','Klesarstvo','Ribarstvo'],
    ['Koji instrument ima posebno mjesto u slavonskoj tradicijskoj glazbi?','Tamburica','Gusle','Mandolina','Sopile'],
    ['Koji se instrument često povezuje s istarskom tradicijskom glazbom?','Sopile','Tamburica','Gajde','Cimbal'],
    ['Što su sopile?','Tradicionalni puhački instrument','Vrsta plesa','Vrsta čipke','Drvena posuda'],
    ['Koji je glazbeni izričaj karakterističan za dalmatinsku obalu i otoke?','Klapsko pjevanje','Tamburaško kolo','Ganga','Ojkanje'],
    ['Što je klapa?','Skupina pjevača koji tradicionalno pjevaju višeglasno','Vrsta broda','Vrsta plesa','Vrsta crkve'],
    ['Koji je hrvatski glazbeni izraz UNESCO zaštitio kao nematerijalnu baštinu?','Klapsko pjevanje','Pop glazbu','Tamburaški orkestar','Zborsko pjevanje Zagreba'],
    ['Koji je tradicijski vokalni stil posebno povezan s Dalmatinskom zagorom?','Ganga','Klapa','Linđo','Moreška'],
    ['Koji se pjevački stil tradicionalno izvodi u Istri i na Kvarneru?','Dvoglasje tijesnih intervala Istre i Hrvatskog primorja','Klapsko pjevanje','Ganga','Ojkanje Slavonije'],
    ['Koji je tradicionalni oblik pjevanja karakterističan za područje Imotske krajine i Hercegovine?','Ganga','Klapa','Linđo','Glagoljaško pjevanje'],
    ['Što je ojkanje?','Tradicionalni način pjevanja s karakterističnim potresanjem glasa','Vrsta plesa','Vrsta čipke','Obred pečenja kruha'],
    ['Koji je hrvatski povijesni običaj povezan s viteškim natjecanjem u Sinju?','Sinjska alka','Moreška','Trka na prstenac','Festa sv. Vlaha'],
    ['U kojem se gradu održava Sinjska alka?','Sinju','Kninu','Trogiru','Omišu'],
    ['Koji se predmet koristi kao meta u Sinjskoj alci?','Alka','Prsten','Jabuka','Štit'],
    ['Koji se običaj u Barbanu održava kao viteško konjaničko natjecanje?','Trka na prstenac','Sinjska alka','Moreška','Zvončari'],
    ['U kojem se istarskom mjestu održava Trka na prstenac?','Barbanu','Pazinu','Rovinju','Buzetu'],
    ['Koji je običaj povezan s Festom svetoga Vlaha?','Proslava zaštitnika Dubrovnika','Berba grožđa','Pomorska regata','Poklade'],
    ['Tko je zaštitnik Dubrovnika?','Sveti Vlaho','Sveti Duje','Sveti Marko','Sveti Donat'],
    ['Kako se zove tradicionalna dubrovačka proslava svetoga Vlaha?','Festa svetoga Vlaha','Moreška','Dubrovački karneval','Križni put'],
    ['Koji je predmet važan simbol Feste svetoga Vlaha?','Barjak svetoga Vlaha','Alka','Licitar','Tamburica'],
    ['Koji je blagdan posebno povezan s tradicijom procesija u Hvaru?','Veliki tjedan','Došašće','Sveta tri kralja','Svijećnica'],
    ['Koji je tradicionalni običaj na otoku Hvaru poznat kao Za križem?','Procesija','Ples','Viteško natjecanje','Sajam'],
    ['Kada se održava procesija Za križem?','U noći Velikog četvrtka i na Veliki petak','Na Božić','Na Novu godinu','Na Dan državnosti'],
    ['Koliko se mjesta na Hvaru tradicionalno povezuje s procesijom Za križem?','Šest','Tri','Deset','Dvanaest'],
    ['Koji je hrvatski grad poznat po procesiji Svetog Duje?','Split','Zadar','Rijeka','Pula'],
    ['Tko je zaštitnik Splita?','Sveti Duje','Sveti Vlaho','Sveti Donat','Sveti Eufemija'],
    ['Koji je tradicionalni blagdan povezan s gradom Sinjem?','Velika Gospa','Sveti Vlaho','Sveti Duje','Sveta Eufemija'],
    ['Koje je marijansko svetište jedno od najpoznatijih u Hrvatskoj?','Marija Bistrica','Trsat','Aljmaš','Sinj'],
    ['Gdje se nalazi nacionalno marijansko svetište Marija Bistrica?','U Hrvatskom zagorju','U Istri','Na Korčuli','U Baranji'],
    ['Koje je svetište poznato kao Trsatsko svetište?','Svetište Majke Božje Trsatske','Svetište Gospe Sinjske','Svetište Gospe od Škrpjela','Svetište sv. Vlaha'],
    ['U kojem se gradu nalazi Trsatsko svetište?','Rijeci','Zadru','Splitu','Dubrovniku'],
    ['Koje je poznato marijansko svetište u Sinju?','Svetište Gospe Sinjske','Marija Bistrica','Trsat','Aljmaš'],
    ['Koji se blagdan posebno svečano slavi u Sinju?','Velika Gospa','Tijelovo','Sveti Josip','Svi sveti'],
    ['Koji je hrvatski grad poznat po Eufrazijevoj bazilici?','Poreč','Rovinj','Pula','Umag'],
    ['U kojem se gradu nalazi Eufrazijeva bazilika?','Poreču','Splitu','Šibeniku','Trogiru'],
    ['Koji je povijesni kompleks u Splitu povezan s rimskim carem Dioklecijanom?','Dioklecijanova palača','Narodni trg','Klis','Salona'],
    ['Koji je povijesni lokalitet u blizini Splita bio važan rimski grad?','Salona','Andautonija','Mursa','Cibalae'],
    ['Koji je grad poznat po katedrali sv. Jakova, remek-djelu renesansne arhitekture?','Šibenik','Zadar','Trogir','Pula'],
    ['Od kojeg je materijala uglavnom građena katedrala sv. Jakova u Šibeniku?','Kamena','Drva','Opeke','Mramora'],
    ['Koji je grad poznat po romaničkoj katedrali sv. Stošije?','Zadar','Split','Dubrovnik','Rijeka'],
    ['Koji je hrvatski grad poznat po crkvi sv. Donata?','Zadar','Pula','Osijek','Varaždin'],
    ['Koji je grad poznat po Areni iz rimskog doba?','Pula','Poreč','Rijeka','Zadar'],
    ['Što je pulska Arena?','Rimski amfiteatar','Srednjovjekovna tvrđava','Katedrala','Gradska palača'],
    ['Koji je grad poznat po staroj jezgri pod zaštitom UNESCO-a i Stradunu?','Dubrovnik','Split','Trogir','Zadar'],
    ['Kako se zove glavna povijesna ulica Dubrovnika?','Stradun','Kalelarga','Marmontova','Korzo'],
    ['Koji je hrvatski grad poznat po povijesnoj jezgri i Kamerlengu?','Trogir','Šibenik','Pula','Senj'],
    ['Što je Kamerlengo?','Tvrđava u Trogiru','Crkva u Zadru','Palača u Dubrovniku','Most u Osijeku'],
    ['Koji je grad poznat po romantičnoj staroj jezgri i kuli Lotrščak?','Zagreb','Varaždin','Samobor','Karlovac'],
    ['Koji je zagrebački običaj povezan s pucanjem topa s Griča?','Gradska tradicija podneva','Pokladni ophod','Uskrsna procesija','Žetveni običaj'],
    ['Koji je hrvatski grad poznat po baroknoj kulturnoj baštini?','Varaždin','Knin','Metković','Ploče'],
    ['Koji festival u Varaždinu posebno njeguje baroknu glazbu?','Varaždinske barokne večeri','Dubrovačke ljetne igre','Splitsko ljeto','Motovunski festival'],
    ['Koji je grad poznat po staroj jezgri i dvorcu Trakošćan u okolici?','Varaždin','Zadar','Sinj','Vukovar'],
    ['Koja je tradicionalna kuhinja posebno poznata po zagorskim štruklima?','Hrvatsko zagorje','Istra','Dubrovnik','Lika'],
    ['Što su zagorski štrukli?','Jelo od tijesta sa sirom i nadjevom','Vrsta kolača od badema','Sušena riba','Mesna juha'],
    ['Koji je specijalitet posebno povezan s otokom Pagom?','Paški sir','Samoborska salama','Istarski fuži','Zagorski štrukli'],
    ['Od kojeg se mlijeka tradicionalno proizvodi paški sir?','Ovčjeg','Kravlje­g','Kozjeg','Bivoljeg'],
    ['Koji je istarski proizvod zaštićen kao dio hrvatske gastronomske baštine?','Istarski pršut','Paški sir','Zagorski štrukli','Kulenova seka'],
    ['Koji je slavonski suhomesnati proizvod poznat po začinjenoj svinjetini?','Kulen','Paški sir','Istarski pršut','Dalmatinska pašticada'],
    ['Koji je proizvod tradicionalno povezan s Baranjom?','Baranjski kulen','Paški sir','Zagorski štrukli','Viška pogača'],
    ['Koji je dalmatinski tradicionalni specijalitet od govedine?','Pašticada','Kulen','Štrukli','Čobanac'],
    ['Koje je jelo tradicionalno povezano s Visom?','Viška pogača','Pašticada','Kulen','Zagorski štrukli'],
    ['Što je soparnik?','Tradicionalno jelo od tijesta i blitve','Mesni gulaš','Slavonska kobasica','Riblja juha'],
    ['Koji je kraj posebno poznat po soparniku?','Poljica','Baranja','Međimurje','Istra'],
    ['Koje je hrvatsko vino posebno povezano s Pelješcem?','Dingač','Graševina','Malvazija','Pošip'],
    ['Koja je sorta vina posebno poznata na Korčuli?','Pošip','Dingač','Graševina','Plavac mali'],
    ['Koja je sorta bijelog vina posebno poznata u Istri?','Malvazija istarska','Pošip','Graševina','Škrlet'],
    ['Koja je sorta vina posebno poznata u kontinentalnoj Hrvatskoj?','Graševina','Plavac mali','Pošip','Malvazija'],
    ['Koji je tradicionalni napitak važan u hrvatskoj vinskoj kulturi?','Vino','Kava','Čaj','Medovina'],
    ['Koji je običaj povezan s berbom grožđa?','Vincanje i berba','Zvončari','Moreška','Alka'],
    ['Koji je hrvatski tradicijski predmet poznat kao simbol Zagreba i sjeverozapadne Hrvatske?','Licitarsko srce','Sinjska alka','Paška čipka','Dubrovnički barjak'],
    ['Koje su boje najčešće na tradicionalnom licitarskom srcu?','Crvena s ukrasima','Plava bez ukrasa','Crna i bijela','Zelena i žuta'],
    ['Koji je tradicionalni odjevni predmet karakterističan za Liku?','Lička kapa','Paška čipka','Šokački opanak','Dubrovnička kapa'],
    ['Koji je dio tradicijske nošnje posebno poznat u Slavoniji?','Zlatovez','Paška čipka','Lička kapa','Moreška'],
    ['Što je zlatovez?','Ukrasni vez zlatnom ili pozlaćenom niti','Vrsta čipke','Vrsta plesa','Vrsta tamburice'],
    ['Koji je kraj posebno poznat po zlatovezu?','Slavonija','Istra','Kvarner','Dubrovnik'],
    ['Koji je tradicionalni dio obuće važan u mnogim hrvatskim krajevima?','Opanak','Kaciga','Mokasina','Sandala'],
    ['Koji je hrvatski tradicijski zanat povezan s izradom drvenih posuda i predmeta?','Drvorezbarstvo','Čipkarstvo','Kovaštvo','Lončarstvo'],
    ['Koji je zanat povezan s oblikovanjem predmeta od gline?','Lončarstvo','Klesarstvo','Čipkarstvo','Zlatovez'],
    ['Koji je grad poznat po tradiciji licitara i medičarstva koja je zaštićena UNESCO-om?','Zagreb','Split','Dubrovnik','Pula'],
    ['Koji je običaj vezan uz božićno vrijeme i unošenje slame u kuću?','Tradicionalni božićni običaj','Sinjska alka','Zvončari','Moreška'],
    ['Koji se tradicijski ukras često postavlja u hrvatskim kućama za Božić?','Božićno drvce','Licitarska alka','Barjak svetog Vlaha','Alka'],
    ['Koji je tradicionalni uskrsni običaj povezan s ukrašavanjem jaja?','Pisanice','Zvončari','Moreška','Alka'],
    ['Kako se nazivaju ukrašena uskrsna jaja u hrvatskoj tradiciji?','Pisanice','Licitari','Štrukli','Sopile'],
    ['Koji je oblik uskrsne pobožnosti posebno raširen u Hrvatskoj?','Procesije','Viteške igre','Tamburaški koncerti','Berba grožđa'],
    ['Koji je hrvatski običaj povezan s danom svetog Martina i mladim vinom?','Martinje','Fašnik','Alka','Festa svetog Vlaha'],
    ['Što se tradicionalno obilježava na Martinje?','Pretvaranje mošta u vino','Početak žetve','Berba maslina','Početak ribolovne sezone'],
    ['Koji je običaj posebno poznat u sjevernoj Hrvatskoj za vrijeme poklada?','Fašnik','Martinje','Moreška','Alka'],
    ['Kako se u Hrvatskoj često naziva pokladno vrijeme?','Fašnik','Martinje','Advent','Korizma'],
    ['Koji je hrvatski grad poznat po Samoborskom fašniku?','Samobor','Varaždin','Sinj','Dubrovnik'],
    ['Koji je tradicijski predmet često povezan s hrvatskim pomorstvom?','Drveni brod','Licitarsko srce','Lička kapa','Zlatovez'],
    ['Koji je hrvatski grad poznat po tradiciji drvenih brodova i kalafata?','Betina','Krapina','Varaždin','Bjelovar'],
    ['Na kojem se otoku nalazi mjesto Betina poznato po tradicijskoj brodogradnji?','Murteru','Hvaru','Braču','Pagu'],
    ['Koji je zanat ključan za tradicionalnu drvenu brodogradnju?','Kalafatanje','Licitiranje','Zlatovez','Čipkarstvo'],
    ['Što je kalafat?','Majstor tradicionalne brodogradnje','Vrsta plesa','Vrsta vina','Vrsta čipke'],
    ['Koji je hrvatski grad poznat po tradiciji drvenih igračaka i medičarstva u okolici?','Zagreb','Pula','Dubrovnik','Šibenik'],
    ['Koji je hrvatski zaštićeni tradicijski zanat povezan s Međimurjem?','Izrada tradicijskih predmeta i glazbala','Izrada paške čipke','Sinjska alka','Moreška'],
    ['Koji je simbol hrvatske kulturne baštine često prikazan u crvenoj boji kao srce?','Licitarsko srce','Paška alka','Sinjska kapa','Baranjski štit'],
    ['Koji je običaj povezan s procesijom na Veliki petak u mnogim hrvatskim mjestima?','Nošenje križa i molitva','Trka na prstenac','Zvončari','Berba grožđa'],
    ['Koji je tradicijski oblik umjetnosti posebno povezan s kamenoklesarstvom na dalmatinskoj obali?','Klesarstvo','Zlatovez','Čipkarstvo','Lončarstvo'],
    ['Koji materijal posebno obilježava dalmatinsku graditeljsku baštinu?','Kamen','Bambus','Trska','Blato'],
    ['Koji je hrvatski kulturni prostor poznat po suhozidima?','Jadranska obala i otoci','Središnja Slavonija','Međimurje','Podravina'],
    ['Što je suhozid?','Zid građen bez vezivnog morta','Drveni most','Kamena kuća s krovom','Vrsta bunara'],
    ['Koji je hrvatski tradicijski graditeljski element UNESCO zaštitio zajedno s drugim mediteranskim zemljama?','Umijeće suhozidne gradnje','Izrada tamburice','Izrada licitara','Izrada štrukli'],
    ['Koji je važan element hrvatske baštine vezan uz stara seoska gospodarstva?','Tradicijska arhitektura','Neboderi','Industrijske hale','Moderne marine'],
    ['Koja su kućanstva tradicionalno građena od drva posebno poznata u Posavini?','Posavske drvene kuće','Dalmatinske palače','Istarske kažete','Primorske kule'],
    ['Koji je tradicijski oblik kuće čest u Istri?','Kamena kuća','Drvena čardaklija','Baranjska kuća','Posavska kuća'],
    ['Koji se pojam često koristi za tradicionalnu slavonsku kuću s dvorištem?','Šokačka kuća','Kaštel','Konoba','Kula'],
    ['Što je konoba u dalmatinskoj tradiciji?','Prostor za čuvanje hrane, vina i druženje','Vrsta crkve','Vrsta čipke','Viteška igra'],
    ['Koji je tradicionalni prostor istarskog doma često služio za pripremu hrane?','Kuhinja i ognjište','Konoba','Čardak','Kula'],
    ['Koji je važan simbol hrvatske baštine povezan s ognjištem?','Obiteljski dom','Sinjska alka','Moreška','Licitar'],
    ['Koji se tradicionalni kruh često pripremao za blagdane?','Blagdanski kruh i pogača','Pizza','Tortilja','Bagel'],
    ['Koji je običaj povezan s blagoslovom hrane za Uskrs?','Uskrsni blagoslov hrane','Martinje','Fašnik','Zvončari'],
    ['Koji se običaj u nekim krajevima održava na blagdan svetog Jurja?','Jurjevski ophodi','Sinjska alka','Moreška','Martinje'],
    ['Što simbolizira proljetni običaj jurjevskih ophoda?','Dolazak proljeća i zaštitu doma','Početak zime','Berbu maslina','Pomorsku sezonu'],
    ['Koji se blagdan tradicionalno povezuje s paljenjem krijesova u nekim hrvatskim krajevima?','Ivanje','Božić','Sveti Nikola','Sveta Lucija'],
    ['Koji je običaj povezan s paljenjem ivanjskih krijesova?','Ivanje','Martinje','Fašnik','Festa svetog Vlaha'],
    ['Koji je tradicijski predmet djeci često donosio darove na blagdan svetog Nikole?','Sveti Nikola','Sveti Vlaho','Sveti Duje','Sveti Juraj'],
    ['Koji je blagdan poznat po običaju sijanja pšenice uoči Božića?','Sveta Lucija','Sveti Nikola','Sveti Juraj','Martinje'],
    ['Koji se datum tradicionalno povezuje sa svetom Lucijom?','13. prosinca','6. prosinca','25. prosinca','1. siječnja'],
    ['Koji je hrvatski običaj povezan s djecom i blagdanom svetog Nikole?','Darivanje djece','Berba grožđa','Zvončari','Trka na prstenac'],
    ['Koji je oblik hrvatske baštine posebno važan za očuvanje narodnih priča i legendi?','Usmena predaja','Industrijski dizajn','Moderna arhitektura','Digitalna umjetnost'],
    ['Kako se prenose mnoge tradicijske pjesme, priče i običaji kroz generacije?','Usmenom predajom','Isključivo internetom','Samo knjigama','Samo muzejima'],
    ['Koji je cilj očuvanja nematerijalne kulturne baštine?','Prenositi znanje i običaje budućim generacijama','Zamijeniti tradiciju modernim običajima','Ukinuti stare zanate','Ograničiti kulturne događaje'],
    ['Što je nematerijalna kulturna baština?','Znanja, vještine, običaji, izrazi i prakse zajednice','Samo stare građevine','Samo muzejski predmeti','Samo arheološki nalazi'],
    ['Koja organizacija vodi svjetski popis nematerijalne kulturne baštine?','UNESCO','UEFA','NATO','WHO'],
    ['Koji hrvatski tradicijski običaj uključuje zvona, maske i ophod?','Zvončari','Klapa','Alka','Linđo'],
    ['Koji je važan dio baštine hrvatskih otoka tradicionalno vezan uz maslinarstvo?','Suhozidi i maslinici','Zlatovez','Tamburice','Šokačko kolo'],
    ['Koje stablo ima posebno mjesto u dalmatinskoj poljoprivrednoj tradiciji?','Maslina','Breza','Jela','Bukva'],
    ['Koji je tradicijski proizvod važan u priobalnoj Hrvatskoj?','Maslinovo ulje','Kukuruzno brašno','Kulen','Medica'],
    ['Koji je hrvatski kraj posebno poznat po tartufima?','Istra','Lika','Slavonija','Međimurje'],
    ['Koji je tradicionalni istarski proizvod od tijesta poznat kao fuži?','Tjestenina','Kolač','Sir','Kobasica'],
    ['Koji je istarski specijalitet poznat kao maneštra?','Gusta juha od povrća i mahunarki','Kolač','Riblja pašteta','Kobasica'],
    ['Koji je tradicionalni slavonski kotlić poznat kao čobanac?','Gulaš od više vrsta mesa','Riblja juha','Kolač','Jelo od tijesta'],
    ['Koji je hrvatski grad poznat po tradiciji licitara, medičarstva i božićnih sajmova?','Zagreb','Ploče','Knin','Metković'],
    ['Koji je tradicijski oblik nakita posebno poznat u nekim dalmatinskim krajevima?','Srebrni i zlatni nakit','Drvene perle samo','Plastični nakit','Željezne pločice'],
    ['Koji je poznati dalmatinski nakit tradicionalno izrađivan od srebra?','Moruši i filigran','Licitari','Zlatovez','Paška čipka'],
    ['Što je filigran?','Fina obrada metala u obliku ukrasnih niti','Vrsta plesa','Vrsta vina','Drvena igračka'],
    ['Koji je grad posebno poznat po tradiciji zadarskog i dalmatinskog filigrana?','Zadar','Krapina','Varaždin','Vukovar'],
    ['Koji je hrvatski tradicijski zanat povezan s izradom glinenih posuda?','Lončarstvo','Kovaštvo','Čipkarstvo','Zlatovez'],
    ['Koji je tradicijski zanat povezan s obradom željeza?','Kovaštvo','Lončarstvo','Čipkarstvo','Drvorezbarstvo'],
    ['Koji je važan element tradicijske baštine vezan uz prenošenje vještina s majstora na učenika?','Tradicionalni obrti','Industrijska proizvodnja','Digitalizacija','Masovna proizvodnja'],
    ['Što je kulturna baština?','Nasljeđe materijalnih i nematerijalnih vrijednosti zajednice','Samo povijesne bitke','Samo muzejski eksponati','Samo prirodni krajolici'],
    ['Koji je najbolji način očuvanja tradicijskog zanata?','Učiti ga i prenositi novim generacijama','Samo ga fotografirati','Zabraniti promjene','Čuvati ga bez praktične primjene'],
    ['Zašto su hrvatski lokalni običaji važni?','Čuvaju identitet i povezuju generacije','Samo zbog turizma','Samo zbog natjecanja','Nisu važni izvan mjesta nastanka'],
    ['Što povezuje hrvatsku baštinu različitih krajeva?','Raznolikost tradicija unutar zajedničkog kulturnog prostora','Samo jedan običaj','Samo jedan govor','Samo jedna kuhinja'],
    ['Koja je glavna vrijednost hrvatske baštine?','Znanje, identitet i nasljeđe koje se prenosi generacijama','Samo gospodarska vrijednost','Samo turistička vrijednost','Samo muzejska vrijednost']
  ];
  window.PATRIA_BASTINA = q.map((f,i)=>({
    id:`bastina_${String(i+1).padStart(3,'0')}`,
    category:'bastina',
    question:f[0],
    answers:[f[1],f[2],f[3],f[4]],
    correctIndex:0
  }));
})();