// PatriaSoul – centralna baza pitanja
// Svako pitanje ima 4 opcije, a quiz.js ih pri igranju preslaguje.
const PATRIA_CATEGORIES={povijest:'Hrvatska povijest',domovinski_rat:'Domovinski rat',kraljevi:'Hrvatski kraljevi',katolicka_bastina:'Katolička baština',kulturna_bastina:'Kulturna baština',geografija:'Hrvatska geografija',glazba:'Hrvatska glazba',gradovi:'Gradovi i znamenitosti',jezik:'Jezik i književnost',mijesani:'Miješani kviz'};
const PATRIA_QUESTIONS=[
{id:'p001',category:'povijest',question:'Koji se hrvatski vladar tradicionalno smatra prvim hrvatskim kraljem?',answers:['Tomislav','Mislav','Krešimir III.','Dmitar Zvonimir'],correctIndex:0},
{id:'p002',category:'povijest',question:'Koje je godine Hrvatska postala članicom Ujedinjenih naroda?',answers:['1991.','1992.','1995.','2000.'],correctIndex:1},
{id:'p003',category:'povijest',question:'Koji je hrvatski ban povezan s revolucionarnom 1848. godinom?',answers:['Ivan Mažuranić','Josip Jelačić','Petar Berislavić','Nikola Šubić Zrinski'],correctIndex:1},
{id:'p004',category:'povijest',question:'Tko je branio Siget od Osmanlija 1566. godine?',answers:['Petar Zrinski','Nikola Šubić Zrinski','Fran Krsto Frankopan','Ivan Drašković'],correctIndex:1},
{id:'p005',category:'povijest',question:'Koje je godine osnovano Sveučilište u Zagrebu?',answers:['1669.','1699.','1776.','1874.'],correctIndex:0},
{id:'p006',category:'povijest',question:'Koji je grad bio važno središte hrvatske države u ranom srednjem vijeku?',answers:['Knin','Pula','Rijeka','Varaždin'],correctIndex:0},
{id:'p007',category:'povijest',question:'Kojeg se datuma obilježava Dan državnosti Republike Hrvatske?',answers:['25. lipnja','30. svibnja','5. kolovoza','8. listopada'],correctIndex:1},
{id:'p008',category:'povijest',question:'Koji se događaj dogodio 25. lipnja 1991.?',answers:['Proglašena je hrvatska neovisnost','Operacija Oluja','Međunarodno priznanje Hrvatske','Mirna reintegracija Podunavlja'],correctIndex:0},
{id:'p009',category:'povijest',question:'Koji je hrvatski sabor 1848. ukinuo kmetstvo?',answers:['Hrvatski sabor','Carevinsko vijeće','Dalmatinski sabor','Banski stol'],correctIndex:0},
{id:'p010',category:'povijest',question:'Koji se dokument smatra jednim od najvažnijih ranih hrvatskih glagoljskih spomenika?',answers:['Bašćanska ploča','Vinodolski zakonik','Povaljska listina','Istarski razvod'],correctIndex:0},
{id:'p011',category:'kraljevi',question:'Koji je hrvatski kralj vladao u drugoj polovici 11. stoljeća?',answers:['Dmitar Zvonimir','Tomislav','Mislav','Krešimir III.'],correctIndex:0},
{id:'p012',category:'kraljevi',question:'Koji se vladar povezuje s godinom 925. i naslovom kralja u papinskom pismu?',answers:['Tomislav','Dmitar Zvonimir','Petar Krešimir IV.','Stjepan Držislav'],correctIndex:0},
{id:'p013',category:'kraljevi',question:'Koji je hrvatski kralj poznat kao Petar Krešimir IV.?',answers:['Petar Krešimir IV.','Petar Svačić','Dmitar Zvonimir','Stjepan Držislav'],correctIndex:0},
{id:'p014',category:'kraljevi',question:'Koji je vladar prema hrvatskoj historiografiji naslijedio Tomislava?',answers:['Trpimir II.','Dmitar Zvonimir','Petar Krešimir IV.','Mihajlo Krešimir II.'],correctIndex:0},
{id:'p015',category:'kraljevi',question:'Koji je hrvatski kralj posljednji iz dinastije Trpimirovića?',answers:['Stjepan II.','Tomislav','Petar Krešimir IV.','Dmitar Zvonimir'],correctIndex:0},
{id:'p016',category:'domovinski_rat',question:'Koja se vojno-redarstvena operacija iz kolovoza 1995. obilježava 5. kolovoza?',answers:['Oluja','Bljesak','Maslenica','Medački džep'],correctIndex:0},
{id:'p017',category:'domovinski_rat',question:'Koja je operacija provedena u svibnju 1995.?',answers:['Bljesak','Oluja','Maslenica','Medački džep'],correctIndex:0},
{id:'p018',category:'domovinski_rat',question:'Koji je grad simbol otpora i obrane Hrvatske 1991. godine?',answers:['Vukovar','Pula','Varaždin','Dubrovnik'],correctIndex:0},
{id:'p019',category:'domovinski_rat',question:'Koji je datum Dana pobjede i domovinske zahvalnosti i Dana hrvatskih branitelja?',answers:['5. kolovoza','30. svibnja','25. lipnja','8. listopada'],correctIndex:0},
{id:'p020',category:'domovinski_rat',question:'Koji je proces završio mirnom reintegracijom hrvatskog Podunavlja?',answers:['Mirna reintegracija','Operacija Bljesak','Operacija Oluja','Zagrebački sporazum'],correctIndex:0},
{id:'p021',category:'geografija',question:'Koji je najviši vrh Hrvatske?',answers:['Sinjal na Dinari','Sveto brdo','Snježnik','Risnjak'],correctIndex:0},
{id:'p022',category:'geografija',question:'Koja je najduža rijeka koja cijelim tokom protječe kroz Hrvatsku?',answers:['Kupa','Cetina','Korana','Mrežnica'],correctIndex:0},
{id:'p023',category:'geografija',question:'Koje je najveće hrvatsko jezero po površini?',answers:['Vransko jezero','Prokljansko jezero','Bajer','Lokvarsko jezero'],correctIndex:0},
{id:'p024',category:'geografija',question:'Koji je najveći hrvatski otok po površini?',answers:['Cres','Krk','Brač','Hvar'],correctIndex:0},
{id:'p025',category:'geografija',question:'Koji nacionalni park čine brojna jezera povezana slapovima?',answers:['Plitvička jezera','Risnjak','Paklenica','Brijuni'],correctIndex:0},
{id:'p026',category:'gradovi',question:'U kojem se gradu nalazi Dioklecijanova palača?',answers:['Split','Dubrovnik','Zadar','Šibenik'],correctIndex:0},
{id:'p027',category:'gradovi',question:'Koji je hrvatski grad poznat po Stradunu?',answers:['Dubrovnik','Trogir','Zadar','Pula'],correctIndex:0},
{id:'p028',category:'gradovi',question:'U kojem se gradu nalazi crkva sv. Donata?',answers:['Zadar','Split','Poreč','Šibenik'],correctIndex:0},
{id:'p029',category:'gradovi',question:'Koji je grad poznat po Areni iz rimskog doba?',answers:['Pula','Rijeka','Osijek','Varaždin'],correctIndex:0},
{id:'p030',category:'gradovi',question:'Koji je hrvatski grad poznat po katedrali sv. Jakova koja je na UNESCO-ovu popisu?',answers:['Šibenik','Zagreb','Karlovac','Sisak'],correctIndex:0},
{id:'p031',category:'kulturna_bastina',question:'Koje je pismo posebno povezano s hrvatskom srednjovjekovnom baštinom?',answers:['Glagoljica','Runica','Grčko pismo','Arapsko pismo'],correctIndex:0},
{id:'p032',category:'kulturna_bastina',question:'Gdje se nalazi Bašćanska ploča?',answers:['Jurandvor na Krku','Trogir','Nin','Knin'],correctIndex:0},
{id:'p033',category:'kulturna_bastina',question:'Koji je hrvatski grad povijesno središte dubrovačke Republike?',answers:['Dubrovnik','Zagreb','Split','Osijek'],correctIndex:0},
{id:'p034',category:'kulturna_bastina',question:'Koji je grad poznat po Eufrazijevoj bazilici?',answers:['Poreč','Rovinj','Umag','Pula'],correctIndex:0},
{id:'p035',category:'kulturna_bastina',question:'Koja je tradicionalna viteška igra povezana sa Sinjem?',answers:['Sinjska alka','Moreška','Trka na prstenac','Kumpanija'],correctIndex:0},
{id:'p036',category:'katolicka_bastina',question:'Kako se u katoličkoj tradiciji naziva blagdan Presvetog Tijela i Krvi Kristove?',answers:['Tijelovo','Bogojavljenje','Blagovijest','Svi sveti'],correctIndex:0},
{id:'p037',category:'katolicka_bastina',question:'Koje je hrvatsko marijansko svetište poznato po crkvi na otvorenom i velikom hodočašću?',answers:['Marija Bistrica','Trsat','Sinj','Vepric'],correctIndex:0},
{id:'p038',category:'katolicka_bastina',question:'Koje je poznato svetište u Rijeci povezano s čudotvornom slikom Majke Božje?',answers:['Trsat','Marija Bistrica','Aljmaš','Ludbreg'],correctIndex:0},
{id:'p039',category:'katolicka_bastina',question:'Koji je svetac zaštitnik grada Dubrovnika?',answers:['Sveti Vlaho','Sveti Duje','Sveti Marko','Sveti Donat'],correctIndex:0},
{id:'p040',category:'katolicka_bastina',question:'Koji je svetac zaštitnik Splita?',answers:['Sveti Duje','Sveti Vlaho','Sveti Josip','Sveti Juraj'],correctIndex:0},
{id:'p041',category:'jezik',question:'Tko je napisao roman „U registraturi“?',answers:['Ante Kovačić','August Šenoa','Miroslav Krleža','Vjenceslav Novak'],correctIndex:0},
{id:'p042',category:'jezik',question:'Tko je autor „Judite“?',answers:['Marko Marulić','Marin Držić','Ivan Gundulić','Petar Hektorović'],correctIndex:0},
{id:'p043',category:'jezik',question:'Tko je napisao „Planine“?',answers:['Petar Zoranić','Marko Marulić','Hanibal Lucić','Marin Držić'],correctIndex:0},
{id:'p044',category:'jezik',question:'Koje je djelo napisao Marin Držić?',answers:['Dundo Maroje','Judita','Ribanje i ribarsko prigovaranje','Planine'],correctIndex:0},
{id:'p045',category:'jezik',question:'Koji je hrvatski književnik napisao „Gospodu Glembajeve“?',answers:['Miroslav Krleža','August Šenoa','Tin Ujević','Antun Gustav Matoš'],correctIndex:0},
{id:'p046',category:'glazba',question:'Koji je oblik višeglasnog pjevanja posebno povezan s dalmatinskom tradicijom?',answers:['Klapsko pjevanje','Bećarac','Ojkanje','Ganga'],correctIndex:0},
{id:'p047',category:'glazba',question:'Koji je oblik tradicijskog pjevanja povezan sa Slavonijom i Baranjom?',answers:['Bećarac','Klapsko pjevanje','Ganga','Ojkanje'],correctIndex:0},
{id:'p048',category:'glazba',question:'Koji je hrvatski skladatelj napisao operu „Nikola Šubić Zrinjski“?',answers:['Ivan pl. Zajc','Vatroslav Lisinski','Jakov Gotovac','Boris Papandopulo'],correctIndex:0},
{id:'p049',category:'glazba',question:'Koji je skladatelj napisao operu „Ero s onoga svijeta“?',answers:['Jakov Gotovac','Ivan pl. Zajc','Vatroslav Lisinski','Blagoje Bersa'],correctIndex:0},
{id:'p050',category:'glazba',question:'Tko je skladao prvu hrvatsku operu „Ljubav i zloba“?',answers:['Vatroslav Lisinski','Ivan pl. Zajc','Jakov Gotovac','Ivo Tijardović'],correctIndex:0},
{id:'p051',category:'povijest',question:'Koji je hrvatski ban bio poznat po reformama u 19. stoljeću i bio književnik?',answers:['Ivan Mažuranić','Josip Jelačić','Nikola Šubić Zrinski','Petar Berislavić'],correctIndex:0},
{id:'p052',category:'povijest',question:'Koji je hrvatski ban poginuo u bitci kod Krbavskog polja 1493.?',answers:['Petar Zrinski','Emerik Derenčin','Nikola Šubić Zrinski','Ivan Karlović'],correctIndex:1},
{id:'p053',category:'povijest',question:'Koji je hrvatski plemić pogubljen 1671. nakon Zrinsko-frankopanske urote?',answers:['Petar Zrinski','Nikola Šubić Zrinski','Ivan Mažuranić','Josip Jelačić'],correctIndex:0},
{id:'p054',category:'povijest',question:'Koji je plemić pogubljen zajedno s Petrom Zrinskim 1671.?',answers:['Fran Krsto Frankopan','Nikola Šubić Zrinski','Stjepan Držislav','Petar Berislavić'],correctIndex:0},
{id:'p055',category:'povijest',question:'Koji je grad bio sjedište hrvatskog bana u 19. stoljeću?',answers:['Zagreb','Split','Rijeka','Dubrovnik'],correctIndex:0},
{id:'p056',category:'gradovi',question:'Koji je grad glavni grad Republike Hrvatske?',answers:['Zagreb','Split','Rijeka','Osijek'],correctIndex:0},
{id:'p057',category:'gradovi',question:'Koji grad leži na ušću rijeke Neretve?',answers:['Metković','Zadar','Šibenik','Senj'],correctIndex:0},
{id:'p058',category:'gradovi',question:'Koji je grad poznat po staroj jezgri na otočiću Trogiru?',answers:['Trogir','Rovinj','Korčula','Hvar'],correctIndex:0},
{id:'p059',category:'gradovi',question:'Koji se grad naziva gradom na četiri rijeke?',answers:['Karlovac','Sisak','Osijek','Varaždin'],correctIndex:0},
{id:'p060',category:'gradovi',question:'Koji je grad najveći u Slavoniji?',answers:['Osijek','Vinkovci','Slavonski Brod','Požega'],correctIndex:0},
{id:'p061',category:'geografija',question:'Koji je najviši vrh Dinare na hrvatskoj strani?',answers:['Sinjal','Sveto brdo','Kula','Vaganski vrh'],correctIndex:0},
{id:'p062',category:'geografija',question:'Koji hrvatski otok je poznat po Zlatnom ratu?',answers:['Brač','Hvar','Vis','Korčula'],correctIndex:0},
{id:'p063',category:'geografija',question:'Koji je najduži hrvatski poluotok?',answers:['Istra','Pelješac','Pag','Cres'],correctIndex:0},
{id:'p064',category:'geografija',question:'Koja rijeka protječe kroz Zagreb?',answers:['Sava','Kupa','Drava','Una'],correctIndex:0},
{id:'p065',category:'geografija',question:'Koja rijeka protječe kroz Karlovac?',answers:['Kupa','Sava','Drava','Neretva'],correctIndex:0},
{id:'p066',category:'kulturna_bastina',question:'Koji je rimski car dao izgraditi palaču u Splitu?',answers:['Dioklecijan','Trajan','August','Konstantin'],correctIndex:0},
{id:'p067',category:'kulturna_bastina',question:'Koji se lokalitet nalazi u Poreču?',answers:['Eufrazijeva bazilika','Arena','Dioklecijanova palača','Katedrala sv. Jakova'],correctIndex:0},
{id:'p068',category:'kulturna_bastina',question:'Koji je hrvatski grad poznat po zadarskim Morskim orguljama?',answers:['Zadar','Split','Rijeka','Šibenik'],correctIndex:0},
{id:'p069',category:'kulturna_bastina',question:'Koja je povijesna jezgra pod zaštitom UNESCO-a i poznata po katedrali sv. Lovre?',answers:['Trogir','Zadar','Rovinj','Pula'],correctIndex:0},
{id:'p070',category:'kulturna_bastina',question:'Koji je lokalitet povezan s poljem drevnih parcela na Hvaru?',answers:['Starogradsko polje','Limska draga','Lonjsko polje','Imotsko polje'],correctIndex:0},
{id:'p071',category:'domovinski_rat',question:'Koja je bitka 1991. postala simbol obrane grada Vukovara?',answers:['Bitka za Vukovar','Bitka za Maslenicu','Bitka za Šibenik','Bitka za Zadar'],correctIndex:0},
{id:'p072',category:'domovinski_rat',question:'Koji je hrvatski grad bio izložen teškom granatiranju 1991. i branjen u Domovinskom ratu?',answers:['Dubrovnik','Pula','Varaždin','Rovinj'],correctIndex:0},
{id:'p073',category:'domovinski_rat',question:'Koja je operacija 1993. oslobodila područje oko Maslenice?',answers:['Maslenica','Bljesak','Oluja','Medački džep'],correctIndex:0},
{id:'p074',category:'domovinski_rat',question:'Koja je operacija provedena u rujnu 1993. na području Like?',answers:['Medački džep','Maslenica','Bljesak','Oluja'],correctIndex:0},
{id:'p075',category:'domovinski_rat',question:'Koji je sporazum otvorio put mirnoj reintegraciji hrvatskog Podunavlja?',answers:['Erdutski sporazum','Washingtonski sporazum','Daytonski sporazum','Zagrebački sporazum'],correctIndex:0},
{id:'p076',category:'katolicka_bastina',question:'Koji je svetac zaštitnik Zagreba?',answers:['Majka Božja od Kamenitih vrata','Sveti Duje','Sveti Vlaho','Sveti Donat'],correctIndex:0},
{id:'p077',category:'katolicka_bastina',question:'Koji je blagdan 15. kolovoza?',answers:['Uznesenje Marije – Velika Gospa','Tijelovo','Uskrs','Duhovi'],correctIndex:0},
{id:'p078',category:'katolicka_bastina',question:'Koji je svetac zaštitnik Dubrovnika?',answers:['Sveti Vlaho','Sveti Duje','Sveti Josip','Sveti Nikola'],correctIndex:0},
{id:'p079',category:'katolicka_bastina',question:'Koji je svetac zaštitnik Splita?',answers:['Sveti Duje','Sveti Vlaho','Sveti Marko','Sveti Juraj'],correctIndex:0},
{id:'p080',category:'katolicka_bastina',question:'Koje je hrvatsko svetište povezano s čudotvornim kipom Majke Božje na Trsatu?',answers:['Trsatsko svetište','Marija Bistrica','Sinj','Aljmaš'],correctIndex:0},
{id:'p081',category:'jezik',question:'Koji je hrvatski književnik napisao „Čudnovate zgode šegrta Hlapića“?',answers:['Ivana Brlić-Mažuranić','Marija Jurić Zagorka','Jagoda Truhelka','Zlata Kolarić-Kišur'],correctIndex:0},
{id:'p082',category:'jezik',question:'Tko je autor „Ribanja i ribarskoga prigovaranja“?',answers:['Petar Hektorović','Marko Marulić','Hanibal Lucić','Marin Držić'],correctIndex:0},
{id:'p083',category:'jezik',question:'Koji je književnik poznat pod nadimkom „Mažuranić“ i napisao „Smrt Smail-age Čengića“?',answers:['Ivan Mažuranić','Ivan Gundulić','Petar Preradović','August Šenoa'],correctIndex:0},
{id:'p084',category:'jezik',question:'Tko je napisao „Glembajeve“?',answers:['Miroslav Krleža','Antun Gustav Matoš','Tin Ujević','Vladimir Nazor'],correctIndex:0},
{id:'p085',category:'jezik',question:'Koji je hrvatski književnik autor pjesme „Notturno“?',answers:['Antun Gustav Matoš','Tin Ujević','Dobriša Cesarić','Vladimir Nazor'],correctIndex:0},
{id:'p086',category:'glazba',question:'Koja je tradicionalna glazbena forma povezana s Međimurjem i upisana na UNESCO-ov popis?',answers:['Međimurska popevka','Bećarac','Klapsko pjevanje','Ojkanje'],correctIndex:0},
{id:'p087',category:'glazba',question:'Koji je oblik pjevanja 2012. upisan na UNESCO-ov popis nematerijalne baštine?',answers:['Klapsko pjevanje','Tamburaško pjevanje','Zagorska popevka','Istarsko pjevanje'],correctIndex:0},
{id:'p088',category:'glazba',question:'Koji je oblik tradicijskog pjevanja povezan s vokalnom tehnikom „ojkanja“?',answers:['Ojkanje','Bećarac','Klapa','Psalmodija'],correctIndex:0},
{id:'p089',category:'glazba',question:'Koji hrvatski skladatelj nosi titulu autora opere „Nikola Šubić Zrinjski“?',answers:['Ivan pl. Zajc','Jakov Gotovac','Vatroslav Lisinski','Boris Papandopulo'],correctIndex:0},
{id:'p090',category:'glazba',question:'Koji je skladatelj napisao „Ero s onoga svijeta“?',answers:['Jakov Gotovac','Ivan pl. Zajc','Vatroslav Lisinski','Ivo Tijardović'],correctIndex:0},
{id:'p091',category:'kulturna_bastina',question:'Koliko lokaliteta Hrvatska trenutno ima na UNESCO-ovu Popisu svjetske baštine?',answers:['10','8','12','15'],correctIndex:0},
{id:'p092',category:'gradovi',question:'Koji je hrvatski grad poznat po tvrđavi sv. Mihovila?',answers:['Šibenik','Split','Pula','Zagreb'],correctIndex:0},
{id:'p093',category:'geografija',question:'Koji je nacionalni park najstariji u Hrvatskoj?',answers:['Plitvička jezera','Risnjak','Paklenica','Mljet'],correctIndex:0},
{id:'p094',category:'geografija',question:'Koji nacionalni park obuhvaća otok Mljet?',answers:['Mljet','Brijuni','Kornati','Krka'],correctIndex:0},
{id:'p095',category:'gradovi',question:'Koji se grad nalazi na četiri rijeke Kupi, Korani, Mrežnici i Dobri?',answers:['Karlovac','Sisak','Zagreb','Slavonski Brod'],correctIndex:0},
{id:'p096',category:'kraljevi',question:'Koji je kralj povezan s Bašćanskom pločom kao „Zvonimir kralj hrvatski“?',answers:['Dmitar Zvonimir','Tomislav','Petar Krešimir IV.','Stjepan Držislav'],correctIndex:0},
{id:'p097',category:'povijest',question:'Koji je hrvatski vladar bio knez 914. prema Tomi Arhiđakonu?',answers:['Tomislav','Trpimir II.','Muncimir','Mihajlo Krešimir II.'],correctIndex:0},
{id:'p098',category:'kulturna_bastina',question:'Koji je hrvatski lokalitet poznat po stećcima i nalazi se na UNESCO-ovu popisu kao dio multinacionalnog dobra?',answers:['Stećci – srednjovjekovni nadgrobni spomenici','Bašćanska ploča','Stari Grad','Eufrazijeva bazilika'],correctIndex:0},
{id:'p099',category:'gradovi',question:'Koji je grad poznat po Dioklecijanovoj palači i povijesnoj jezgri pod zaštitom UNESCO-a?',answers:['Split','Dubrovnik','Trogir','Zadar'],correctIndex:0},
{id:'p100',category:'povijest',question:'Koje godine je Hrvatska primljena u Ujedinjene narode?',answers:['1992.','1991.','1995.','1999.'],correctIndex:0}
];