// PatriaSoul – Domovinski rat
// 100 pitanja o ključnim događajima, bojištima, postrojbama i operacijama Domovinskog rata.
// Format: [pitanje, točan odgovor, distraktor 1, distraktor 2, distraktor 3].
// Centralni quiz engine preslaguje ponuđene odgovore, pa točan odgovor nije uvijek pod A.
(function(){
  const q = [
    ['Koje se godine najčešće navode kao godine Domovinskog rata?','1991.–1995.','1980.–1985.','1996.–2000.','1989.–1992.'],
    ['Koji je događaj prethodio otvorenoj agresiji na Hrvatsku 1991.?','Pobuna dijela srpskog stanovništva u Hrvatskoj','Ulazak Hrvatske u NATO','Uvođenje eura','Osnivanje UN-a'],
    ['Kada je izbila pobuna dijela srpskog stanovništva u Hrvatskoj?','U kolovozu 1990.','U veljači 1991.','U listopadu 1991.','U siječnju 1992.'],
    ['Gdje je 2. svibnja 1991. došlo do teškog sukoba u kojem je poginulo 12 hrvatskih policajaca?','Borovo Selo','Pakrac','Kijevo','Maslenica'],
    ['Kada se dogodio sukob na Plitvicama poznat kao Krvavi Uskrs?','31. ožujka 1991.','2. svibnja 1991.','25. lipnja 1991.','8. listopada 1991.'],
    ['Kako se zove policijska akcija na Plitvicama 31. ožujka 1991.?','Krvavi Uskrs','Bljesak','Oluja','Maslenica'],
    ['Koja je hrvatska postrojba prethodila ustroju Hrvatske vojske kao Zbor narodne garde?','ZNG','UNPROFOR','JNA','HVK'],
    ['Što znači kratica ZNG?','Zbor narodne garde','Zajednica narodnih gardista','Zapovjedništvo nacionalne garde','Zaštitna narodna grupa'],
    ['Kada je Hrvatska proglasila samostalnost i suverenost?','25. lipnja 1991.','30. svibnja 1990.','8. listopada 1991.','15. siječnja 1992.'],
    ['Kada je Hrvatski sabor donio odluku o raskidu državnopravnih veza s Jugoslavijom?','8. listopada 1991.','25. lipnja 1991.','5. kolovoza 1995.','15. siječnja 1992.'],
    ['Koji je grad postao jedan od najvećih simbola otpora tijekom Domovinskog rata?','Vukovar','Varaždin','Opatija','Čakovec'],
    ['Kada je pao Vukovar?','18. studenoga 1991.','8. listopada 1991.','5. kolovoza 1995.','1. svibnja 1995.'],
    ['Koliko je približno trajala opsada Vukovara?','Oko tri mjeseca','Oko tjedan dana','Oko dvije godine','Oko deset dana'],
    ['Koja je postrojba bila jezgra obrane Vukovara?','204. vukovarska brigada','4. gardijska brigada','7. gardijska brigada','1. gardijska brigada'],
    ['Tko je bio poznati zapovjednik obrane Borova Naselja?','Blago Zadro','Ante Gotovina','Mirko Norac','Damir Krstičević'],
    ['Koji je objekt u Vukovaru postao simbol stradanja ranjenika i civila?','Vukovarska bolnica','Vodotoranj u Osijeku','Pošta u Vinkovcima','Kolodvor u Iloku'],
    ['Koji je događaj vezan uz vukovarsku bolnicu 20. studenoga 1991.?','Odvođenje i ubojstvo ranjenika na Ovčari','Oslobođenje bolnice','Dolazak UNPROFOR-a','Potpisivanje Erdutskog sporazuma'],
    ['Gdje se nalazi Ovčara?','U blizini Vukovara','U blizini Dubrovnika','U Lici','U Istri'],
    ['Koji je grad u istočnoj Slavoniji bio važna točka obrane tijekom 1991.?','Osijek','Rijeka','Pula','Varaždin'],
    ['Koji je grad bio važno središte obrane u zapadnoj Slavoniji?','Pakrac','Dubrovnik','Sinj','Makarska'],
    ['Koja je akcija oslobađanja u zapadnoj Slavoniji izvedena krajem 1991.?','Orkan ’91','Oluja','Bljesak','Medački džep'],
    ['Koja je operacija na Bilogori provedena od 31. listopada do 4. studenoga 1991.?','Otkos 10','Maslenica','Bljesak','Oluja'],
    ['Koji je važan grad u zapadnoj Slavoniji oslobođen u prosincu 1991.?','Lipik','Knin','Vukovar','Petrinja'],
    ['Koji je grad na jugu Hrvatske bio pod teškim napadima 1991.?','Dubrovnik','Varaždin','Koprivnica','Bjelovar'],
    ['Kada je počeo opći napad na dubrovačko područje 1991.?','1. listopada 1991.','25. lipnja 1991.','5. kolovoza 1995.','1. svibnja 1995.'],
    ['Kada je povijesna jezgra Dubrovnika teško granatirana?','6. prosinca 1991.','18. studenoga 1991.','7. listopada 1991.','15. siječnja 1992.'],
    ['Kako se zvao humanitarni konvoj koji je stigao u Dubrovnik 1991.?','Libertas','Sloboda','Dubrovnik','Jadran'],
    ['Koji je hrvatski grad bio poznat po obrani tijekom napada JNA na Dalmaciju?','Šibenik','Varaždin','Krapina','Bjelovar'],
    ['Koja je važna bitka na šibenskom području omogućila zauzimanje topničkih položaja?','Borbe za Šibenik i oslobađanje položaja na Žirju i Zečevu','Bitka za Knin','Bitka za Vukovar','Bitka za Pakrac'],
    ['Koji je most bio ključna prometna veza Dalmacije i srušen 1991.?','Maslenički most','Pelješki most','Krčki most','Paški most'],
    ['Kada je Maslenički most srušen?','21. studenoga 1991.','8. listopada 1991.','5. kolovoza 1995.','1. svibnja 1995.'],
    ['Koja je akcija iz siječnja 1993. ponovno povezala sjevernu i južnu Hrvatsku preko područja Maslenice?','Maslenica','Bljesak','Oluja','Orkan ’91'],
    ['Kada je provedena operacija Maslenica?','U siječnju 1993.','U svibnju 1995.','U kolovozu 1995.','U listopadu 1991.'],
    ['Koji je strateški važan grad oslobođen u operaciji Maslenica?','Zadarsko zaleđe','Knin','Vukovar','Varaždin'],
    ['Koja je operacija provedena u području Medačkog džepa 1993.?','Medački džep','Oluja','Bljesak','Orkan ’91'],
    ['Koje je godine izvedena operacija Medački džep?','1993.','1991.','1994.','1995.'],
    ['Koji je grad bio središte obrane Like tijekom rata?','Gospić','Dubrovnik','Osijek','Pula'],
    ['Koja je gardijska brigada poznata kao Tigrovi?','1. gardijska brigada','2. gardijska brigada','4. gardijska brigada','7. gardijska brigada'],
    ['Koja je gardijska brigada poznata kao Gromovi?','2. gardijska brigada','1. gardijska brigada','3. gardijska brigada','9. gardijska brigada'],
    ['Koja je gardijska brigada poznata kao Kune?','3. gardijska brigada','4. gardijska brigada','5. gardijska brigada','7. gardijska brigada'],
    ['Koja je gardijska brigada poznata kao Pauci?','4. gardijska brigada','1. gardijska brigada','2. gardijska brigada','9. gardijska brigada'],
    ['Koja je gardijska brigada poznata kao Sokolovi?','5. gardijska brigada','3. gardijska brigada','7. gardijska brigada','8. brigada Vojne policije'],
    ['Koja je gardijska brigada poznata kao Pume?','7. gardijska brigada','5. gardijska brigada','4. gardijska brigada','9. gardijska brigada'],
    ['Koja je gardijska brigada poznata kao Vukovi?','9. gardijska brigada','7. gardijska brigada','2. gardijska brigada','3. gardijska brigada'],
    ['Iz kojeg je grada bila vezana 4. gardijska brigada?','Splita','Zagreba','Osijeka','Varaždina'],
    ['Koja je brigada bila posebno povezana s Gospićem i Likom?','9. gardijska brigada Vukovi','3. gardijska brigada Kune','5. gardijska brigada Sokolovi','1. gardijska brigada Tigrovi'],
    ['Koji je hrvatski vojni čin nosio Franjo Tuđman kao predsjednik i vrhovni zapovjednik?','Vrhovni zapovjednik Oružanih snaga','Načelnik Glavnog stožera','Zapovjednik ZNG-a','Ministar unutarnjih poslova'],
    ['Tko je bio prvi ministar obrane Republike Hrvatske?','Martin Špegelj','Gojko Šušak','Damir Krstičević','Ante Gotovina'],
    ['Tko je bio ministar obrane tijekom najvećeg dijela završnih operacija 1995.?','Gojko Šušak','Martin Špegelj','Janko Bobetko','Blago Zadro'],
    ['Tko je bio načelnik Glavnog stožera HV-a tijekom operacije Oluja?','Zvonimir Červenko','Blago Zadro','Mile Dedaković','Janko Bobetko'],
    ['Koji je general zapovijedao Zbornim područjem Split i bio jedan od ključnih zapovjednika Oluje?','Ante Gotovina','Janko Bobetko','Mirko Norac','Blago Zadro'],
    ['Koji je general bio zapovjednik Zbornog područja Zagreb?','Petar Stipetić','Ante Gotovina','Mladen Markač','Mirko Norac'],
    ['Koji je zapovjednik specijalne policije imao važnu ulogu u Oluji?','Mladen Markač','Blago Zadro','Mile Dedaković','Janko Bobetko'],
    ['Koja je operacija izvedena 1. i 2. svibnja 1995.?','Bljesak','Oluja','Maslenica','Medački džep'],
    ['Gdje je prvenstveno izveden Bljesak?','U zapadnoj Slavoniji','U Lici','Na dubrovačkom području','U Istri'],
    ['Koji je grad bio glavno središte oslobađanja u operaciji Bljesak?','Okučani','Knin','Vukovar','Gospić'],
    ['Koja je operacija započela 4. kolovoza 1995.?','Oluja','Bljesak','Maslenica','Orkan ’91'],
    ['Koliko je trajala glavna faza operacije Oluja?','Od 4. do 7. kolovoza 1995.','Od 1. do 2. svibnja 1995.','Od 22. do 24. siječnja 1993.','Od 15. do 18. studenoga 1991.'],
    ['Koji je grad oslobođen 5. kolovoza 1995. i postao simbol Oluje?','Knin','Vukovar','Pakrac','Gospić'],
    ['Koje su dvije gardijske brigade među prvima ušle u Knin?','4. i 7. gardijska brigada','1. i 2. gardijska brigada','3. i 5. gardijska brigada','5. i 9. gardijska brigada'],
    ['Koji se datum obilježava kao Dan pobjede i domovinske zahvalnosti?','5. kolovoza','1. svibnja','25. lipnja','8. listopada'],
    ['Koji se datum obilježava kao Dan hrvatskih branitelja?','5. kolovoza','18. studenoga','15. siječnja','30. svibnja'],
    ['Koja je operacija omogućila oslobađanje najvećeg dijela okupiranog teritorija Hrvatske?','Oluja','Bljesak','Maslenica','Medački džep'],
    ['Koje su hrvatske snage sudjelovale u Oluji?','Hrvatska vojska i specijalna policija','Samo mornarica','Samo policija','Samo zrakoplovstvo'],
    ['Na kojoj je tvrđavi podignuta hrvatska zastava nakon oslobođenja Knina?','Kninskoj tvrđavi','Kliskoj tvrđavi','Tvrđavi sv. Mihovila','Medvedgradu'],
    ['Koji je simbol hrvatske pobjede u Oluji postao posebno poznat nakon fotografije iz Knina?','Hrvatska zastava na kninskoj tvrđavi','Grb Zagreba','Zastava UN-a','Zastava Dubrovnika'],
    ['Koji je dio Hrvatske ostao izvan operacije Oluja i kasnije je mirno reintegriran?','Hrvatsko Podunavlje','Istra','Kvarner','Dubrovačko primorje'],
    ['Kako se zvala međunarodna prijelazna uprava u hrvatskom Podunavlju?','UNTAES','UNPROFOR','NATO','EUFOR'],
    ['U kojem je razdoblju provedena mirna reintegracija hrvatskog Podunavlja?','1996.–1998.','1991.–1992.','1993.–1994.','1999.–2000.'],
    ['Koji je sporazum otvorio put mirnoj reintegraciji hrvatskog Podunavlja?','Erdutski sporazum','Washingtonski sporazum','Daytonski sporazum','Vanceov plan'],
    ['Kada je potpisan Erdutski sporazum?','12. studenoga 1995.','4. kolovoza 1995.','8. listopada 1991.','1. svibnja 1995.'],
    ['Koja je međunarodna organizacija rasporedila mirovne snage u Hrvatskoj početkom 1992.?','Ujedinjeni narodi','NATO','Europska unija','OESS'],
    ['Kako se zvala mirovna misija UN-a u Hrvatskoj?','UNPROFOR','UNTAES','KFOR','IFOR'],
    ['Što je Vanceov plan predviđao u Hrvatskoj?','Razmještaj mirovnih snaga UN-a i prekid vatre','Neposredno članstvo Hrvatske u NATO-u','Podjelu Hrvatske na županije','Uvođenje nove valute'],
    ['Kada je Hrvatska međunarodno priznata kao neovisna država od većine država tadašnje EZ?','15. siječnja 1992.','25. lipnja 1991.','8. listopada 1991.','5. kolovoza 1995.'],
    ['Koji je datum međunarodnog priznanja Hrvatske posebno vezan uz 15. siječnja?','15. siječnja 1992.','15. siječnja 1991.','15. veljače 1992.','15. ožujka 1992.'],
    ['Koji je sporazum iz 1995. pridonio završetku rata u Bosni i Hercegovini?','Daytonski sporazum','Erdutski sporazum','Vanceov plan','Washingtonski sporazum'],
    ['Koji je hrvatski predsjednik bio na čelu države tijekom Domovinskog rata?','Franjo Tuđman','Stjepan Mesić','Franjo Gregurić','Vladimir Šeks'],
    ['Koji je državni praznik 30. svibnja povezan s prvim višestranačkim izborima 1990.?','Dan Hrvatskoga sabora','Dan pobjede','Dan hrvatskih branitelja','Dan neovisnosti'],
    ['Koji je važan događaj u Zagrebu 7. listopada 1991.?','Napadnut je Banski dvori','Potpisan je Erdutski sporazum','Oslobođen je Knin','Počeo je Bljesak'],
    ['Što je bilo meta raketiranja 7. listopada 1991.?','Banski dvori','Maksimir','Zračna luka Dubrovnik','Kninska tvrđava'],
    ['Koji je grad postao simbol stradanja i otpora u istočnoj Slavoniji?','Vukovar','Slavonski Brod','Đakovo','Našice'],
    ['Koje je selo u zadarskom zaleđu teško stradalo 18. studenoga 1991.?','Škabrnja','Kijevo','Ćelije','Lovas'],
    ['Koje je selo u dalmatinskom zaleđu bilo simbol ranih napada 1990.–1991.?','Kijevo','Okučani','Dalj','Antunovac'],
    ['Koji je grad bio poznat po obrani i teškim napadima na području Banovine?','Petrinja','Poreč','Rovinj','Sinj'],
    ['Koji je grad bio ključna obrambena točka na Kordunu?','Karlovac','Pula','Dubrovnik','Vinkovci'],
    ['Koji je grad bio važno središte obrane na Banovini?','Sisak','Zadar','Trogir','Varaždin'],
    ['Koja je hrvatska vojna grana imala važnu ulogu u obrani Jadrana?','Hrvatska ratna mornarica','Hrvatsko ratno zrakoplovstvo','Vojna policija','Inženjerija'],
    ['Što je Hrvatska ratna mornarica uspješno učinila u studenome 1991. u Splitskom i Korčulanskom kanalu?','Razbila pomorsku blokadu Splita','Oslobodila Knin','Zauzela Vukovar','Provela mirnu reintegraciju'],
    ['Koji je događaj označio završetak glavnih borbenih operacija u Hrvatskoj?','Oslobađanje većine okupiranog teritorija u Oluji i potom mirna reintegracija Podunavlja','Potpisivanje Vanceova plana','Uvođenje UNPROFOR-a','Krvavi Uskrs'],
    ['Koji je izraz najčešće povezan s hrvatskim vojnicima i policajcima koji su branili zemlju?','Hrvatski branitelji','UN promatrači','Plave kacige','Miropisci'],
    ['Kako se službeno nazivaju oružane snage Republike Hrvatske danas?','Oružane snage Republike Hrvatske','Zbor narodne garde','Jugoslavenska narodna armija','Teritorijalna obrana'],
    ['Koji je grad bio simbol završne pobjede 1995. zbog svog strateškog i simboličkog značenja?','Knin','Pula','Varaždin','Rijeka'],
    ['Koji je datum početka operacije Bljesak?','1. svibnja 1995.','4. kolovoza 1995.','5. kolovoza 1995.','22. siječnja 1993.'],
    ['Koji je datum početka operacije Oluja?','4. kolovoza 1995.','1. svibnja 1995.','5. kolovoza 1995.','8. listopada 1991.'],
    ['Koja je hrvatska akcija prethodila Oluji kao velika operacija oslobađanja zapadne Slavonije?','Bljesak','Maslenica','Oluja','Medački džep'],
    ['Koji je izraz najprikladniji za karakter hrvatskih završnih operacija 1995.?','Vojno-redarstvene operacije','Pomorske blokade','Mirovne konferencije','Humanitarne misije'],
    ['Koji je glavni cilj Domovinskog rata za Republiku Hrvatsku bio?','Obrana i uspostava neovisnosti i teritorijalne cjelovitosti Hrvatske','Širenje hrvatskog teritorija izvan međunarodno priznatih granica','Osnivanje nove Jugoslavije','Uspostava kolonijalne vlasti'],
    ['Koja je institucija 1991. bila najviše tijelo zakonodavne vlasti Republike Hrvatske?','Hrvatski sabor','Glavni stožer','MUP','UNPROFOR'],
    ['Koji je dokument iz 1991. utvrdio temeljni okvir državne samostalnosti Hrvatske?','Ustavna odluka o suverenosti i samostalnosti Republike Hrvatske','Erdutski sporazum','Vanceov plan','Daytonski sporazum'],
    ['Koji je grad bio posebno važan za obranu istočne Hrvatske uz Vukovar?','Vinkovci','Pula','Rijeka','Dubrovnik'],
    ['Koji je hrvatski grad bio poznat po obrani i granatiranju na sjevernom dijelu bojišta?','Slavonski Brod','Opatija','Umag','Makarska'],
    ['Koji je događaj 1995. označio oslobađanje zapadne Slavonije?','Operacija Bljesak','Operacija Oluja','Operacija Maslenica','Operacija Orkan ’91'],
    ['Koji je događaj 1995. označio oslobađanje Knina i velikog dijela okupiranog teritorija?','Operacija Oluja','Operacija Bljesak','Operacija Medački džep','Operacija Maslenica'],
    ['Koja je hrvatska operacija iz 1993. vezana uz područje Like i Gospića?','Medački džep','Bljesak','Oluja','Orkan ’91'],
    ['Koja je operacija iz 1993. bila važna za područje zadarskog zaleđa i Maslenice?','Maslenica','Bljesak','Oluja','Otkos 10'],
    ['Koja je operacija iz 1991. vezana uz Bilogoru?','Otkos 10','Oluja','Bljesak','Medački džep'],
    ['Koja je operacija iz 1991. bila jedna od većih hrvatskih akcija u zapadnoj Slavoniji?','Orkan ’91','Maslenica','Bljesak','Oluja'],
    ['Koji je događaj 1995. omogućio hrvatskim snagama prodor prema državnoj granici u Dalmaciji?','Operacija Oluja','Operacija Bljesak','Operacija Maslenica','Krvavi Uskrs'],
    ['Koji je grad oslobođen u Bljesku i bio središte srpske okupacijske vlasti u zapadnoj Slavoniji?','Okučani','Knin','Vukovar','Petrinja'],
    ['Koji je grad bio sjedište Zbornog područja Split?','Split','Zagreb','Osijek','Gospić'],
    ['Koji je grad bio sjedište Zbornog područja Gospić?','Gospić','Varaždin','Pula','Dubrovnik'],
    ['Koja je hrvatska postrojba poznata po nadimku Orlovi?','8. lako jurišna brigada Vojne policije','1. gardijska brigada','5. gardijska brigada','9. gardijska brigada'],
    ['Koja je brigada nosila nadimak Marijan Celjak?','57. brigada','99. brigada','104. brigada','125. brigada'],
    ['Koji je grad bio važan za obranu i logistiku hrvatskih snaga u sjeverozapadnoj Hrvatskoj?','Varaždin','Dubrovnik','Knin','Vukovar'],
    ['Koji je događaj omogućio Hrvatskoj da krajem 1991. preuzme značajne količine oružja iz vojarni?','Blokada i predaja dijela vojarni JNA','Dolazak UNPROFOR-a','Međunarodno priznanje','Erdutski sporazum'],
    ['Kako se nazivaju zarobljeni i zatočeni hrvatski branitelji i civili koje su držale srpske snage?','Zatočenici','UN promatrači','Mirovnjaci','Dezerteri'],
    ['Koji je grad bio jedno od najpoznatijih mjesta razmjene i oslobađanja zatočenika?','Nemetin','Knin','Sinj','Pula'],
    ['Koja je međunarodna organizacija bila uključena u nadzor primirja i mirovne operacije u Hrvatskoj?','Ujedinjeni narodi','NATO','Europska komisija','Svjetska banka'],
    ['Koja je država bila glavni izvor izravne vojne potpore srpskim snagama u Hrvatskoj tijekom agresije?','Srbija','Austrija','Italija','Mađarska'],
    ['Koje su oružane snage tadašnje Jugoslavije imale ključnu ulogu u napadu na Hrvatsku?','JNA','NATO','UNPROFOR','HV'],
    ['Što znači kratica JNA?','Jugoslavenska narodna armija','Jadranska narodna armija','Jugoslavenska nacionalna administracija','Jedinstvena narodna akcija'],
    ['Koji je hrvatski simbol postao posebno poznat zbog obrane Vukovara?','Vukovarski vodotoranj','Dioklecijanova palača','Katedrala sv. Jakova','Lotrščak'],
    ['Koji je datum Dan sjećanja na žrtve Domovinskog rata i Dan sjećanja na žrtvu Vukovara i Škabrnje?','18. studenoga','5. kolovoza','1. svibnja','25. lipnja'],
    ['Koja je glavna poruka Dana sjećanja 18. studenoga?','Sjećanje na žrtve Domovinskog rata, Vukovara i Škabrnje','Proslava međunarodnog priznanja','Obilježavanje početka Bljeska','Dan osnutka ZNG-a'],
    ['Koji je grad simbol hrvatske obrane na krajnjem jugu?','Dubrovnik','Varaždin','Bjelovar','Koprivnica'],
    ['Koji je grad simbol hrvatske obrane u Lici?','Gospić','Pula','Rijeka','Varaždin'],
    ['Koji je grad simbol hrvatske obrane u istočnoj Slavoniji?','Vukovar','Karlovac','Zagreb','Sinj'],
    ['Koji je grad simbol hrvatske obrane na Banovini?','Sisak','Dubrovnik','Poreč','Trogir'],
    ['Koji je grad simbol hrvatske obrane na karlovačkom području?','Karlovac','Pula','Split','Šibenik'],
    ['Koji je grad bio jedno od važnih središta obrane sjeverne Dalmacije?','Zadar','Varaždin','Krapina','Bjelovar'],
    ['Koji je grad bio posebno važan u obrani južne Dalmacije osim Dubrovnika?','Ston','Varaždin','Čakovec','Koprivnica'],
    ['Koji je događaj označio kraj izravne blokade Dubrovnika nakon obrambenih uspjeha 1992.?','Oslobađanje hrvatskog juga','Pad Vukovara','Bljesak','Otkos 10'],
    ['Koja je godina međunarodnog priznanja Hrvatske?','1992.','1990.','1991.','1995.'],
    ['Koja je godina operacije Bljesak?','1995.','1993.','1992.','1991.'],
    ['Koja je godina operacije Oluja?','1995.','1994.','1993.','1992.'],
    ['Koja je godina operacije Maslenica?','1993.','1991.','1995.','1994.'],
    ['Koja je godina operacije Medački džep?','1993.','1992.','1994.','1995.']
  ];

  // Registracija u globalni registar koji koristi PatriaSoul quiz engine.
  window.PatriaSoulQuizBanks = window.PatriaSoulQuizBanks || {};
  window.PatriaSoulQuizBanks.domovinskiRat = q;
  window.domovinskiRatQuiz = q;
})();
