/* PatriaSoul — urednički vizualni sloj. Privremene ilustracije lako se zamijene stvarnim fotografijama. */
(function(){
  'use strict';
  var path=location.pathname.toLowerCase();
  var profiles={
    '/domovina.html':{key:'hrvatska',title:'Hrvatska kao prostor života, povijesti i identiteta',text:'Domovina nije samo zemljopisni pojam. Ona obuhvaća prostor u kojem se kroz stoljeća susreću obala i kontinent, gradovi i sela, različite regionalne tradicije, vjera, jezik, kultura i iskustva generacija. Zato PatriaSoul Hrvatsku promatra kroz više povezanih slojeva: prostor, povijest, ljude, baštinu i sjećanje.',text2:'Cilj nije stvarati kratki katalog činjenica, nego graditi preglednu digitalnu zbirku u kojoj korisnik može krenuti od jedne teme i nastaviti prema drugoj. Grad vodi prema povijesti i baštini; povijesni događaj prema osobama i mjestima; mjesto prema spomenicima i pričama. Na taj način sadržaj postaje povezana priča, a ne skup nepovezanih stranica.'},
    '/povijest.html':{key:'povijest',title:'Povijest se čita kroz vrijeme, mjesta i ljude',text:'Povijesni sadržaj PatriaSoula treba biti dovoljno širok da pokaže kontinuitete i promjene, ali dovoljno oprezan da ne pretvara predaju, političko tumačenje ili popularni mit u neupitnu činjenicu. Svako razdoblje zato treba promatrati u njegovom vlastitom kontekstu i, gdje je moguće, povezati ga s relevantnim izvorima.',text2:'Posebnu vrijednost imaju lokalne priče. Iza velikih događaja uvijek stoje gradovi, sela, obitelji, vojnici, svećenici, umjetnici, obrtnici i obični ljudi. Upravo zato će se povijesne teme postupno povezivati s gradskim profilima, baštinom, spomenicima i osobama, kako bi se velika kronologija mogla čitati i kroz konkretna mjesta.'},
    '/bastina.html':{key:'bastina',title:'Baština nije samo ono što je staro — nego ono što prenosimo dalje',text:'Hrvatska baština obuhvaća materijalnu i nematerijalnu baštinu: povijesne gradove i građevine, sakralnu arhitekturu, utvrde, arheološka nalazišta, umjetnost, glazbu, običaje, govor, gastronomiju, procesije i različite oblike tradicijskog života. Različite hrvatske regije imaju vlastite izraze, ali zajedno čine iznimno raznoliku kulturnu cjelinu.',text2:'Na PatriaSoulu baština se zato ne svodi na popis znamenitosti. Uz svaku temu treba ponuditi kontekst: gdje se nalazi, kako je nastala, što je oblikovalo njezin razvoj, kako se čuva danas i s kojim je drugim sadržajima povezana. Kada korisnik vidi fotografiju, pročita priču i može nastaviti prema gradu ili povijesnom razdoblju, baština dobiva život.'},
    '/branitelji.html':{key:'branitelji',title:'Sjećanje mora imati činjenice, mjesta i ljudsko dostojanstvo',text:'Sadržaj o Domovinskom ratu traži posebno ozbiljan pristup. Uz opći pregled potrebno je jasno razlikovati postrojbe, operacije, mjesta, datume, izvore i osobne priče. PatriaSoul zato gradi registre koji mogu povezivati brigade, postrojbe, operacije, gradove, spomenike i relevantne izvore bez nepotrebnog ponavljanja podataka.',text2:'Posebno mjesto imaju ljudi i mjesta. Ratna povijest nije samo popis operacija nego i iskustvo gradova, obitelji i branitelja. Vizualni sadržaj treba služiti razumijevanju i sjećanju, a tekst treba biti pisan dostojanstveno, provjerljivo i bez izmišljanja podataka koji još nisu potvrđeni.'},
    '/vjera.html':{key:'vjera',title:'Vjera kao dio hrvatske duhovne i kulturne baštine',text:'Vjera je kroz stoljeća ostavila dubok trag u hrvatskoj kulturi, umjetnosti, arhitekturi, književnosti, blagdanskim običajima i svakodnevnom životu. PatriaSoul prostor vjere zamišlja kao miran i pregledan dio portala u kojem se mogu susresti Evanđelje, molitva, Biblija, krunica, blagdani, sveti i blaženici te duhovne misli.',text2:'Sadržaj treba biti pristupačan i ozbiljan: uz kratke tekstove mogu stajati objašnjenja, poveznice prema izvorima, slike sakralne baštine i povezana mjesta. Tako se duhovna tema može povezati i s kulturnom baštinom, gradovima i povijesnim razvojem hrvatskog prostora.'},
    '/gradovi.html':{key:'hrvatska',title:'Gradovi su živa karta hrvatske povijesti',text:'Svaki hrvatski grad nosi vlastitu kombinaciju zemljopisnog položaja, povijesti, arhitekture, ljudi, gospodarstva, običaja i sjećanja. Zato registar gradova nije zamišljen kao običan popis imena. Svaki grad dobiva vlastiti profil koji se može širiti kako se prikupljaju provjereni podaci i kvalitetne fotografije.',text2:'Konačni cilj je da korisnik iz pregleda svih gradova može doći do detaljne priče: od osnovnih podataka i županije, preko povijesti i znamenitosti, do vjere, tradicije, Domovinskog rata, spomenika i kvizova. Fotografije će se moći zamijeniti vlastitim materijalima bez promjene strukture stranice.'},
    '/brigade.html':{key:'branitelji',title:'Brigade kao dio strukturiranog pregleda Domovinskog rata',text:'Registar brigada treba biti više od kartica s nazivom. Kada se podaci potvrde i prošire, svaki zapis može povezivati naziv i broj postrojbe, sjedište, područje djelovanja, razdoblje, povezane operacije, mjesta sjećanja i izvore. Tako se pojedina brigada može promatrati unutar šireg konteksta rata.',text2:'Važno je zadržati uredničku disciplinu: nepotvrđene podatke ne treba popunjavati pretpostavkama. Umjesto toga, profil se može označiti kao sadržaj u izgradnji i postupno dopunjavati provjerenim izvorima, dokumentima i fotografijama.'},
    '/operacije.html':{key:'branitelji',title:'Operacije i bojišta: događaji povezani s prostorom',text:'Operacije se najbolje razumiju kada se povežu s kartom, vremenom, postrojbama i mjestima. Zato će PatriaSoul postupno povezivati operativne zapise s brigadama, gradovima, spomenicima i drugim relevantnim sadržajem.',text2:'Vizualni elementi ovdje imaju posebnu ulogu: karta, fotografija mjesta ili arhivski materijal mogu korisniku pomoći da razumije prostor i slijed događaja. Privremene ilustracije služe samo kao prijelazno rješenje dok se ne dodaju provjerene fotografije i dokumenti.'},
    '/spomenici.html':{key:'branitelji',title:'Mjesta sjećanja zaslužuju prostor i kontekst',text:'Spomenik nije samo objekt na karti. On je dio lokalne memorije i često govori o ljudima, događajima i zajednici koja ga je podigla. Zato svaki zapis treba, kada su podaci dostupni, sadržavati mjesto, namjenu, povezan događaj ili osobu, osnovne podatke o nastanku te fotografiju.',text2:'Središnji registar omogućuje da se isto mjesto sjećanja prikaže na profilu grada, u temi branitelja i u zasebnoj galeriji. Time se izbjegava rasipanje podataka i stvara bogatiji kontekst za korisnika.'},
    '/brani-svoj-grad.html':{key:'hrvatska',title:'Brani svoj grad: znanje pretvaramo u iskustvo',text:'Igra je zamišljena kao interaktivni nastavak sadržaja portala. Gradovi, povijest, baština i nacionalno znanje postaju pitanja i izazovi, a igrač kroz to učenje upoznaje Hrvatsku iz drugog kuta.',text2:'Kako se baze budu širile, igra može koristiti sve više lokalnih pitanja, dnevne i tjedne izazove, značke, XP i rang-liste. Tako korisnik ne dobiva samo rezultat nego i razlog da se vrati, nauči nešto novo i istraži temu koja mu je bila nepoznata.'}
  };
  var p=profiles[path];
  var imgBase='/assets/editorial/';
  var imgMap={hrvatska:'hrvatska.svg',povijest:'povijest.svg',bastina:'bastina.svg',branitelji:'branitelji.svg',vjera:'vjera.svg'};
  function figure(key,caption){var f=document.createElement('figure');f.className='ps-editorial-figure';var img=document.createElement('img');img.src=imgBase+imgMap[key];img.alt=caption;img.loading='lazy';var c=document.createElement('figcaption');c.textContent=caption+' · privremena ilustracija';f.append(img,c);return f;}
  function addIntro(){if(!p||document.querySelector('[data-editorial-intro]'))return;var main=document.querySelector('main');if(!main)return;var hero=main.querySelector('.ps-page-hero,.history-hero,.home-hero');var box=document.createElement('section');box.className='ps-editorial-intro';box.setAttribute('data-editorial-intro','true');box.innerHTML='<div class="container"><div class="ps-editorial-copy"><span class="eyebrow">PATRIA SOUL · U FOKUSU</span><h2>'+p.title+'</h2><p>'+p.text+'</p><p>'+p.text2+'</p></div></div></section>';if(hero&&hero.nextSibling)hero.parentNode.insertBefore(box,hero.nextSibling);else main.insertBefore(box,main.firstChild);}
  function addArticleImages(){var main=document.querySelector('main');if(!main)return;var sections=[].slice.call(main.querySelectorAll('section')).filter(function(s){return !s.classList.contains('ps-editorial-intro')&&!s.classList.contains('home-hero')&&!s.classList.contains('home-anniv');});if(!sections.length)return;var keys=['hrvatska','povijest','bastina','branitelji','vjera'];var i=0;sections.forEach(function(s,idx){if(s.querySelector('img')||idx===0)return;if(idx%2===1){var key=p?p.key:keys[i%keys.length];var fig=figure(key,s.querySelector('h2,h3,h1')?.textContent||'PatriaSoul sadržaj');s.insertBefore(fig,s.firstChild);i++;}});}
  function init(){addIntro();addArticleImages();document.body.classList.add('ps-editorial-ready');}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
