// PatriaSoul – kanonski registar gradova Hrvatske (Faza 2)
// Izvor teritorijalnog ustroja: Ministarstvo pravosuđa, uprave i digitalne transformacije RH.
// Ne duplicirati gradove u drugim JS bazama; ovaj registar je jedini izvor za Gradovi hub.
window.PATRIA_CITY_DATA = [
  {"name":"Dugo Selo","slug":"dugo-selo","county":"Zagrebačka županija","source":"mpudt-jls"},{"name":"Ivanić-Grad","slug":"ivanic-grad","county":"Zagrebačka županija","source":"mpudt-jls"},{"name":"Jastrebarsko","slug":"jastrebarsko","county":"Zagrebačka županija","source":"mpudt-jls"},{"name":"Samobor","slug":"samobor","county":"Zagrebačka županija","source":"mpudt-jls"},{"name":"Sveta Nedelja","slug":"sveta-nedelja","county":"Zagrebačka županija","source":"mpudt-jls"},{"name":"Sveti Ivan Zelina","slug":"sveti-ivan-zelina","county":"Zagrebačka županija","source":"mpudt-jls"},{"name":"Velika Gorica","slug":"velika-gorica","county":"Zagrebačka županija","source":"mpudt-jls"},{"name":"Vrbovec","slug":"vrbovec","county":"Zagrebačka županija","source":"mpudt-jls"},{"name":"Zaprešić","slug":"zapresic","county":"Zagrebačka županija","source":"mpudt-jls"},
  {"name":"Donja Stubica","slug":"donja-stubica","county":"Krapinsko-zagorska županija","source":"mpudt-jls"},{"name":"Klanjec","slug":"klanjec","county":"Krapinsko-zagorska županija","source":"mpudt-jls"},{"name":"Krapina","slug":"krapina","county":"Krapinsko-zagorska županija","source":"mpudt-jls"},{"name":"Oroslavje","slug":"oroslavje","county":"Krapinsko-zagorska županija","source":"mpudt-jls"},{"name":"Pregrada","slug":"pregrada","county":"Krapinsko-zagorska županija","source":"mpudt-jls"},{"name":"Zabok","slug":"zabok","county":"Krapinsko-zagorska županija","source":"mpudt-jls"},{"name":"Zlatar","slug":"zlatar","county":"Krapinsko-zagorska županija","source":"mpudt-jls"},
  {"name":"Glina","slug":"glina","county":"Sisačko-moslavačka županija","source":"mpudt-jls"},{"name":"Hrvatska Kostajnica","slug":"hrvatska-kostajnica","county":"Sisačko-moslavačka županija","source":"mpudt-jls"},{"name":"Kutina","slug":"kutina","county":"Sisačko-moslavačka županija","source":"mpudt-jls"},{"name":"Novska","slug":"novska","county":"Sisačko-moslavačka županija","source":"mpudt-jls"},{"name":"Petrinja","slug":"petrinja","county":"Sisačko-moslavačka županija","source":"mpudt-jls"},{"name":"Popovača","slug":"popovaca","county":"Sisačko-moslavačka županija","source":"mpudt-jls"},{"name":"Sisak","slug":"sisak","county":"Sisačko-moslavačka županija","source":"mpudt-jls"},
  {"name":"Duga Resa","slug":"duga-resa","county":"Karlovačka županija","source":"mpudt-jls"},{"name":"Karlovac","slug":"karlovac","county":"Karlovačka županija","source":"mpudt-jls"},{"name":"Ogulin","slug":"ogulin","county":"Karlovačka županija","source":"mpudt-jls"},{"name":"Ozalj","slug":"ozalj","county":"Karlovačka županija","source":"mpudt-jls"},{"name":"Slunj","slug":"slunj","county":"Karlovačka županija","source":"mpudt-jls"},
  {"name":"Ivanec","slug":"ivanec","county":"Varaždinska županija","source":"mpudt-jls"},{"name":"Lepoglava","slug":"lepoglava","county":"Varaždinska županija","source":"mpudt-jls"},{"name":"Ludbreg","slug":"ludbreg","county":"Varaždinska županija","source":"mpudt-jls"},{"name":"Novi Marof","slug":"novi-marof","county":"Varaždinska županija","source":"mpudt-jls"},{"name":"Varaždin","slug":"varazdin","county":"Varaždinska županija","source":"mpudt-jls"},{"name":"Varaždinske Toplice","slug":"varazdinske-toplice","county":"Varaždinska županija","source":"mpudt-jls"},
  {"name":"Đurđevac","slug":"durdevac","county":"Koprivničko-križevačka županija","source":"mpudt-jls"},{"name":"Koprivnica","slug":"koprivnica","county":"Koprivničko-križevačka županija","source":"mpudt-jls"},{"name":"Križevci","slug":"krizevci","county":"Koprivničko-križevačka županija","source":"mpudt-jls"},
  {"name":"Bjelovar","slug":"bjelovar","county":"Bjelovarsko-bilogorska županija","source":"mpudt-jls"},{"name":"Čazma","slug":"cazma","county":"Bjelovarsko-bilogorska županija","source":"mpudt-jls"},{"name":"Daruvar","slug":"daruvar","county":"Bjelovarsko-bilogorska županija","source":"mpudt-jls"},{"name":"Garešnica","slug":"garesnica","county":"Bjelovarsko-bilogorska županija","source":"mpudt-jls"},{"name":"Grubišno Polje","slug":"grubisno-polje","county":"Bjelovarsko-bilogorska županija","source":"mpudt-jls"},
  {"name":"Bakar","slug":"bakar","county":"Primorsko-goranska županija","source":"mpudt-jls"},{"name":"Cres","slug":"cres","county":"Primorsko-goranska županija","source":"mpudt-jls"},{"name":"Crikvenica","slug":"crikvenica","county":"Primorsko-goranska županija","source":"mpudt-jls"},{"name":"Čabar","slug":"cabar","county":"Primorsko-goranska županija","source":"mpudt-jls"},{"name":"Delnice","slug":"delnice","county":"Primorsko-goranska županija","source":"mpudt-jls"},{"name":"Kastav","slug":"kastav","county":"Primorsko-goranska županija","source":"mpudt-jls"},{"name":"Kraljevica","slug":"kraljevica","county":"Primorsko-goranska županija","source":"mpudt-jls"},{"name":"Krk","slug":"krk","county":"Primorsko-goranska županija","source":"mpudt-jls"},{"name":"Mali Lošinj","slug":"mali-losinj","county":"Primorsko-goranska županija","source":"mpudt-jls"},{"name":"Novi Vinodolski","slug":"novi-vinodolski","county":"Primorsko-goranska županija","source":"mpudt-jls"},{"name":"Opatija","slug":"opatija","county":"Primorsko-goranska županija","source":"mpudt-jls"},{"name":"Rab","slug":"rab","county":"Primorsko-goranska županija","source":"mpudt-jls"},{"name":"Rijeka","slug":"rijeka","county":"Primorsko-goranska županija","source":"mpudt-jls"},{"name":"Vrbovsko","slug":"vrbovsko","county":"Primorsko-goranska županija","source":"mpudt-jls"},
  {"name":"Gospić","slug":"gospic","county":"Ličko-senjska županija","source":"mpudt-jls"},{"name":"Novalja","slug":"novalja","county":"Ličko-senjska županija","source":"mpudt-jls"},{"name":"Otočac","slug":"otocac","county":"Ličko-senjska županija","source":"mpudt-jls"},{"name":"Senj","slug":"senj","county":"Ličko-senjska županija","source":"mpudt-jls"},
  {"name":"Orahovica","slug":"orahovica","county":"Virovitičko-podravska županija","source":"mpudt-jls"},{"name":"Slatina","slug":"slatina","county":"Virovitičko-podravska županija","source":"mpudt-jls"},{"name":"Virovitica","slug":"virovitica","county":"Virovitičko-podravska županija","source":"mpudt-jls"},
  {"name":"Kutjevo","slug":"kutjevo","county":"Požeško-slavonska županija","source":"mpudt-jls"},{"name":"Lipik","slug":"lipik","county":"Požeško-slavonska županija","source":"mpudt-jls"},{"name":"Pakrac","slug":"pakrac","county":"Požeško-slavonska županija","source":"mpudt-jls"},{"name":"Pleternica","slug":"pleternica","county":"Požeško-slavonska županija","source":"mpudt-jls"},{"name":"Požega","slug":"pozega","county":"Požeško-slavonska županija","source":"mpudt-jls"},
  {"name":"Nova Gradiška","slug":"nova-gradiska","county":"Brodsko-posavska županija","source":"mpudt-jls"},{"name":"Slavonski Brod","slug":"slavonski-brod","county":"Brodsko-posavska županija","source":"mpudt-jls"},
  {"name":"Benkovac","slug":"benkovac","county":"Zadarska županija","source":"mpudt-jls"},{"name":"Biograd na Moru","slug":"biograd-na-moru","county":"Zadarska županija","source":"mpudt-jls"},{"name":"Nin","slug":"nin","county":"Zadarska županija","source":"mpudt-jls"},{"name":"Obrovac","slug":"obrovac","county":"Zadarska županija","source":"mpudt-jls"},{"name":"Pag","slug":"pag","county":"Zadarska županija","source":"mpudt-jls"},{"name":"Zadar","slug":"zadar","county":"Zadarska županija","source":"mpudt-jls"},
  {"name":"Beli Manastir","slug":"beli-manastir","county":"Osječko-baranjska županija","source":"mpudt-jls"},{"name":"Belišće","slug":"belisce","county":"Osječko-baranjska županija","source":"mpudt-jls"},{"name":"Đakovo","slug":"dakovo","county":"Osječko-baranjska županija","source":"mpudt-jls"},{"name":"Donji Miholjac","slug":"donji-miholjac","county":"Osječko-baranjska županija","source":"mpudt-jls"},{"name":"Našice","slug":"nasice","county":"Osječko-baranjska županija","source":"mpudt-jls"},{"name":"Osijek","slug":"osijek","county":"Osječko-baranjska županija","source":"mpudt-jls"},{"name":"Valpovo","slug":"valpovo","county":"Osječko-baranjska županija","source":"mpudt-jls"},
  {"name":"Drniš","slug":"drnis","county":"Šibensko-kninska županija","source":"mpudt-jls"},{"name":"Knin","slug":"knin","county":"Šibensko-kninska županija","source":"mpudt-jls"},{"name":"Skradin","slug":"skradin","county":"Šibensko-kninska županija","source":"mpudt-jls"},{"name":"Šibenik","slug":"sibenik","county":"Šibensko-kninska županija","source":"mpudt-jls"},{"name":"Vodice","slug":"vodice","county":"Šibensko-kninska županija","source":"mpudt-jls"},
  {"name":"Ilok","slug":"ilok","county":"Vukovarsko-srijemska županija","source":"mpudt-jls"},{"name":"Otok","slug":"otok","county":"Vukovarsko-srijemska županija","source":"mpudt-jls"},{"name":"Vinkovci","slug":"vinkovci","county":"Vukovarsko-srijemska županija","source":"mpudt-jls"},{"name":"Vukovar","slug":"vukovar","county":"Vukovarsko-srijemska županija","source":"mpudt-jls"},{"name":"Županja","slug":"zupanja","county":"Vukovarsko-srijemska županija","source":"mpudt-jls"},
  {"name":"Hvar","slug":"hvar","county":"Splitsko-dalmatinska županija","source":"mpudt-jls"},{"name":"Imotski","slug":"imotski","county":"Splitsko-dalmatinska županija","source":"mpudt-jls"},{"name":"Kaštela","slug":"kastela","county":"Splitsko-dalmatinska županija","source":"mpudt-jls"},{"name":"Komiža","slug":"komiza","county":"Splitsko-dalmatinska županija","source":"mpudt-jls"},{"name":"Makarska","slug":"makarska","county":"Splitsko-dalmatinska županija","source":"mpudt-jls"},{"name":"Omiš","slug":"omis","county":"Splitsko-dalmatinska županija","source":"mpudt-jls"},{"name":"Sinj","slug":"sinj","county":"Splitsko-dalmatinska županija","source":"mpudt-jls"},{"name":"Solin","slug":"solin","county":"Splitsko-dalmatinska županija","source":"mpudt-jls"},{"name":"Split","slug":"split","county":"Splitsko-dalmatinska županija","source":"mpudt-jls"},{"name":"Stari Grad","slug":"stari-grad","county":"Splitsko-dalmatinska županija","source":"mpudt-jls"},{"name":"Supetar","slug":"supetar","county":"Splitsko-dalmatinska županija","source":"mpudt-jls"},{"name":"Trogir","slug":"trogir","county":"Splitsko-dalmatinska županija","source":"mpudt-jls"},{"name":"Trilj","slug":"trilj","county":"Splitsko-dalmatinska županija","source":"mpudt-jls"},{"name":"Vis","slug":"vis","county":"Splitsko-dalmatinska županija","source":"mpudt-jls"},{"name":"Vrlika","slug":"vrlika","county":"Splitsko-dalmatinska županija","source":"mpudt-jls"},{"name":"Vrgorac","slug":"vrgorac","county":"Splitsko-dalmatinska županija","source":"mpudt-jls"},
  {"name":"Buje","slug":"buje","county":"Istarska županija","source":"mpudt-jls"},{"name":"Buzet","slug":"buzet","county":"Istarska županija","source":"mpudt-jls"},{"name":"Labin","slug":"labin","county":"Istarska županija","source":"mpudt-jls"},{"name":"Novigrad","slug":"novigrad","county":"Istarska županija","source":"mpudt-jls"},{"name":"Pazin","slug":"pazin","county":"Istarska županija","source":"mpudt-jls"},{"name":"Poreč","slug":"porec","county":"Istarska županija","source":"mpudt-jls"},{"name":"Pula","slug":"pula","county":"Istarska županija","source":"mpudt-jls"},{"name":"Rovinj","slug":"rovinj","county":"Istarska županija","source":"mpudt-jls"},{"name":"Umag","slug":"umag","county":"Istarska županija","source":"mpudt-jls"},
  {"name":"Dubrovnik","slug":"dubrovnik","county":"Dubrovačko-neretvanska županija","source":"mpudt-jls"},{"name":"Korčula","slug":"korcula","county":"Dubrovačko-neretvanska županija","source":"mpudt-jls"},{"name":"Metković","slug":"metkovic","county":"Dubrovačko-neretvanska županija","source":"mpudt-jls"},{"name":"Opuzen","slug":"opuzen","county":"Dubrovačko-neretvanska županija","source":"mpudt-jls"},{"name":"Ploče","slug":"ploce","county":"Dubrovačko-neretvanska županija","source":"mpudt-jls"},
  {"name":"Čakovec","slug":"cakovec","county":"Međimurska županija","source":"mpudt-jls"},{"name":"Mursko Središće","slug":"mursko-sredisce","county":"Međimurska županija","source":"mpudt-jls"},{"name":"Prelog","slug":"prelog","county":"Međimurska županija","source":"mpudt-jls"},{"name":"Zagreb","slug":"zagreb","county":"Grad Zagreb","source":"mpudt-jls"}
];
window.PATRIA_CITIES = window.PATRIA_CITY_DATA.map(c => c.name);
