// PatriaSoul — javna rang-lista s Supabase adapterom i sigurnim lokalnim fallbackom.
(function(global){'use strict';
 const KEY='patriasoul_leaderboard_v3';
 function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch(_){return []}}
 function save(x){try{localStorage.setItem(KEY,JSON.stringify(x.slice(-500)))}catch(_){}return x}
 function localSubmit(result){const p=global.PatriaPlayer.current();const r={id:(crypto.randomUUID?.()||Date.now()+''),name:p.name||'Gost',xp:Math.max(0,Number(result.xp)||0),points:Math.max(0,Number(result.points)||0),quizzes:1,correct:Math.max(0,Number(result.correct)||0),city:result.city||null,date:new Date().toISOString(),period:result.period||'all'};const rows=read();rows.push(r);save(rows);return r}
 async function submit(result){const sb=global.PatriaSupabase?.client;if(!sb)return localSubmit(result);const u=(await sb.auth.getUser()).data.user;if(!u)return localSubmit(result);const r={user_id:u.id,category:String(result.category||'mijesano'),period:['daily','weekly','monthly','all'].includes(result.period)?result.period:'all',points:Math.min(100000,Math.max(0,Number(result.points)||0)),xp:Math.min(100000,Math.max(0,Number(result.xp)||0)),correct:Math.max(0,Number(result.correct)||0),answers:Math.max(0,Number(result.answers)||0),city:result.city||null,metadata:{source:'quiz'}};const {data,error}=await sb.from('quiz_results').insert(r).select().single();if(error){console.warn('PatriaSoul leaderboard fallback:',error);return localSubmit(result)}return data}
 async function aggregate(type='points',period='all'){const sb=global.PatriaSupabase?.client;if(sb){if(period==='all'){const {data,error}=await sb.from('leaderboard_all').select('*').order(type==='xp'?'xp':'points',{ascending:false}).limit(100);if(!error)return data||[]}const {data,error}=await sb.from('leaderboard_period').select('*').eq('period',period).order(type==='xp'?'xp':'points',{ascending:false}).limit(100);if(!error)return data||[]}
 const rows=read(),map=new Map();rows.filter(r=>period==='all'||r.period===period).forEach(r=>{const key=(r.name||'Gost').toLocaleLowerCase('hr-HR');const x=map.get(key)||{name:r.name||'Gost',xp:0,points:0,quizzes:0,correct:0};x.xp+=r.xp;x.points+=r.points;x.quizzes+=r.quizzes;x.correct+=r.correct;map.set(key,x)});return [...map.values()].sort((a,b)=>(type==='xp'?b.xp-a.xp:b.points-a.points)).slice(0,100)}
 global.PatriaLeaderboard={read,save,submit,aggregate,remote:()=>Boolean(global.PatriaSupabase?.client)};
})(typeof window!=='undefined'?window:globalThis);
