document.addEventListener('DOMContentLoaded',()=>{
  document.documentElement.lang='hr';
  const btn=document.querySelector('[data-menu]'),side=document.querySelector('[data-side]'),overlay=document.querySelector('[data-overlay]');
  const close=()=>{side?.classList.remove('open');overlay?.classList.remove('open');document.body.classList.remove('menu-open')};
  if(btn&&side){btn.addEventListener('click',()=>{side.classList.add('open');overlay?.classList.add('open');document.body.classList.add('menu-open')});side.querySelectorAll('a').forEach(a=>a.addEventListener('click',close));overlay?.addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})}
  const path=location.pathname.split('/').pop()||'index.html';
  const style=document.createElement('style');
  style.textContent=`
    .quiz-menu,.history-menu,.faith-menu{position:relative;display:inline-flex;align-items:center}
    .quiz-menu>a:first-child,.history-menu>a:first-child,.faith-menu>a:first-child{display:inline-flex;align-items:center;gap:6px}
    .quiz-menu>a:first-child::after,.history-menu>a:first-child::after,.faith-menu>a:first-child::after{content:'▾';font-size:10px;opacity:.7}
    .quiz-submenu,.history-submenu,.faith-submenu{position:absolute;top:100%;left:50%;transform:translateX(-50%);min-width:250px;max-height:75vh;overflow:auto;padding:7px;background:#11161d;border:1px solid var(--line);border-radius:0 0 12px 12px;box-shadow:0 14px 30px rgba(0,0,0,.35);display:none;z-index:1000}
    .quiz-menu:hover .quiz-submenu,.quiz-menu:focus-within .quiz-submenu,.history-menu:hover .history-submenu,.history-menu:focus-within .history-submenu,.faith-menu:hover .faith-submenu,.faith-menu:focus-within .faith-submenu{display:grid}
    .quiz-submenu a,.history-submenu a,.faith-submenu a{display:block!important;padding:10px 12px!important;border-radius:8px;white-space:nowrap}
    .quiz-submenu a:hover,.history-submenu a:hover,.faith-submenu a:hover{background:rgba(212,174,56,.09);color:var(--gold2)}
    .city-nav{white-space:nowrap!important;padding:10px 14px!important;border:1px solid rgba(212,174,56,.5)!important;border-radius:10px;background:linear-gradient(135deg,rgba(212,174,56,.16),rgba(212,174,56,.06))!important;color:#e3c55b!important;font-weight:900!important}
    .side-quiz-links,.side-history-links,.side-faith-links{margin:4px 0 8px 15px;padding-left:12px;border-left:1px solid var(--line)}
    .side-quiz-links a,.side-history-links a,.side-faith-links a{font-size:13px!important;color:var(--muted)!important}
    .quiz-subpage-nav{width:min(1050px,92%);margin:25px auto -5px;display:flex;justify-content:center;gap:8px;flex-wrap:wrap}
    .quiz-subpage-nav a{padding:10px 16px;border:1px solid var(--line);border-radius:10px;color:var(--muted);text-decoration:none;background:#10161d}
    .quiz-subpage-nav a:hover,.quiz-subpage-nav a.active{color:var(--gold2);border-color:rgba(212,174,56,.5)}
    .timeline::before{content:'';display:block;width:min(900px,100%);height:250px;margin:0 auto 30px;border-radius:18px;background:linear-gradient(rgba(8,10,14,.18),rgba(8,10,14,.58)),url('https://raw.githubusercontent.com/Patriasoul/patriasoul/main/images/nedladdning%20(33).jpg?raw=true') center/cover no-repeat;border:1px solid rgba(212,174,56,.2);box-shadow:0 14px 35px rgba(0,0,0,.28)}
    @media(max-width:800px){.quiz-menu,.history-menu,.faith-menu{display:block}.quiz-menu:hover .quiz-submenu,.history-menu:hover .history-submenu,.faith-menu:hover .faith-submenu{display:none}.quiz-submenu,.history-submenu,.faith-submenu{position:static;transform:none;margin:5px 0 8px 15px;box-shadow:none;display:grid;border-radius:10px;max-height:none}.quiz-menu>a:first-child::after,.history-menu>a:first-child::after,.faith-menu>a:first-child::after{display:none}.timeline::before{height:180px}}
  `;
  document.head.appendChild(style);

  document.querySelectorAll('.main-nav').forEach(nav=>{
    const rank=nav.querySelector('a[href="leaderboard.html"]');
    const profile=nav.querySelector('a[href="profile.html"]');
    const calendar=nav.querySelector('a[href="kalendar.html"]');
    const oldFaith=nav.querySelector('a[href="vjera.html"]');
    const existingHistory=nav.querySelector('a[href="povijest.html"]');
    const quiz=nav.querySelector('a[href="quiz.html"]');
    const upoznaj=nav.querySelector('a[href="hrvatska.html"]');
    if(upoznaj&&/upoznaj\s+hrvatsku/i.test(upoznaj.textContent.trim()))upoznaj.remove();
    if(rank)rank.remove(); if(profile)profile.remove(); if(calendar)calendar.remove();
    if(quiz&&!quiz.parentElement.classList.contains('quiz-menu')){const menu=document.createElement('div');menu.className='quiz-menu';quiz.parentNode.insertBefore(menu,quiz);menu.appendChild(quiz);const sub=document.createElement('div');sub.className='quiz-submenu';sub.innerHTML='<a href="leaderboard.html">Rang-lista</a><a href="profile.html">Profil igrača</a>';menu.appendChild(sub)}
    if(oldFaith&&!oldFaith.parentElement.classList.contains('faith-menu')){const menu=document.createElement('div');menu.className='faith-menu';oldFaith.parentNode.insertBefore(menu,oldFaith);menu.appendChild(oldFaith);const sub=document.createElement('div');sub.className='faith-submenu';sub.innerHTML='<a href="vjera.html">Vjera – početna</a><a href="vjera-biblija.html">Biblija</a><a href="vjera-clanci.html">Članci o vjeri</a><a href="vjera-blazenici.html">Sveci i blaženici</a><a href="vjera-svetista.html">Crkve i svetišta</a>';menu.appendChild(sub)}
    if(!nav.querySelector('.faith-menu')){const anchor=document.createElement('a');anchor.href='vjera.html';anchor.textContent='Vjera';const menu=document.createElement('div');menu.className='faith-menu';menu.appendChild(anchor);const sub=document.createElement('div');sub.className='faith-submenu';sub.innerHTML='<a href="vjera.html">Vjera – početna</a><a href="vjera-biblija.html">Biblija</a><a href="vjera-clanci.html">Članci o vjeri</a><a href="vjera-blazenici.html">Sveci i blaženici</a><a href="vjera-svetista.html">Crkve i svetišta</a>';menu.appendChild(sub);const target=nav.querySelector('a[href="hrvatska.html"],a[href="encyclopedia.html"]');if(target)target.parentNode.insertBefore(menu,target);else nav.appendChild(menu)}
    if(existingHistory&&!existingHistory.parentElement.classList.contains('history-menu')){const menu=document.createElement('div');menu.className='history-menu';existingHistory.parentNode.insertBefore(menu,existingHistory);menu.appendChild(existingHistory);const sub=document.createElement('div');sub.className='history-submenu';sub.innerHTML='<a href="povijest.html">Povijest Hrvatske</a><a href="povijesna-razdoblja.html">Povijesna razdoblja</a><a href="hrvatski-vladari.html">Hrvatski vladari</a><a href="povijesne-osobe.html">Povijesne osobe</a><a href="povijesni-banovi.html">Hrvatski banovi</a><a href="hrvatski-sabor.html">Hrvatski sabor</a><a href="hrvatska-drzavnost.html">Hrvatska državnost</a><a href="domovinski-rat.html">Domovinski rat</a><a href="bitke-i-ratovi.html">Bitke i ratovi</a><a href="povijesne-obitelji.html">Povijesne obitelji</a><a href="gradovi-kroz-povijest.html">Gradovi kroz povijest</a><a href="tvrdave-i-dvorci.html">Tvrđave i dvorci</a><a href="kulturna-povijest.html">Kulturna povijest</a><a href="povijesni-dokumenti.html">Povijesni dokumenti</a><a href="kalendar.html">Povijesni kalendar</a><a href="povijesni-clanci.html">Povijesni članci</a>';menu.appendChild(sub)}
    if(!nav.querySelector('.history-menu')){const anchor=document.createElement('a');anchor.href='povijest.html';anchor.textContent='Povijest';const menu=document.createElement('div');menu.className='history-menu';menu.appendChild(anchor);const sub=document.createElement('div');sub.className='history-submenu';sub.innerHTML='<a href="povijest.html">Povijest Hrvatske</a><a href="povijesna-razdoblja.html">Povijesna razdoblja</a><a href="hrvatski-vladari.html">Hrvatski vladari</a><a href="povijesne-osobe.html">Povijesne osobe</a><a href="povijesni-banovi.html">Hrvatski banovi</a><a href="hrvatski-sabor.html">Hrvatski sabor</a><a href="hrvatska-drzavnost.html">Hrvatska državnost</a><a href="domovinski-rat.html">Domovinski rat</a><a href="bitke-i-ratovi.html">Bitke i ratovi</a><a href="povijesne-obitelji.html">Povijesne obitelji</a><a href="gradovi-kroz-povijest.html">Gradovi kroz povijest</a><a href="tvrdave-i-dvorci.html">Tvrđave i dvorci</a><a href="kulturna-povijest.html">Kulturna povijest</a><a href="povijesni-dokumenti.html">Povijesni dokumenti</a><a href="kalendar.html">Povijesni kalendar</a><a href="povijesni-clanci.html">Povijesni članci</a>';menu.appendChild(sub);const target=nav.querySelector('a[href="hrvatska.html"],a[href="encyclopedia.html"]');if(target)target.parentNode.insertBefore(menu,target);else nav.appendChild(menu)}
    if(!nav.querySelector('.city-nav')){const city=document.createElement('a');city.href='brani-svoj-grad.html';city.textContent='🛡️ Brani svoj grad';city.className='city-nav';const quizMenu=nav.querySelector('.quiz-menu');if(quizMenu)quizMenu.parentNode.insertBefore(city,quizMenu);else nav.appendChild(city)}
  });

  document.querySelectorAll('.side-links').forEach(list=>{
    const rank=list.querySelector('a[href="leaderboard.html"]'),profile=list.querySelector('a[href="profile.html"]'),quiz=list.querySelector('a[href="quiz.html"]');
    if(rank)rank.parentElement.remove();if(profile)profile.parentElement.remove();
    if(quiz&&!list.querySelector('.side-quiz-links')){const box=document.createElement('li');box.className='side-quiz-links';box.innerHTML='<a href="leaderboard.html">Rang-lista</a><a href="profile.html">Profil igrača</a>';quiz.parentElement.insertAdjacentElement('afterend',box)}
    if(!list.querySelector('.side-faith-links')){const quizLink=list.querySelector('a[href="quiz.html"]');const box=document.createElement('li');box.className='side-faith-links';box.innerHTML='<a href="vjera.html">Vjera</a><a href="vjera-biblija.html">Biblija</a><a href="vjera-clanci.html">Članci o vjeri</a><a href="vjera-blazenici.html">Sveci i blaženici</a><a href="vjera-svetista.html">Crkve i svetišta</a>';if(quizLink)quizLink.parentElement.insertAdjacentElement('afterend',box);else list.appendChild(box)}
  });

  if(path==='leaderboard.html'||path==='profile.html'){const nav=document.createElement('nav');nav.className='quiz-subpage-nav';nav.innerHTML='<a href="quiz.html">← Kviz</a><a href="leaderboard.html">Rang-lista</a><a href="profile.html">Profil igrača</a>';document.querySelector('header')?.insertAdjacentElement('afterend',nav)}
  document.querySelectorAll('.main-nav a,.side-links a').forEach(a=>{if(a.getAttribute('href')===path)a.classList.add('active')});
  const footer=document.querySelector('footer');
  if(footer)footer.innerHTML='<div class="footer-brand">PATRIA<span>SOUL</span></div><nav class="footer-links" aria-label="Podnožje"><a href="index.html">Početna</a><a href="quiz.html">Kviz</a><a href="brani-svoj-grad.html">🛡️ Brani svoj grad</a><a href="vjera.html">Vjera</a><a href="kalendar.html">Povijesni kalendar</a><a href="encyclopedia.html">Enciklopedija</a><a href="articles.html">Članci</a><a href="about.html">O PatriaSoulu</a><a href="contact.html">Kontakt</a><a href="privacy.html">Pravila privatnosti</a></nav><div class="footline">Hrvatska. Povijest. Znanje. Identitet. • © 2026 PatriaSoul</div>';
  document.querySelectorAll('.brand,.footer-brand').forEach(el=>{if(el.dataset.logoApplied)return;if(el.textContent.includes('PATRIA')&&el.textContent.includes('SOUL')){el.innerHTML='<img class="patria-logo" src="images/1000000982.png" alt="PatriaSoul">';el.dataset.logoApplied='1'}});
  document.querySelectorAll('.entry,.place,.uitem,.heritage').forEach(card=>{const h=card.querySelector('h3,strong');if(!h)return;const title=h.textContent.trim();card.setAttribute('role','link');card.setAttribute('tabindex','0');card.style.cursor='pointer';const open=()=>location.href='detail.html?title='+encodeURIComponent(title);card.addEventListener('click',e=>{if(!e.target.closest('a'))open()});card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})});
  if(document.querySelector('.music-card')){const s=document.createElement('script');s.src='js/music-details.js';document.body.appendChild(s)}
});
const PATRIA_STORAGE='patriasoul_player';
function defaultPlayer(){return{name:'PatriaSoul igrač',xp:0,points:0,quizzes:0,correct:0,streak:0,badges:[]}}
function normalize(p){p={...defaultPlayer(),...(p||{})};p.xp=Number(p.xp)||0;p.points=Number(p.points)||0;p.quizzes=Number(p.quizzes)||0;p.correct=Number(p.correct)||0;p.badges=Array.isArray(p.badges)?p.badges:[];[[500,'Poznavatelj Hrvatske'],[1000,'Hrvatski znalac'],[2500,'Čuvar baštine'],[5000,'PatriaSoul majstor']].forEach(([xp,b])=>{if(p.xp>=xp&&!p.badges.includes(b))p.badges.push(b)});return p}
function getPlayer(){try{return normalize(JSON.parse(localStorage.getItem(PATRIA_STORAGE)||localStorage.getItem('patriasoul_profile')||'null'))}catch{return defaultPlayer()}}
function savePlayer(p){p=normalize(p);localStorage.setItem(PATRIA_STORAGE,JSON.stringify(p));return p}
function addQuizResult(correct,total,bonus=0){const p=getPlayer(),gained=correct*100+Math.max(0,Number(bonus)||0);p.xp+=gained;p.points+=gained;p.quizzes++;p.correct+=correct;p.streak++;return savePlayer(p)}
function levelForXP(xp){if(xp>=5000)return{level:'PatriaSoul majstor',next:Infinity};if(xp>=2500)return{level:'Čuvar baštine',next:5000};if(xp>=1000)return{level:'Hrvatski znalac',next:2500};if(xp>=500)return{level:'Poznavatelj Hrvatske',next:1000};return{level:'Početnik',next:500}}
window.PatriaSoul={getPlayer,savePlayer,addQuizResult,levelForXP};