(function(){'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').toLocaleLowerCase('hr-HR');
const yt=id=>id?`https://www.youtube.com/watch?v=${encodeURIComponent(id)}`:'';
const thumb=id=>id?`https://i.ytimg.com/vi/${encodeURIComponent(id)}/hqdefault.jpg`:'';
function init(){const data=window.PATRIA_MEDIA||{};
 const filters=(id,items)=>{const el=document.getElementById(id);if(!el)return;const cats=['Sve',...[...new Set(items.map(x=>x.category).filter(Boolean))]];el.innerHTML=cats.map((c,i)=>`<button class="video-filter${i===0?' active':''}" type="button" data-filter="${esc(c)}">${esc(c)}</button>`).join('');return el};
 const v=document.getElementById('videos');
 if(v){const items=data.video||[],f=filters('video-filters',items),search=document.getElementById('video-search'),count=document.getElementById('video-count');let active='Sve';
 const render=()=>{const q=norm(search?.value);const out=items.filter(x=>(active==='Sve'||x.category===active)&&(!q||norm([x.title,x.description,x.category,...(x.tags||[])].join(' ')).includes(q)));if(count)count.textContent=`${out.length} sadržaja`;v.innerHTML=out.length?out.map((x,i)=>{const href=x.videoId?yt(x.videoId):x.url;const image=x.videoId?thumb(x.videoId):(x.image||'/images/domovinski-rat-hero.svg');return `<article class="video-card"><a class="video-thumb" href="${esc(href)}" target="_blank" rel="noopener noreferrer" aria-label="Otvori ${esc(x.title)}"><img src="${esc(image)}" alt="${esc(x.title)}" loading="lazy" onerror="this.onerror=null;this.src='/images/domovinski-rat-hero.svg'"><span class="video-play" aria-hidden="true">▶</span><span class="video-badge">${esc(x.category||'Video')}</span></a><div class="video-card-body"><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><div class="video-meta"><span class="video-tag">${esc((x.tags||[]).slice(0,3).join(' · '))}</span>${x.source?`<span>${esc(x.source)}</span>`:''}</div><div class="video-actions"><a class="video-btn primary" href="${esc(href)}" target="_blank" rel="noopener noreferrer">Pogledaj video ↗</a></div></div></article>`}).join(''):`<div class="video-empty"><strong>Nema pronađenih sadržaja</strong>Pokušaj s drugim pojmom ili kategorijom.</div>`};
 f?.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;active=b.dataset.filter;f.querySelectorAll('.video-filter').forEach(x=>x.classList.toggle('active',x===b));render()});search?.addEventListener('input',render);render();}
 const g=document.getElementById('gallery');
 if(g){const items=data.gallery||[],f=filters('gallery-filters',items),search=document.getElementById('gallery-search'),count=document.getElementById('gallery-count');let active='Sve';
 const render=()=>{const q=norm(search?.value);const out=items.filter(x=>(active==='Sve'||x.category===active)&&(!q||norm([x.title,x.caption,x.category,x.source].join(' ')).includes(q)));if(count)count.textContent=`${out.length} vizuala`;g.innerHTML=out.length?out.map(x=>`<figure class="gallery-item"><button class="gallery-image" type="button" data-lightbox="${esc(x.image)}" data-title="${esc(x.title)}"><img src="${esc(x.image)}" alt="${esc(x.title)}" loading="lazy" onerror="this.onerror=null;this.src='/images/vjera-duhovna-bastina.svg'"><span class="gallery-overlay"><span class="gallery-view">⌕ Uvećaj</span></span></button><figcaption class="gallery-caption"><h3>${esc(x.title)}</h3><p>${esc(x.caption)}</p><div class="gallery-meta"><strong>${esc(x.category||'PatriaSoul')}</strong>${x.source?`<span>Foto: ${esc(x.source)}</span>`:''}</div>${x.creditUrl?`<a class="gallery-credit" href="${esc(x.creditUrl)}" target="_blank" rel="noopener noreferrer">Izvor / licenca ↗</a>`:''}</figcaption></figure>`).join(''):`<div class="gallery-empty">Nema vizuala za odabrani filtar.</div>`};
 f?.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;active=b.dataset.filter;f.querySelectorAll('.video-filter').forEach(x=>x.classList.toggle('active',x===b));render()});search?.addEventListener('input',render);render();
 g.addEventListener('click',e=>{const b=e.target.closest('[data-lightbox]');if(!b)return;const lb=document.getElementById('ps-media-lightbox');lb.querySelector('img').src=b.dataset.lightbox;lb.querySelector('img').alt=b.dataset.title;lb.querySelector('[data-lightbox-title]').textContent=b.dataset.title;lb.classList.add('is-open');lb.setAttribute('aria-hidden','false')});}
 if(!document.getElementById('ps-media-lightbox')){const lb=document.createElement('div');lb.id='ps-media-lightbox';lb.className='ps-gallery-lightbox';lb.setAttribute('aria-hidden','true');lb.innerHTML='<button class="gallery-lightbox-close" type="button" aria-label="Zatvori" data-close>×</button><figure style="margin:0;text-align:center"><img src="" alt=""><figcaption style="margin-top:12px;color:#fff;font-weight:800" data-lightbox-title></figcaption></figure>';document.body.appendChild(lb);lb.addEventListener('click',e=>{if(e.target===lb||e.target.closest('[data-close]')){lb.classList.remove('is-open');lb.setAttribute('aria-hidden','true')}});document.addEventListener('keydown',e=>{if(e.key==='Escape')lb.classList.remove('is-open')})}
 const b=document.querySelector('[data-ps-menu]'),n=document.querySelector('.ps-mainnav');if(b&&n&&!b.dataset.mediaBound){b.dataset.mediaBound='1';b.addEventListener('click',()=>n.classList.toggle('is-open'))}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();
