// PatriaSoul — centralni katalog medija.
// Video i galerija koriste isti izvor podataka.
window.PATRIA_MEDIA={
 video:[
  {title:'O hrvatskome jeziku s Anom Ćavar',description:'Razgovor o počecima uporabe hrvatskoga jezika u školama i razvoju njegova poučavanja.',tags:['jezik','kultura','Matica hrvatska'],category:'Baština',videoId:'EyVb3O3_A1w',source:'Matica hrvatska'},
  {title:'Hrvatska ćirilična baština',description:'Predavanje o hrvatskoj ćiriličnoj baštini, spomenicima i razvoju pisane kulture.',tags:['pismo','baština','povijest'],category:'Povijest',videoId:'l4gRplFd1Vs',source:'Matica hrvatska'},
  {title:'Priča iz sudskih spisa Dubrovačke Republike',description:'Autentični dubrovački govor i svakodnevni život zabilježeni u povijesnim sudskim spisima.',tags:['Dubrovnik','govori','Dubrovačka Republika'],category:'Baština',videoId:'PywB5yQmkMU',source:'Matica hrvatska'},
  {title:'Dubrovački govor iz povijesnih zapisa',description:'Drugi video-prilog o autentičnom hrvatskom govoru Dubrovnika kroz povijesne izvore.',tags:['Dubrovnik','jezik','baština'],category:'Baština',videoId:'lStrsZ5BA5s',source:'Matica hrvatska'},
  {title:'Bitka za Vukovar — arhivske snimke',description:'Dokumentarni pregled bitke za Vukovar i ratnih događaja 1991. s arhivskim snimkama.',tags:['Vukovar','1991','Domovinski rat'],category:'Sjećanje',videoId:'HXo9Al2dUSU',source:'Frontline by ITN'},
  {title:'Hrvatska i baština',description:'Video vodiči kroz hrvatsku povijest, kulturu, gradove, običaje i identitet.',tags:['Hrvatska','baština','povijest'],category:'Baština',url:'https://www.youtube.com/results?search_query=hrvatska+ba%C5%A1tina+povijest'},
  {title:'Sinjska alka',description:'Materijali o Sinjskoj alci, tradiciji, viteškom natjecanju i kulturnoj baštini Sinja.',tags:['Sinj','Sinjska alka','tradicija'],category:'Baština',url:'https://www.youtube.com/results?search_query=Sinjska+alka+sluzbeno'},
  {title:'Domovinski rat',description:'Kronologija, operacije, postrojbe i svjedočanstva povezani s Domovinskim ratom.',tags:['1991–1995','branitelji','operacije'],category:'Povijest',url:'https://www.youtube.com/results?search_query=Domovinski+rat+Hrvatska+sluzbeno'},
  {title:'Hrvatska vjera i duhovna baština',description:'Video sadržaji o hrvatskim crkvama, hodočašćima, vjeri i duhovnoj tradiciji.',tags:['vjera','crkva','duhovnost'],category:'Vjera',url:'https://www.youtube.com/results?search_query=Hrvatska+katoli%C4%8Dka+vjera'},
  {title:'Hrvatska gastronomija',description:'Tradicionalna jela, regionalni okusi, obiteljski recepti i priče o hrani.',tags:['gastronomija','recepti','tradicija'],category:'Gastronomija',url:'https://www.youtube.com/results?search_query=hrvatska+tradicionalna+kuhinja'},
  {title:'Hrvatski govori i dijalekti',description:'Primjeri govora, narječja i jezične baštine hrvatskih krajeva.',tags:['dijalekti','govori','jezik'],category:'Baština',url:'https://www.youtube.com/results?search_query=hrvatski+dijalekti+govori'}
 ],
 gallery:[
  {title:'Dubrovnik — kameni grad uz more',caption:'Pogled na Dubrovnik i dubrovačku obalu.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/A_distant_view_of_Divovici_Beach_and_the_Old_Town_of_Dubrovnik,_Croatia_(48739125537).jpg',category:'Dalmacija',source:'Wikimedia Commons',creditUrl:'https://commons.wikimedia.org/wiki/Category:Dubrovnik-Neretva_County'},
  {title:'Klis — tvrđava iznad Dalmacije',caption:'Klis i krajolik Splitsko-dalmatinske županije.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Klis_VPZ_2018..jpg',category:'Dalmacija',source:'Wikimedia Commons',creditUrl:'https://commons.wikimedia.org/wiki/Category:Split-Dalmatia_County'},
  {title:'Istra — batana i pomorska baština',caption:'Istarska batana kao dio pomorske i tradicijske kulture.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Batana_istrska.jpg',category:'Istra',source:'Wikimedia Commons',creditUrl:'https://commons.wikimedia.org/wiki/Category:Istria_County'},
  {title:'Zagreb — glavni grad Hrvatske',caption:'Gradski pejzaž Zagreba i njegova povijesna jezgra.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Zagreb_(29255640143).jpg',category:'Zagreb',source:'Wikimedia Commons',creditUrl:'https://commons.wikimedia.org/wiki/Category:Views_of_Zagreb'},
  {title:'Medvedgrad — pogled na Zagreb',caption:'Srednjovjekovna utvrda Medvedgrad iznad Zagreba.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Medvedgrad_2022-05-12.jpg',category:'Zagreb',source:'Wikimedia Commons',creditUrl:'https://commons.wikimedia.org/wiki/Category:Views_of_Zagreb'},
  {title:'Slavonija — široka ravnica',caption:'Pejzaž Slavonije, prostora polja, rijeka i tradicije.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Slavonija3_8292855.jpg',category:'Slavonija',source:'Wikimedia Commons',creditUrl:'https://commons.wikimedia.org/wiki/Category:Slavonia'},
  {title:'Sava u Slavoniji',caption:'Smiraj dana na rijeci Savi.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Smiraj_dana_na_rijeci_Savi.jpg',category:'Slavonija',source:'Wikimedia Commons',creditUrl:'https://commons.wikimedia.org/wiki/Category:Slavonia'},
  {title:'Šokačka tradicija',caption:'Narodna nošnja i živa tradicija Slavonije.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Traditional_Slavonian_National_Costume.jpg',category:'Tradicija',source:'Wikimedia Commons',creditUrl:'https://commons.wikimedia.org/wiki/Category:Slavonia'},
  {title:'Lika — krajolik i planinski prostor',caption:'Ličko-senjski krajolik, planine i široki prostori Like.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/02.10.2011._-_panoramio.jpg',category:'Lika',source:'Wikimedia Commons',creditUrl:'https://commons.wikimedia.org/wiki/Category:Views_of_Lika-Senj_County'},
  {title:'Vukovar — grad na Dunavu',caption:'Vukovar i Dunav, grad snažnog povijesnog i memorijalnog značenja.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Panorama_of_Vukovara.jpg',category:'Sjećanje',source:'Wikimedia Commons',creditUrl:'https://commons.wikimedia.org/wiki/Category:Vukovar'},
  {title:'Vukovar — memorijalno groblje',caption:'Mjesto tišine, molitve i trajnog sjećanja.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Memorijalno_groblje_Vukovar.jpg',category:'Sjećanje',source:'Wikimedia Commons',creditUrl:'https://commons.wikimedia.org/wiki/Category:Vukovar_Memorial_Cemetery'},
  {title:'Vukovarski vodotoranj',caption:'Simbol otpora, obnove i sjećanja na Vukovar.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Hrvatski_grad_Vukovar.jpg',category:'Sjećanje',source:'Wikimedia Commons',creditUrl:'https://commons.wikimedia.org/wiki/Category:Vukovar_Water_Tower'},
  {title:'Opatija — kvarnerska baština',caption:'Povijesna Opatija i tragovi njezine turističke i pomorske baštine.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Croatia_BW_2014-10-07_14-21-23.jpg',category:'Kvarner',source:'Wikimedia Commons',creditUrl:'https://commons.wikimedia.org/wiki/Category:Hotel_Kvarner,_Opatija'},
  {title:'Čuvari domovine',caption:'Vizualna priča o braniteljima, sjećanju i dostojanstvu.',image:'/images/branitelji-hero.svg',category:'Sjećanje',source:'PatriaSoul',creditUrl:''},
  {title:'Domovinski rat',caption:'Kronologija, obrana, oslobađanje i sjećanje.',image:'/images/domovinski-rat-hero.svg',category:'Povijest',source:'PatriaSoul',creditUrl:''},
  {title:'Vjera i duhovna baština',caption:'Križ, svjetlost i prostor hrvatske duhovne baštine.',image:'/images/vjera-duhovna-bastina.svg',category:'Vjera',source:'PatriaSoul',creditUrl:''}
 ]
};
