// PatriaSoul — središnji registar hrvatskih vojno-redarstvenih i važnijih oslobodilačkih operacija
// Jedini izvor podataka za operacije; stranice ga mogu koristiti bez kopiranja.

export const operacije = [
  {
    id: "miljevci",
    naziv: "Operacija Miljevci",
    kodniNaziv: "Miljevci",
    tip: "vojno-redarstvena operacija",
    startDate: "1992-06-21",
    endDate: "1992-06-22",
    godina: 1992,
    podrucje: "Miljevački plato, Šibensko-kninska županija",
    cilj: "Oslobađanje Miljevačkog platoa i pomicanje crte obrane od Šibenika.",
    znacaj: "Jedna od prvih većih oslobodilačkih akcija hrvatskih snaga tijekom Domovinskog rata.",
    kategorija: "Domovinski rat",
    status: "uspješna",
    tags: ["Miljevci", "Šibenik", "HV", "MUP"]
  },
  {
    id: "maslenica",
    naziv: "Vojno-redarstvena operacija Maslenica",
    kodniNaziv: "Gusar",
    tip: "vojno-redarstvena operacija",
    startDate: "1993-01-22",
    endDate: "1993-01-27",
    godina: 1993,
    podrucje: "Zadarsko zaleđe",
    cilj: "Oslobađanje strateških područja u zadarskom zaleđu i ponovno povezivanje sjevera i juga Hrvatske.",
    znacaj: "Jedna od prvih velikih oslobodilačkih operacija Hrvatske vojske i MUP-a; u prva tri dana oslobođeno je gotovo 100 km² okupiranog teritorija.",
    kategorija: "Domovinski rat",
    status: "uspješna",
    tags: ["Maslenica", "Gusar", "Zadar", "HV", "MUP"]
  },
  {
    id: "medak-dzep",
    naziv: "Operacija Medački džep",
    kodniNaziv: "Medački džep",
    tip: "vojno-redarstvena operacija",
    startDate: "1993-09-09",
    endDate: "1993-09-17",
    godina: 1993,
    podrucje: "Područje Gospića i Medačkog džepa",
    cilj: "Oslobađanje područja južno od Gospića i potiskivanje neprijateljskih snaga od grada.",
    znacaj: "Važna operacija u obrani Gospića i pomicanju crte bojišta na ličkom području.",
    kategorija: "Domovinski rat",
    status: "uspješna",
    tags: ["Medački džep", "Gospić", "Lika", "HV", "MUP"]
  },
  {
    id: "zima-94",
    naziv: "Operacija Zima '94",
    kodniNaziv: "Zima '94",
    tip: "operacija",
    startDate: "1994-11-29",
    endDate: "1994-12-24",
    godina: 1994,
    podrucje: "Livno i Livanjsko polje, BiH",
    cilj: "Oslobađanje prostora Livanjskog polja i stvaranje povoljnijih strateških uvjeta za daljnja djelovanja.",
    znacaj: "Združena operacija hrvatskih snaga i Hrvatskog vijeća obrane koja je stvorila važnu pretpostavku za kasnije operacije, uključujući Oluju.",
    kategorija: "Domovinski rat",
    status: "uspješna",
    tags: ["Zima '94", "Livno", "Dinara", "HV", "HVO"]
  },
  {
    id: "skok-1",
    naziv: "Operacija Skok-1",
    kodniNaziv: "Skok-1",
    tip: "operacija",
    startDate: "1995-04-07",
    endDate: "1995-04-11",
    godina: 1995,
    podrucje: "Dinara i područje Livanjskog polja, BiH",
    cilj: "Poboljšanje položaja hrvatskih snaga na Dinari i stvaranje povoljnijih uvjeta za daljnja djelovanja.",
    znacaj: "Dio niza operacija kojima su hrvatske snage tijekom 1995. stvarale strateške uvjete za završne operacije.",
    kategorija: "Domovinski rat",
    status: "uspješna",
    tags: ["Skok-1", "Dinara", "Livno", "HV", "HVO"]
  },
  {
    id: "bljesak",
    naziv: "Vojno-redarstvena operacija Bljesak",
    kodniNaziv: "Bljesak",
    tip: "vojno-redarstvena operacija",
    startDate: "1995-05-01",
    endDate: "1995-05-04",
    godina: 1995,
    podrucje: "Zapadna Slavonija",
    cilj: "Oslobađanje okupiranog područja zapadne Slavonije i uspostava nadzora nad važnim prometnim pravcima.",
    znacaj: "U operaciji je u oko 32 sata oslobođeno približno 500 km², uključujući Okučane, Pakrac i Jasenovac.",
    kategorija: "Domovinski rat",
    status: "uspješna",
    tags: ["Bljesak", "Okučani", "Pakrac", "Jasenovac", "zapadna Slavonija", "HV", "MUP"]
  },
  {
    id: "skok-2",
    naziv: "Operacija Skok-2",
    kodniNaziv: "Skok-2",
    tip: "operacija",
    startDate: "1995-06-04",
    endDate: "1995-06-11",
    godina: 1995,
    podrucje: "Dinara i Livanjsko polje, BiH",
    cilj: "Daljnje pomicanje hrvatskih snaga prema strateškim položajima na Dinari i stvaranje uvjeta za završne operacije.",
    znacaj: "Nastavak djelovanja na Dinari uoči operacije Ljeto '95.",
    kategorija: "Domovinski rat",
    status: "uspješna",
    tags: ["Skok-2", "Dinara", "HV", "HVO"]
  },
  {
    id: "ljeto-95",
    naziv: "Operacija Ljeto '95",
    kodniNaziv: "Ljeto '95",
    tip: "operacija",
    startDate: "1995-07-25",
    endDate: "1995-07-30",
    godina: 1995,
    podrucje: "Bosansko Grahovo i Glamoč, BiH",
    cilj: "Oslobađanje područja Bosanskog Grahova i Glamoča te stvaranje povoljnog strateškog položaja za oslobađanje Knina.",
    znacaj: "Operacija je bitno promijenila strateški položaj na području Dinare i približila hrvatske snage završnim operacijama.",
    kategorija: "Domovinski rat",
    status: "uspješna",
    tags: ["Ljeto '95", "Grahovo", "Glamoč", "Dinara", "HV", "HVO"]
  },
  {
    id: "oluja",
    naziv: "Vojno-redarstvena operacija Oluja",
    kodniNaziv: "Oluja",
    tip: "vojno-redarstvena operacija",
    startDate: "1995-08-04",
    endDate: "1995-08-07",
    godina: 1995,
    podrucje: "Veći dio okupiranog područja Republike Hrvatske",
    cilj: "Vraćanje okupiranih područja u hrvatski ustavno-pravni poredak.",
    znacaj: "U operaciji je oslobođeno 10.400 km², odnosno 18,4 % ukupne površine Hrvatske; Knin je oslobođen 5. kolovoza 1995.",
    kategorija: "Domovinski rat",
    status: "uspješna",
    tags: ["Oluja", "Knin", "Lika", "Kordun", "Banovina", "Dalmacija", "HV", "MUP"]
  },
  {
    id: "maestral",
    naziv: "Operacija Maestral",
    kodniNaziv: "Maestral",
    tip: "operacija",
    startDate: "1995-09-08",
    endDate: "1995-09-15",
    godina: 1995,
    podrucje: "Zapadna i središnja Bosna i Hercegovina",
    cilj: "Potiskivanje snaga Vojske Republike Srpske i stvaranje uvjeta za završetak rata u BiH.",
    znacaj: "Združeno djelovanje Hrvatske vojske i Hrvatskog vijeća obrane u završnoj fazi rata u BiH.",
    kategorija: "Domovinski rat / BiH",
    status: "uspješna",
    tags: ["Maestral", "BiH", "HV", "HVO"]
  }
];

export default operacije;
