/* PatriaSoul — unified brand hero layer */
(function(){
'use strict';
var heroImage='/images/flag-of-croatia-free-vector.jpg?v=a939374e';
var labels={'/domovina.html':'Hrvatska i domovina','/domovina':'Hrvatska i domovina','/gradovi.html':'Gradovi Hrvatske','/gradovi':'Gradovi Hrvatske','/branitelji.html':'Branitelji i sjećanje','/branitelji':'Branitelji i sjećanje','/domovinski-rat.html':'Domovinski rat','/domovinski-rat':'Domovinski rat','/postrojbe.html':'Postrojbe','/postrojbe':'Postrojbe','/brigade.html':'Brigade','/brigade':'Brigade','/operacije.html':'Operacije i bojišta','/operacije':'Operacije i bojišta','/vukovar.html':'Vukovar — grad koji pamti','/vukovar':'Vukovar — grad koji pamti','/spomenici.html':'Spomenici i memorijali','/spomenici':'Spomenici i memorijali','/povijest.html':'Hrvatska povijest','/povijest':'Hrvatska povijest','/bastina.html':'Kulturna i povijesna baština','/bastina':'Kulturna i povijesna baština','/gastronomija.html':'Hrvatska gastronomija','/gastronomija':'Hrvatska gastronomija','/govori-i-dijalekti.html':'Govori i dijalekti','/govori-i-dijalekti':'Govori i dijalekti','/vjera.html':'Vjera i duhovna baština','/vjera':'Vjera i duhovna baština','/evandelje.html':'Evanđelje','/evandelje':'Evanđelje','/molitve.html':'Molitve','/molitve':'Molitve','/krunica.html':'Krunica','/krunica':'Krunica','/blagdani.html':'Crkveni blagdani','/blagdani':'Crkveni blagdani','/biblija.html':'Biblija','/biblija':'Biblija','/svetac-dana.html':'Svetac dana','/svetac-dana':'Svetac dana','/video.html':'Video arhiva','/video':'Video arhiva','/galerija.html':'Galerija','/galerija':'Galerija','/vijesti.html':'Vijesti','/vijesti':'Vijesti','/brani-svoj-grad.html':'Brani svoj grad','/brani-svoj-grad':'Brani svoj grad','/quiz.html':'PatriaSoul kviz','/quiz':'PatriaSoul kviz','/duel.html':'Duel','/duel':'Duel','/rang-lista.html':'Rang-lista','/rang-lista':'Rang-lista','/profil.html':'Moj profil','/profil':'Moj profil','/o-nama.html':'O projektu PatriaSoul','/o-nama':'O projektu PatriaSoul','/o-patriasoul.html':'PatriaSoul','/o-patriasoul':'PatriaSoul','/kontakt.html':'Kontakt','/kontakt':'Kontakt'};
function current(){return location.pathname.replace(/\/+$/,'')||'/';}
function style(){if(document.getElementById('ps-page-hero-style'))return;var s=document.createElement('style');s.id='ps-page-hero-style';s.textContent='.ps-page-hero{min-height:330px;display:flex;align-items:center;position:relative;overflow:hidden;background-image:linear-gradient(90deg,rgba(4,7,11,.94),rgba(4,7,11,.58),rgba(4,7,11,.86)),url("'+heroImage+'");background-position:center!important;background-size:cover!important;background-repeat:no-repeat!important}.ps-page-hero .container{position:relative;z-index:2}.ps-page-hero .ps-kicker{display:inline-block;color:#f3da84!important;font-weight:900;letter-spacing:.12em;text-transform:uppercase;font-size:.72rem;margin-bottom:14px}.ps-page-hero:before{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(4,7,11,.18),rgba(4,7,11,.12),rgba(4,7,11,.28));z-index:1}.ps-page-hero h1{position:relative}.ps-page-hero p{position:relative}.ps-page-hero .home-actions{position:relative}@media(max-width:560px){.ps-page-hero{min-height:290px}}';document.head.appendChild(s);}
function setBrandHero(hero){hero.style.backgroundImage='linear-gradient(90deg,rgba(4,7,11,.94),rgba(4,7,11,.58),rgba(4,7,11,.86)),url("'+heroImage+'")';hero.classList.add('ps-contextual-hero');var kicker=hero.querySelector('.ps-kicker');if(kicker)kicker.textContent=labels[current()]||kicker.textContent.replace(/•/g,'·');}
function ensureHero(){if(current()==='/'||current()==='/index.html')return;var main=document.querySelector('main');if(!main)return;var hero=main.querySelector(':scope > .ps-page-hero');var h1=main.querySelector('h1');if(!hero&&!h1)return;style();if(hero){setBrandHero(hero);return;}var path=current();var text=h1.textContent.trim();var p=h1.parentElement&&h1.parentElement.querySelector('p');hero=document.createElement('section');hero.className='ps-page-hero ps-contextual-hero';hero.style.backgroundImage='linear-gradient(90deg,rgba(4,7,11,.94),rgba(4,7,11,.58),rgba(4,7,11,.86)),url("'+heroImage+'")';var c=document.createElement('div');c.className='container';var k=document.createElement('span');k.className='ps-kicker';k.textContent=labels[path]||'PatriaSoul';var title=document.createElement('h1');title.textContent=text;var desc=document.createElement('p');desc.textContent=p?p.textContent.trim():'Istraži sadržaj PatriaSoul portala.';c.append(k,title,desc);hero.appendChild(c);main.insertBefore(hero,main.firstChild);h1.style.display='none';if(p&&p!==desc)p.style.display='none';}
function init(){ensureHero();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();