/* PatriaSoul — contextual page hero layer */
(function(){
'use strict';
var fallback='/images/1765535164250.png';
var flag=fallback;
var labels={
'/domovina.html':'Hrvatska i domovina','/gradovi.html':'Gradovi Hrvatske','/branitelji.html':'Branitelji i sjećanje','/domovinski-rat.html':'Domovinski rat','/postrojbe.html':'Postrojbe','/brigade.html':'Brigade','/operacije.html':'Operacije i bojišta','/vukovar.html':'Vukovar — grad koji pamti','/spomenici.html':'Spomenici i memorijali','/povijest.html':'Hrvatska povijest','/bastina.html':'Kulturna i povijesna baština','/gastronomija.html':'Hrvatska gastronomija','/govori-i-dijalekti.html':'Govori i dijalekti','/vjera.html':'Vjera i duhovna baština','/evandelje.html':'Evanđelje','/molitve.html':'Molitve','/krunica.html':'Krunica','/blagdani.html':'Crkveni blagdani','/biblija.html':'Biblija','/svetac-dana.html':'Svetac dana','/video.html':'Video arhiva','/galerija.html':'Galerija','/vijesti.html':'Vijesti','/brani-svoj-grad.html':'Brani svoj grad','/quiz.html':'PatriaSoul kviz','/duel.html':'Duel','/rang-lista.html':'Rang-lista','/profil.html':'Moj profil','/o-nama.html':'O projektu PatriaSoul','/o-patriasoul.html':'PatriaSoul','/kontakt.html':'Kontakt'};
function current(){return location.pathname.replace(/\/+$/,'')||'/';}
function style(){if(document.getElementById('ps-page-hero-style'))return;var s=document.createElement('style');s.id='ps-page-hero-style';s.textContent='.ps-page-hero{min-height:330px;display:flex;align-items:center;position:relative;overflow:hidden;background-position:center!important;background-size:cover!important;background-repeat:no-repeat!important}.ps-page-hero .container{position:relative;z-index:2}.ps-page-hero .ps-kicker{display:inline-block;color:#f3da84!important;font-weight:900;letter-spacing:.12em;text-transform:uppercase;font-size:.72rem;margin-bottom:14px}.ps-page-hero:before{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(4,7,11,.90) 0%,rgba(4,7,11,.70) 42%,rgba(4,7,11,.34) 72%,rgba(4,7,11,.56) 100%);z-index:1}.ps-page-hero:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,rgba(0,0,0,.16),transparent 38%,rgba(0,0,0,.30));z-index:1;pointer-events:none}.ps-page-hero .page-hero-credit{display:block;margin-top:14px;color:rgba(255,255,255,.58);font-size:.7rem}.ps-page-hero h1{position:relative;text-shadow:0 2px 18px rgba(0,0,0,.75)}.ps-page-hero p{position:relative;text-shadow:0 2px 12px rgba(0,0,0,.75)}.ps-page-hero .home-actions{position:relative}@media(max-width:560px){.ps-page-hero{min-height:290px;align-items:flex-end}.ps-page-hero:before{background:linear-gradient(90deg,rgba(4,7,11,.84),rgba(4,7,11,.58)),linear-gradient(0deg,rgba(4,7,11,.72),transparent 70%)}.ps-page-hero .container{padding-bottom:34px}.ps-page-hero h1{font-size:clamp(1.8rem,8vw,2.5rem)}}';document.head.appendChild(s);}
function ensureHero(){if(current()==='/'||current()==='/index.html')return;var main=document.querySelector('main');if(!main)return;var hero=main.querySelector(':scope > .ps-page-hero');var h1=main.querySelector('h1');if(!hero&&!h1)return;style();var path=current();if(hero){hero.style.backgroundImage='url("'+flag+'")';hero.classList.add('ps-contextual-hero');var kicker=hero.querySelector('.ps-kicker');if(kicker)kicker.textContent=labels[path]||kicker.textContent.replace(/•/g,'·');return;}
var text=h1.textContent.trim();var p=h1.parentElement&&h1.parentElement.querySelector('p');hero=document.createElement('section');hero.className='ps-page-hero ps-contextual-hero';hero.style.backgroundImage='url("'+flag+'")';var c=document.createElement('div');c.className='container';var k=document.createElement('span');k.className='ps-kicker';k.textContent=labels[path]||'PatriaSoul';var title=document.createElement('h1');title.textContent=text;var desc=document.createElement('p');desc.textContent=p?p.textContent.trim():'Istraži sadržaj PatriaSoul portala.';c.append(k,title,desc);hero.appendChild(c);main.insertBefore(hero,main.firstChild);h1.style.display='none';if(p&&p!==desc)p.style.display='none';}
function init(){ensureHero();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
