// PatriaSoul – dodatni registar pitanja iz hrvatske povijesti
// Odvojena banka za proširenje glavnog povijesnog kviza.
// Centralni quiz engine preslaguje odgovore; točan odgovor nije vezan uz A/B/C/D.
(function(){
  window.PATRIA_EXTRA_QUESTIONS = window.PATRIA_EXTRA_QUESTIONS || {};
  const q = [
    ['Koje je poznato neandertalsko nalazište u Hrvatskoj?','Hušnjakovo kod Krapine','Vučedol kod Vukovara','Salona','Narona'],
    ['Koja je kultura poznata po nalazištu Vučedol kod Vukovara?','Vučedolska kultura','Starčevačka kultura','Hallstattska kultura','La Tène kultura'],
    ['Koji je antički grad bio središte rimske provincije Dalmacije?','Salona','Siscia','Mursa','Andautonija'],
    ['Koji je rimski grad bio na području današnje Pule?','Pola','Iader','Mursa','Salona'],
    ['Kako se rimski nazivao Zadar?','Iader','Salona','Narona','Tarsatica'],
    ['Kako se rimski nazivao Osijek?','Mursa','Siscia','Iader','Salona'],
    ['Kako se rimski nazivao Sisak?','Siscia','Mursa','Tarsatica','Narona'],
    ['Koji je antički grčki grad osnovan na Visu?','Issa','Pharos','Salona','Iader'],
    ['Koji je antički grad bio grčka kolonija na Hvaru?','Pharos','Issa','Mursa','Narona'],
    ['Koji je bizantski car povezan s djelom De administrando imperio?','Konstantin VII. Porfirogenet','Heraklije','Justinijan I.','Teodozije I.'],
    ['Koji se hrvatski knez spominje u ispravi iz 852.?','Trpimir','Borna','Mislav','Branimir'],
    ['Koji je knez podigao ustanak protiv Franaka 818.?','Ljudevit Posavski','Borna','Mislav','Domagoj'],
    ['Koji je knez ojačao hrvatsku pomorsku moć sredinom 9. stoljeća?','Mislav','Trpimir','Branimir','Zvonimir'],
    ['Koji je papa povezan s pismom knezu Branimiru iz 879.?','Ivan VIII.','Lav III.','Grgur VII.','Aleksandar II.'],
    ['Koji je hrvatski kralj poznat po darovnici iz 1069.?','Petar Krešimir IV.','Tomislav','Dmitar Zvonimir','Stjepan Držislav'],
    ['Koji je kralj povezan s krunidbom 1076. prema tradicionalnoj historiografiji?','Dmitar Zvonimir','Petar Krešimir IV.','Tomislav','Mihajlo Krešimir II.'],
    ['Koji je kralj poginuo u bitci na Gvozdu 1097.?','Petar Svačić','Dmitar Zvonimir','Petar Krešimir IV.','Stjepan Držislav'],
    ['Koja je ploča jedan od najpoznatijih spomenika hrvatske glagoljice?','Bašćanska ploča','Humačka ploča','Višeslavova krstionica','Istarski razvod'],
    ['Na kojem se otoku nalazi Bašćanska ploča?','Krku','Hvaru','Braču','Visu'],
    ['Koje je pismo posebno povezano s hrvatskom srednjovjekovnom kulturnom baštinom?','Glagoljica','Runica','Kirilica','Gotica'],
    ['Koji je dokument iz 1288. važan za pravnu povijest Hrvatske?','Vinodolski zakonik','Pacta conventa','Zlatna bula','Cetinski izbor'],
    ['Koji je grad dobio Zlatnu bulu Bele IV. 1242.?','Gradec','Dubrovnik','Split','Šibenik'],
    ['Koji je mir iz 1358. imao veliko značenje za odnose Venecije i hrvatsko-ugarskog kralja?','Zadarski mir','Karlovački mir','Požarevački mir','Srijemski mir'],
    ['Koja je srednjovjekovna republika razvila snažnu samoupravu na južnom Jadranu?','Dubrovačka Republika','Poljička Republika','Mletačka Republika','Kneževina Krk'],
    ['Koja je plemićka obitelj bila posebno snažna u Krku i Vinodolu?','Frankapani','Šubići','Zrinski','Draškovići'],
    ['Koji je ban iz obitelji Šubić nosio naslov gospodara Bosne?','Pavao I. Šubić','Nikola Šubić Zrinski','Petar Berislavić','Ivan Karlović'],
    ['Koja je bitka 1493. bila težak poraz hrvatskog plemstva od Osmanlija?','Krbavska bitka','Bitka kod Siska','Sigetska bitka','Mohačka bitka'],
    ['Koja je bitka 1593. bila velika pobjeda nad Osmanlijama?','Bitka kod Siska','Krbavska bitka','Sigetska bitka','Mohačka bitka'],
    ['Tko je branio Siget 1566.?','Nikola Šubić Zrinski','Petar Berislavić','Ivan Karlović','Nikola Jurišić'],
    ['Koji je ban poginuo u borbi protiv Osmanlija 1520.?','Petar Berislavić','Nikola Jurišić','Nikola Šubić Zrinski','Juraj Drašković'],
    ['Koji je grad bio važno središte Vojne krajine?','Karlovac','Dubrovnik','Pula','Trogir'],
    ['Koji je mir 1699. bitno promijenio hrvatske granice nakon rata s Osmanlijama?','Mir u Srijemskim Karlovcima','Zadarski mir','Požarevački mir','Bečki mir'],
    ['Koji je plemić pogubljen 1671. u Bečkom Novom Mjestu?','Petar Zrinski','Nikola Šubić Zrinski','Petar Berislavić','Ivan Karlović'],
    ['Tko je pogubljen 1671. zajedno s Petrom Zrinskim?','Fran Krsto Frankopan','Marko Marulić','Ivan Gundulić','Petar Hektorović'],
    ['Tko je napisao Juditu?','Marko Marulić','Marin Držić','Petar Hektorović','Ivan Gundulić'],
    ['Tko je napisao Dunda Maroja?','Marin Držić','Ivan Gundulić','Marko Marulić','Petar Zoranić'],
    ['Tko je napisao Ribanje i ribarsko prigovaranje?','Petar Hektorović','Marko Marulić','Marin Držić','Ivan Gundulić'],
    ['Koji je hrvatski barokni pjesnik napisao Osmana?','Ivan Gundulić','Fran Krsto Frankopan','Marko Marulić','Ivan Mažuranić'],
    ['Koji je preporodni list Ljudevit Gaj pokrenuo 1835.?','Novine Horvatzke','Obzor','Narodne novine','Vijenac'],
    ['Kako se zvao književni prilog Gajevih novina?','Danica','Zora','Vila','Iskra'],
    ['Tko je 1832. napisao Disertaciju?','Janko Drašković','Ljudevit Gaj','Ante Starčević','Ivan Mažuranić'],
    ['Koji je ban 1848. povezan s ukidanjem kmetstva?','Josip Jelačić','Ivan Mažuranić','Levin Rauch','Khuen-Héderváry'],
    ['Koji je ban bio autor Smrti Smail-age Čengića?','Ivan Mažuranić','Josip Jelačić','Ante Starčević','Ivan Kukuljević'],
    ['Tko je bio jedan od glavnih predstavnika pravaške ideje?','Ante Starčević','Stjepan Radić','Vladko Maček','Frano Supilo'],
    ['Koji je ustanak 1871. povezan s Eugenom Kvaternikom?','Rakovički ustanak','Seljačka buna','Krbavska bitka','Buna 1848.'],
    ['Koji je sporazum 1939. stvorio Banovinu Hrvatsku?','Sporazum Cvetković–Maček','Krfska deklaracija','Zagrebačka rezolucija','Londonski ugovor'],
    ['Tko je bio ban Banovine Hrvatske?','Ivan Šubašić','Vladko Maček','Dragiša Cvetković','Stjepan Radić'],
    ['Koje je godine osnovana Kraljevina SHS?','1918.','1929.','1939.','1941.'],
    ['Kako se Kraljevina SHS službeno nazivala od 1929.?','Kraljevina Jugoslavija','Kraljevina Hrvatska','Federacija Jugoslavija','Država SHS'],
    ['Tko je smrtno ranjen u atentatu u beogradskoj skupštini 1928.?','Stjepan Radić','Vladko Maček','Ante Trumbić','Frano Supilo'],
    ['Koja je država proglašena u travnju 1941. na dijelu teritorija Kraljevine Jugoslavije?','Nezavisna Država Hrvatska','Banovina Hrvatska','Republika Hrvatska','Federalna Hrvatska'],
    ['Koji je pokret pružao organizirani oružani otpor okupatorima i vlastima NDH?','Partizanski pokret','Ilirski pokret','Hrvatsko proljeće','Pravaški pokret'],
    ['Koji je logorski kompleks ustaški režim koristio za zatočenje i masovne zločine?','Jasenovac','Goli otok','Kerestinec','Gradiška'],
    ['Koje su skupine bile među glavnim žrtvama ustaškog režima?','Srbi, Židovi, Romi i politički protivnici','Samo strani vojnici','Samo njemački vojnici','Samo talijanski civili'],
    ['Kako se nakon 1963. nazivala Hrvatska kao federalna jedinica Jugoslavije?','Socijalistička Republika Hrvatska','Narodna Republika Hrvatska','Federalna Hrvatska','Hrvatska Republika'],
    ['Koje je godine održan veliki studentski štrajk u sklopu Hrvatskog proljeća?','1971.','1968.','1974.','1980.'],
    ['Koje je godine održan prvi višestranački izborni ciklus u Hrvatskoj?','1990.','1989.','1991.','1992.'],
    ['Koji je datum konstituiranja prvoga višestranačkog Hrvatskog sabora 1990.?','30. svibnja 1990.','25. lipnja 1991.','8. listopada 1991.','15. siječnja 1992.'],
    ['Koji je ustav donesen 22. prosinca 1990.?','Ustav Republike Hrvatske','Ustav SFRJ','Ustav Banovine Hrvatske','Ustav FNRJ'],
    ['Kako se često naziva Ustav Republike Hrvatske iz 1990.?','Božićni ustav','Proljetni ustav','Zagrebački ustav','Saborni ustav'],
    ['Koji je datum referenduma o hrvatskoj samostalnosti 1991.?','19. svibnja 1991.','25. lipnja 1991.','8. listopada 1991.','30. svibnja 1990.'],
    ['Koji je sporazum bio temelj mirne reintegracije hrvatskog Podunavlja?','Erdutski sporazum','Daytonski sporazum','Vanceov plan','Washingtonski sporazum'],
    ['Koje je godine završila mirna reintegracija hrvatskog Podunavlja?','1998.','1995.','1996.','2000.'],
    ['Koje je godine Hrvatska postala članica NATO-a?','2009.','2004.','2013.','2023.'],
    ['Koje je godine Hrvatska postala članica Europske unije?','2013.','2009.','2004.','2023.'],
    ['Koje je godine Hrvatska uvela euro kao službenu valutu?','2023.','2022.','2020.','2013.'],
    ['Koje je godine Hrvatska ušla u schengenski prostor?','2023.','2020.','2013.','2009.'],
    ['Koji je datum međunarodnog priznanja Hrvatske od država tadašnje Europske zajednice?','15. siječnja 1992.','25. lipnja 1991.','8. listopada 1991.','5. kolovoza 1995.'],
    ['Koje je godine Hrvatska primljena u Ujedinjene narode?','1992.','1991.','1995.','2000.'],
    ['Koje je godine otvorena današnja zgrada Hrvatskog narodnog kazališta u Zagrebu?','1895.','1874.','1866.','1905.'],
    ['Koje je godine osnovana Jugoslavenska akademija znanosti i umjetnosti?','1866.','1874.','1842.','1895.'],
    ['Kako se danas zove Jugoslavenska akademija znanosti i umjetnosti?','Hrvatska akademija znanosti i umjetnosti','Hrvatska znanstvena akademija','Akademija hrvatske baštine','Matica hrvatskih znanosti']
  ];

  window.PATRIA_EXTRA_QUESTIONS.povijest_extra = q;
  window.PatriaSoulQuizBanks = window.PatriaSoulQuizBanks || {};
  window.PatriaSoulQuizBanks.povijestExtra = q;
})();
