// PatriaSoul – Hrvatska povijest
// 100 pitanja od prapovijesti i antike do suvremene Republike Hrvatske.
// Format: [pitanje, točan odgovor, distraktor 1, distraktor 2, distraktor 3].
// Centralni quiz engine preslaguje ponuđene odgovore.
(function(){
  const q = [
    ['Koji je rimski grad bio glavno središte rimske provincije Dalmacije na prostoru današnje Hrvatske?','Salona','Siscia','Mursa','Narona'],
    ['Koji je rimski grad bio smješten na području današnje Istre i poznat po amfiteatru?','Pola (Pula)','Senj','Knin','Sisak'],
    ['Kako se zvao rimski grad na području današnjeg Vida kod Metkovića?','Narona','Salona','Andautonia','Mursa'],
    ['Kako se zvao rimski grad na području današnjeg Siska?','Siscia','Salona','Narona','Pola'],
    ['Koji je grad bio važno rimsko središte u Slavoniji na području današnjeg Osijeka?','Mursa','Siscia','Salona','Tarsatica'],
    ['Koji se grad nalazi na području antičke Tarsatike?','Rijeka','Zadar','Pula','Dubrovnik'],
    ['Kada se okvirno odvijala velika seoba naroda koja je zahvatila prostor današnje Hrvatske?','Na prijelazu iz 4. u 7. stoljeće','U 10. stoljeću','U 15. stoljeću','U 18. stoljeću'],
    ['U kojim se stoljećima prema većini historiografskih tumačenja odvijalo doseljavanje slavenskih skupina na prostor današnje Hrvatske?','U 6. i 7. stoljeću','U 2. i 3. stoljeću','U 10. i 11. stoljeću','U 14. i 15. stoljeću'],
    ['Koji je hrvatski knez poznat po ispravi iz 852. godine?','Trpimir I.','Branimir','Muncimir','Zdeslav'],
    ['Kako se naziva važna isprava kneza Trpimira iz 852.?','Trpimirova darovnica','Vinodolski zakonik','Pacta conventa','Zvonimirova krunidbena isprava'],
    ['Koji je hrvatski knez u 9. stoljeću bio posebno povezan s papom Ivanom VIII.?','Branimir','Trpimir I.','Domagoj','Muncimir'],
    ['Koje je godine papa Ivan VIII. u pismu priznao Branimira kao zakonitog vladara?','879.','852.','925.','1102.'],
    ['Koji se knez smatra osnivačem dinastije Trpimirovića?','Trpimir I.','Tomislav','Zvonimir','Petar Krešimir IV.'],
    ['Kako se zove hrvatska vladarska dinastija koja je obilježila 9.–11. stoljeće?','Trpimirovići','Arpadovići','Frankopani','Habsburgovci'],
    ['Koji se hrvatski vladar u pismu pape Ivana X. iz 925. naziva kraljem Hrvata?','Tomislav','Branimir','Krešimir I.','Zvonimir'],
    ['Koji je hrvatski kralj tradicionalno poznat kao prvi hrvatski kralj?','Tomislav','Zvonimir','Stjepan Držislav','Petar Krešimir IV.'],
    ['Koje godine se u papinskom pismu Tomislav spominje kao kralj Hrvata?','925.','879.','1102.','1075.'],
    ['Koji je podatak o Tomislavovoj krunidbi povijesno sigurno potvrđen?','Nije poznato je li, gdje i od koga okrunjen','Okrunjen je sigurno u Zagrebu','Okrunjen je sigurno u Kninu','Okrunjen je sigurno u Zadru'],
    ['Koji je hrvatski kralj poznat po krunidbi u Solinu prema kasnijim izvorima?','Dmitar Zvonimir','Tomislav','Stjepan II.','Petar Snačić'],
    ['Koji je hrvatski kralj povezan s Bašćanskom pločom?','Dmitar Zvonimir','Tomislav','Mihajlo Krešimir II.','Petar Krešimir IV.'],
    ['U kojem je stoljeću nastala Bašćanska ploča?','Krajem 11. stoljeća','U 7. stoljeću','U 14. stoljeću','U 17. stoljeću'],
    ['Koji hrvatski kralj nosi ime Petar Krešimir IV.?','Kralj iz 11. stoljeća','Kralj iz 8. stoljeća','Kralj iz 14. stoljeća','Kralj iz 16. stoljeća'],
    ['Koji je vladar bio posljednji kralj iz dinastije Trpimirovića?','Stjepan II.','Zvonimir','Petar Krešimir IV.','Tomislav'],
    ['Koji se kralj povezuje s jačanjem hrvatske države sredinom 11. stoljeća?','Petar Krešimir IV.','Tomislav','Branimir','Stjepan Držislav'],
    ['Kako se zvao posljednji hrvatski kralj iz dinastije Snačića?','Petar Snačić','Petar Krešimir IV.','Stjepan II.','Zvonimir'],
    ['Koje se godine tradicionalno povezuje s početkom hrvatsko-ugarske personalne unije?','1102.','925.','1527.','1848.'],
    ['Kojoj je dinastiji pripadao kralj Koloman?','Arpadovićima','Trpimirovićima','Habsburgovcima','Frankopanima'],
    ['Kako se naziva dokument koji se tradicionalno povezuje s odnosom Hrvatske i ugarskog kralja Kolomana?','Pacta Conventa','Vinodolski zakonik','Zvonimirova prisega','Trpimirova darovnica'],
    ['Zašto se u suvremenoj historiografiji oprezno govori o Pacta Conventi?','Izvornost i oblik dokumenta su predmet historiografske rasprave','Jer je napisana na glagoljici','Jer je nastala tek u 19. stoljeću','Jer se odnosi samo na Dubrovnik'],
    ['Koji je hrvatski grad bio važan politički i crkveni centar u srednjem vijeku?','Knin','Varaždin','Karlovac','Rijeka'],
    ['Koji je zakon iz 1288. važan izvor hrvatskog srednjovjekovnog prava?','Vinodolski zakonik','Statut grada Zagreba','Petrinjski statut','Zagrebačka pragmatika'],
    ['Na kojem je jeziku velik dio Vinodolskog zakonika napisan?','Starom hrvatskom književnom jeziku, glagoljicom','Latinskim jezikom','Grčkim jezikom','Njemačkim jezikom'],
    ['Koja je plemićka obitelj kasnije poznata kao Zrinski bila povezana s hrvatskim plemstvom?','Šubići Bribirski','Arpadovići','Kotromanići','Celjski'],
    ['Koja je obitelj bila jedna od najvažnijih hrvatskih velikaških obitelji u kasnom srednjem i ranom novom vijeku?','Frankopani','Hohenzollerni','Romanovi','Tudori'],
    ['Koji je događaj 1493. jedan od najpoznatijih poraza hrvatskog plemstva u borbi protiv Osmanlija?','Bitka na Krbavskom polju','Bitka kod Siska','Bitka kod Sigeta','Bitka kod Petrovaradina'],
    ['Koje se godine dogodila bitka na Krbavskom polju?','1493.','1527.','1593.','1664.'],
    ['Koje se godine dogodila bitka kod Siska u kojoj je poražena osmanska vojska?','1593.','1493.','1527.','1683.'],
    ['Tko je bio zapovjednik obrane Sigeta 1566.?','Nikola Šubić Zrinski','Petar Zrinski','Fran Krsto Frankopan','Ban Josip Jelačić'],
    ['Koje se godine odvila opsada Sigeta?','1566.','1493.','1593.','1664.'],
    ['Koja je utvrda bila središte obrane Nikole Šubića Zrinskog protiv Osmanlija?','Siget','Klis','Medvedgrad','Knin'],
    ['Koja je bitka 1593. označila važnu hrvatsku pobjedu nad Osmanlijama?','Bitka kod Siska','Bitka na Krbavskom polju','Bitka kod Sigeta','Bitka kod Mohácsa'],
    ['Koji je ban i vojskovođa povezan s pobjedom kod Siska 1593.?','Toma Erdődy','Nikola Šubić Zrinski','Petar Krešimir IV.','Josip Jelačić'],
    ['Koja je institucija bila povezana s obranom Habsburške Monarhije od Osmanlija na hrvatskom prostoru?','Vojna krajina','Dalmatinski sabor','Hrvatska banovina','Ilirska čitaonica'],
    ['Koji je hrvatski grad bio sjedište Banske krajine i važno obrambeno središte?','Karlovac','Pula','Dubrovnik','Varaždin'],
    ['Koji je mir 1699. značajno promijenio odnos snaga nakon Velikog bečkog rata?','Karlovački mir','Požarevački mir','Zadarski mir','Srijemski mir'],
    ['Koji je mir 1718. dodatno potisnuo Osmansko Carstvo iz dijela hrvatskog prostora?','Požarevački mir','Karlovački mir','Madridski mir','Londonski mir'],
    ['Koja je vladarica provela važne upravne i vojne reforme u 18. stoljeću?','Marija Terezija','Katarina Velika','Elizabeta I.','Marija Antoaneta'],
    ['Koji je habsburški vladar proveo reforme prosvijećenog apsolutizma u hrvatskim zemljama?','Josip II.','Ferdinand I.','Rudolf II.','Karlo V.'],
    ['Koje su godine hrvatski staleži na Cetinskom saboru izabrali Ferdinanda Habsburškog za kralja?','1527.','1102.','1718.','1848.'],
    ['Gdje je 1527. održan sabor na kojem je izabran Ferdinand Habsburški?','Cetingrad','Knin','Zagreb','Varaždin'],
    ['Koja je dinastija vladala Hrvatskom od izbora Ferdinanda 1527. do 1918.?','Habsburgovci','Trpimirovići','Arpadovići','Frankopani'],
    ['Koji je pokret obilježio hrvatski nacionalni preporod u prvoj polovici 19. stoljeća?','Ilirski pokret','Hrvatsko proljeće','Seljački pokret','Mladoturski pokret'],
    ['Tko je bio jedan od vodećih ljudi hrvatskog narodnog preporoda?','Ljudevit Gaj','Ban Khuen-Héderváry','Ante Pavelić','Ivan Mažuranić'],
    ['Koje su novine bile važno glasilo Ljudevita Gaja?','Novine horvatzke','Narodne novine 1945.','Obzor 1991.','Vjesnik slobode'],
    ['Koji je ban povezan s revolucijom 1848. i ukidanjem kmetstva u Hrvatskoj?','Josip Jelačić','Ivan Mažuranić','Ivan Kukuljević','Josip Šokčević'],
    ['Koje je godine ban Josip Jelačić stupio na bansku čast?','1848.','1830.','1868.','1918.'],
    ['Koji je važan društveni proces obilježio Hrvatsku 1848.?','Ukidanje kmetstva','Uvođenje eura','Ulazak u NATO','Osnivanje Jugoslavije'],
    ['Koji je sporazum iz 1868. uredio odnose Hrvatske i Ugarske unutar Monarhije?','Hrvatsko-ugarska nagodba','Karlovački mir','Pacta Conventa','Cetingradska odluka'],
    ['Koje je godine sklopljena Hrvatsko-ugarska nagodba?','1868.','1848.','1878.','1918.'],
    ['Tko je bio hrvatski ban i književnik koji je donio Zakon o slobodi tiska i školstvu te modernizirao upravu?','Ivan Mažuranić','Josip Jelačić','Stjepan Radić','Ante Starčević'],
    ['Tko se često naziva Ocem Domovine u hrvatskoj političkoj tradiciji?','Ante Starčević','Ljudevit Gaj','Stjepan Radić','Franjo Rački'],
    ['Koji je hrvatski političar bio jedan od vodećih zagovornika jugoslavenskog ujedinjenja prije 1918.?','Frano Supilo','Ante Starčević','Eugen Kvaternik','Josip Jelačić'],
    ['Koje je godine završio Prvi svjetski rat?','1918.','1914.','1916.','1921.'],
    ['Kako se zvala državna tvorevina nastala u listopadu 1918. na južnoslavenskim zemljama Austro-Ugarske?','Država Slovenaca, Hrvata i Srba','Kraljevina Jugoslavija','Banovina Hrvatska','NDH'],
    ['Kada je osnovana Kraljevina Srba, Hrvata i Slovenaca?','1. prosinca 1918.','29. listopada 1918.','6. siječnja 1929.','10. travnja 1941.'],
    ['Kako se od 1929. nazivala Kraljevina Srba, Hrvata i Slovenaca?','Kraljevina Jugoslavija','Federativna Jugoslavija','Banovina Hrvatska','Država Slovenaca, Hrvata i Srba'],
    ['Koji je političar bio najpoznatiji vođa Hrvatske seljačke stranke u međuratnom razdoblju?','Stjepan Radić','Ante Starčević','Vladko Maček','Ivan Mažuranić'],
    ['Tko je 1928. smrtno ranio Stjepana Radića u beogradskoj Narodnoj skupštini?','Puniša Račić','Vladko Maček','Nikola Pašić','Aleksandar Karađorđević'],
    ['Koje je godine proglašena diktatura kralja Aleksandra?','1929.','1918.','1939.','1941.'],
    ['Koja je autonomna jedinica osnovana 1939. sporazumom Cvetković–Maček?','Banovina Hrvatska','Hrvatska Republika','Dalmatinska Banovina','Država Hrvatska'],
    ['Koje je godine osnovana Banovina Hrvatska?','1939.','1929.','1941.','1945.'],
    ['Koji je događaj označio početak Drugog svjetskog rata u Europi?','Njemački napad na Poljsku 1939.','Napad na Pearl Harbor','Napad na Francusku 1940.','Kapitulacija Italije'],
    ['Koje je godine proglašena Nezavisna Država Hrvatska?','1941.','1939.','1943.','1945.'],
    ['Kako se povijesno označava razdoblje NDH?','1941.–1945.','1939.–1941.','1945.–1950.','1929.–1939.'],
    ['Koji je pokret djelovao protiv sila Osovine i njihovih saveznika na području Jugoslavije tijekom Drugog svjetskog rata?','Partizanski pokret','Ilirski pokret','Hrvatski preporod','Domobranski pokret'],
    ['Koja je država bila članica sila Osovine i okupirala dijelove hrvatske obale tijekom Drugog svjetskog rata?','Italija','Švedska','Portugal','Švicarska'],
    ['Koji je logor NDH postao jedan od najpoznatijih simbola masovnih progona i ubojstava?','Jasenovac','Goli otok','Stara Gradiška 1991.','Lepoglava 1971.'],
    ['Koje su skupine bile među glavnim žrtvama ustaškog režima?','Srbi, Židovi, Romi i politički protivnici','Samo strani vojnici','Samo njemački civili','Isključivo članovi HSS-a'],
    ['Koje je godine završio Drugi svjetski rat u Europi?','1945.','1941.','1943.','1948.'],
    ['Koja je država nastala nakon rata kao federacija šest republika?','Federativna Narodna Republika Jugoslavija','Kraljevina Jugoslavija','Država SHS','Banovina Hrvatska'],
    ['Kako se od 1963. nazivala Jugoslavija?','Socijalistička Federativna Republika Jugoslavija','Federativna Narodna Republika Jugoslavija','Kraljevina Jugoslavija','Savezna Republika Jugoslavija'],
    ['Koji je politički pokret u Hrvatskoj dosegnuo vrhunac 1971.?','Hrvatsko proljeće','Ilirski pokret','Mladoturski pokret','Seljačka buna'],
    ['Koji je hrvatski političar bio jedan od vodećih predstavnika reformskog pokreta 1971.?','Savka Dabčević-Kučar','Ante Pavelić','Josip Broz Tito','Nikola Šubić Zrinski'],
    ['Koji je ustav SFRJ iz 1974. dodatno proširio ovlasti republika i pokrajina?','Ustav iz 1974.','Ustav iz 1946.','Ustav iz 1963.','Ustav iz 1988.'],
    ['Koje su godine održani prvi višestranački izbori u suvremenoj Hrvatskoj?','1990.','1980.','1991.','1992.'],
    ['Koja je politička stranka pobijedila na izborima za Hrvatski sabor 1990.?','HDZ','HSS','SKH-SDP','HSP'],
    ['Koji je datum povezan s konstituiranjem prvog višestranačkog Sabora 1990.?','30. svibnja 1990.','25. lipnja 1991.','8. listopada 1991.','15. siječnja 1992.'],
    ['Kada je Hrvatska proglasila neovisnost i suverenost?','25. lipnja 1991.','30. svibnja 1990.','8. listopada 1991.','15. siječnja 1992.'],
    ['Kada je Hrvatski sabor donio odluku o raskidu svih državnopravnih veza s bivšom Jugoslavijom?','8. listopada 1991.','25. lipnja 1991.','5. kolovoza 1995.','22. siječnja 1993.'],
    ['Koje je godine Hrvatska međunarodno priznata i primljena u UN?','1992.','1991.','1995.','1998.'],
    ['Koji je grad postao jedan od najjačih simbola Domovinskog rata?','Vukovar','Varaždin','Pula','Opatija'],
    ['Kada se obilježava Dan sjećanja na žrtve Domovinskog rata i Dan sjećanja na žrtvu Vukovara i Škabrnje?','18. studenoga','5. kolovoza','1. svibnja','25. lipnja'],
    ['Koja je operacija provedena u siječnju 1993. na području zadarskog zaleđa i Maslenice?','Maslenica','Bljesak','Oluja','Medački džep'],
    ['Koja je operacija provedena u rujnu 1993. na području Like?','Medački džep','Maslenica','Bljesak','Oluja'],
    ['Koja je operacija oslobodila velik dio zapadne Slavonije u svibnju 1995.?','Bljesak','Oluja','Maslenica','Orkan ’91'],
    ['Koja je operacija započela 4. kolovoza 1995.?','Oluja','Bljesak','Maslenica','Medački džep'],
    ['Koji je grad oslobođen tijekom Oluje i postao njezin glavni simbol?','Knin','Vukovar','Okučani','Pakrac'],
    ['Koje je godine završena mirna reintegracija hrvatskog Podunavlja?','1998.','1995.','1996.','1999.'],
    ['Koji je sporazum postavio okvir za mirnu reintegraciju hrvatskog Podunavlja?','Erdutski sporazum','Daytonski sporazum','Vanceov plan','Washingtonski sporazum'],
    ['Koje je godine Hrvatska postala članica NATO-a?','2009.','2004.','2013.','2016.'],
    ['Koje je godine Hrvatska postala članica Europske unije?','2013.','2009.','2004.','2020.'],
    ['Koje je godine Hrvatska uvela euro kao službenu valutu?','2023.','2020.','2013.','2009.'],
    ['Koje je godine Hrvatska ušla u Schengenski prostor?','2023.','2013.','2020.','2024.'],
    ['Tko je bio prvi predsjednik Republike Hrvatske nakon uvođenja višestranačja?','Franjo Tuđman','Stjepan Mesić','Franjo Gregurić','Vlado Gotovac'],
    ['Koji je hrvatski dokument iz 1990. postavio temeljni ustavni okvir suvremene Republike Hrvatske?','Ustav Republike Hrvatske','Erdutski sporazum','Zakon o obrani','Vanceov plan'],
    ['Koji je datum Dan državnosti Republike Hrvatske?','30. svibnja','25. lipnja','8. listopada','5. kolovoza'],
    ['Koji je datum Dan neovisnosti Republike Hrvatske?','8. listopada','30. svibnja','25. lipnja','15. siječnja'],
    ['Koji je datum Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja?','5. kolovoza','18. studenoga','1. svibnja','25. lipnja'],
    ['Koji je hrvatski sabor 1991. donio odluku o raskidu državnopravnih veza s Jugoslavijom?','Hrvatski sabor','Banovinski sabor','Dalmatinski sabor','Zemaljski sabor'],
    ['Koji je grad bio sjedište hrvatske političke vlasti i Sabora tijekom najvećeg dijela moderne hrvatske povijesti?','Zagreb','Split','Zadar','Osijek'],
    ['Koji je hrvatski grad bio važan centar srednjovjekovne crkvene povijesti i sjedište ninske biskupije?','Nin','Knin','Dubrovnik','Varaždin'],
    ['Koji je hrvatski grad poznat po Dioklecijanovoj palači?','Split','Pula','Zadar','Šibenik'],
    ['Koji je grad poznat po rimskom amfiteatru iz 1. stoljeća?','Pula','Dubrovnik','Trogir','Rijeka'],
    ['Koji je hrvatski grad poznat po povijesnoj jezgri pod zaštitom UNESCO-a i Dubrovačkim zidinama?','Dubrovnik','Zagreb','Osijek','Karlovac'],
    ['Koji je dokument važan za proučavanje ranog hrvatskog jezika i glagoljice?','Bašćanska ploča','Trpimirova darovnica','Erdutski sporazum','Hrvatsko-ugarska nagodba'],
    ['Koje je pismo korišteno na Bašćanskoj ploči?','Glagoljica','Ćirilica','Arapsko pismo','Runica'],
    ['Koji je znanstvenik i povjesničar bio jedan od najvažnijih hrvatskih istraživača srednjeg vijeka u 19. stoljeću?','Franjo Rački','Ban Khuen-Héderváry','Puniša Račić','Vladko Maček'],
    ['Koji je hrvatski političar i biskup bio važan za razvoj moderne hrvatske kulture i politike u 19. stoljeću?','Josip Juraj Strossmayer','Ante Pavelić','Aleksandar Karađorđević','Nikola Pašić'],
    ['Koji je hrvatski biskup povezan s osnivanjem Sveučilišta u Zagrebu i Jugoslavenske akademije znanosti i umjetnosti?','Josip Juraj Strossmayer','Alojzije Stepinac','Juraj Haulik','Maksimilijan Vrhovac'],
    ['Koji je hrvatski kardinal bio zagrebački nadbiskup tijekom Drugog svjetskog rata i poraća?','Alojzije Stepinac','Josip Juraj Strossmayer','Franjo Kuharić','Juraj Haulik'],
    ['Koji je hrvatski nadbiskup bio važna osoba Crkve tijekom Domovinskog rata?','Franjo Kuharić','Alojzije Stepinac','Josip Bozanić','Josip Juraj Strossmayer'],
    ['Koji je grad bio sjedište Hrvatskog sabora i banova prije nego što je Zagreb postao trajno političko središte?','Varaždin','Rijeka','Pula','Šibenik'],
    ['Koji je hrvatski grad bio slobodna komuna i važna pomorska republika kroz stoljeća?','Dubrovnik','Knin','Karlovac','Sisak'],
    ['Koji je događaj 1664. povezan s pogibijom Nikole Zrinskog?','Nesreća u lovu nakon bitke kod Svetog Gottharda','Opsada Sigeta','Bitka kod Siska','Zrinsko-frankopanska urota'],
    ['Koje godine su Petar Zrinski i Fran Krsto Frankopan pogubljeni u Bečkom Novom Mjestu?','1671.','1664.','1527.','1848.'],
    ['Koji se događaj naziva Zrinsko-frankopanskom urotom?','Pokušaj političkog otpora i pregovora velikaša protiv habsburške politike','Seljačka buna 1573.','Ilirski pokret','Hrvatsko proljeće'],
    ['Koje godine je pogubljen Matija Gubec?','1573.','1493.','1593.','1671.'],
    ['Koja je pobuna poznata kao velika seljačka buna Matije Gupca?','Seljačka buna 1573.','Krbavska buna','Varaždinska buna 1848.','Zrinsko-frankopanska buna'],
    ['Koja je hrvatska regija stoljećima imala posebnu vezu s Mletačkom Republikom?','Dio Dalmacije','Međimurje','Slavonija','Lika cijela'],
    ['Koji je grad bio glavno mletačko središte u Dalmaciji?','Zadar','Zagreb','Sisak','Varaždin'],
    ['Koji je hrvatski grad postao važan kontinentalni barokni centar u 17. i 18. stoljeću?','Varaždin','Pula','Dubrovnik','Knin'],
    ['Koji je događaj 1918. označio raspad Austro-Ugarske Monarhije?','Stvaranje novih nacionalnih država i Države SHS','Osnivanje Banovine Hrvatske','Uspostava SFRJ','Uvođenje diktature'],
    ['Koje je godine osnovana Republika Hrvatska kao suvremena međunarodno priznata država?','1991.','1918.','1945.','1989.'],
    ['Što je temeljni cilj hrvatske politike 1990.–1991. prema Ustavu i odlukama Sabora?','Ostvarenje suverene i samostalne Republike Hrvatske','Obnova Austro-Ugarske','Uspostava nove monarhije','Pristupanje Varšavskom paktu'],
    ['Koji je izraz najprikladniji za razdoblje hrvatske povijesti od 1991. do 1995.?','Domovinski rat','Ilirski preporod','Hrvatsko proljeće','Veliki bečki rat'],
    ['Koja je povijesna institucija danas središnje zakonodavno tijelo Republike Hrvatske?','Hrvatski sabor','Hrvatska banska konferencija','Carevinsko vijeće','Državni sabor SHS'],
    ['Kako se službeno zove država koja je danas članica EU i NATO-a?','Republika Hrvatska','Kraljevina Hrvatska','Hrvatska Banovina','Federativna Hrvatska'],
    ['Koji je glavni grad Republike Hrvatske?','Zagreb','Split','Rijeka','Osijek']
  ];

  window.PatriaSoulQuizBanks = window.PatriaSoulQuizBanks || {};
  window.PatriaSoulQuizBanks.povijest = q;
  window.povijestQuiz = q;
})();
