// PatriaSoul – dodatnih 800 pitanja (8 kategorija × 100)
// Svaki zapis je [pitanje, točan odgovor, pogrešni odgovori]. quiz.js ih pretvara u standardni format.
window.PATRIA_EXTRA_QUESTIONS = {};

const makeBank=(category, facts)=>facts.map((f,i)=>{const answers=[f[1],f[2],f[3],f[4]];return {id:`${category}_${String(i+1).padStart(3,'0')}`,category,question:f[0],answers,correctIndex:0};});

// Hrvatska geografija
window.PATRIA_EXTRA_QUESTIONS.geografija=makeBank('geografija',[
['Koji je najviši vrh Hrvatske?','Sinjal na Dinari','Vaganski vrh','Sveto brdo','Snježnik'],
['Koji je najveći hrvatski otok po površini?','Cres','Krk','Brač','Hvar'],
['Koji je najduži hrvatski otok?','Hvar','Cres','Krk','Brač'],
['Koja je najduža rijeka koja cijelim tokom teče Hrvatskom?','Kupa','Drava','Sava','Dunav'],
['Koja je najduža rijeka u Hrvatskoj?','Sava','Drava','Dunav','Kupa'],
['Koje je najveće prirodno jezero u Hrvatskoj?','Vransko jezero','Perućko jezero','Bajer','Lokvarsko jezero'],
['Koji je nacionalni park poznat po kaskadnim jezerima i slapovima?','Plitvička jezera','Krka','Paklenica','Risnjak'],
['Koji nacionalni park obuhvaća otoke Veliki i Mali Brijun?','Brijuni','Kornati','Mljet','Krka'],
['Koji nacionalni park obuhvaća velik dio otoka Mljeta?','Mljet','Brijuni','Kornati','Risnjak'],
['Koji nacionalni park poznat je po stotinama otoka i otočića?','Kornati','Brijuni','Mljet','Plitvice'],
['Koji nacionalni park poznat je po kanjonima Velike i Male Paklenice?','Paklenica','Risnjak','Krka','Sjeverni Velebit'],
['Koji nacionalni park nalazi se na području Gorskog kotara?','Risnjak','Brijuni','Mljet','Kornati'],
['Koji nacionalni park obuhvaća Zavižan i sjeverni Velebit?','Sjeverni Velebit','Paklenica','Risnjak','Plitvička jezera'],
['Koji je najviši planinski lanac u Hrvatskoj?','Dinara','Velebit','Biokovo','Velika Kapela'],
['Koja planina se proteže uz velik dio hrvatske obale?','Velebit','Medvednica','Papuk','Psunj'],
['Koja planina dominira područjem iznad Makarske?','Biokovo','Dinara','Velebit','Mosor'],
['Koja planina se nalazi neposredno iznad Zagreba?','Medvednica','Papuk','Učka','Biokovo'],
['Koja je najviša točka Biokova?','Sveti Jure','Sinjal','Vaganski vrh','Kula'],
['Koja je najviša točka Medvednice?','Sljeme','Lipa','Puntijarka','Medvedgrad'],
['Koji je grad glavni grad Hrvatske?','Zagreb','Split','Rijeka','Osijek'],
['Koji je najveći hrvatski grad na Jadranu?','Split','Rijeka','Zadar','Pula'],
['Koji je najveći hrvatski lučki grad na Kvarneru?','Rijeka','Pula','Zadar','Šibenik'],
['Koji grad leži na ušću rijeke Neretve?','Metković','Opuzen','Ploče','Dubrovnik'],
['Koja rijeka protječe kroz Zagreb?','Sava','Kupa','Drava','Mura'],
['Koja rijeka protječe kroz Osijek?','Drava','Sava','Kupa','Mura'],
['Koja rijeka protječe kroz Karlovac?','Kupa','Sava','Drava','Dunav'],
['Koja rijeka protječe kroz Sisak?','Kupa','Cetina','Zrmanja','Krka'],
['Koja rijeka protječe kroz Slavonski Brod?','Sava','Drava','Kupa','Dunav'],
['Koja rijeka protječe kroz Varaždin?','Drava','Mura','Sava','Kupa'],
['Koja rijeka čini dio granice Hrvatske i Mađarske?','Drava','Cetina','Kupa','Zrmanja'],
['Koja rijeka čini dio granice Hrvatske i Slovenije?','Kupa','Cetina','Krka','Neretva'],
['Koja rijeka teče kroz Sinj?','Cetina','Krka','Zrmanja','Neretva'],
['Koja rijeka protječe kroz Knin?','Krka','Cetina','Zrmanja','Kupa'],
['Koja rijeka protječe područjem Obrovca?','Zrmanja','Krka','Cetina','Kupa'],
['Koja rijeka ima poznate slapove kod Skradina?','Krka','Cetina','Zrmanja','Mrežnica'],
['Koja rijeka ima slap Veliki buk u Nacionalnom parku Una?','Una','Kupa','Mrežnica','Korana'],
['Koji je najveći poluotok u Hrvatskoj?','Istra','Pelješac','Pag','Kvarner'],
['Koji je najveći hrvatski poluotok na jugu Dalmacije?','Pelješac','Istra','Pag','Čiovo'],
['Koji otok je poznat po Zlatnom ratu?','Brač','Hvar','Vis','Pag'],
['Koji je otok poznat po gradu Hvaru?','Hvar','Brač','Korčula','Vis'],
['Koji otok je poznat po gradu Korčuli?','Korčula','Hvar','Brač','Vis'],
['Koji otok je poznat po Modroj špilji u blizini?','Biševo','Vis','Hvar','Lastovo'],
['Koji otok je poznat po Modroj špilji kao turističkoj atrakciji?','Biševo','Brač','Pag','Cres'],
['Koji je otok najbliži dalmatinskoj obali među velikim otocima?','Brač','Cres','Lošinj','Krk'],
['Koji otok je poznat po Starogradskom polju?','Hvar','Brač','Korčula','Vis'],
['Koji je grad na otoku Krku?','Krk','Cres','Mali Lošinj','Rab'],
['Koji otok je povezan s gradom Malim Lošinjem?','Lošinj','Cres','Krk','Rab'],
['Koji otok je poznat po gradu Rabu?','Rab','Pag','Cres','Lošinj'],
['Koji otok je poznat po gradu Pagu?','Pag','Rab','Vir','Ugljan'],
['Koji otok leži neposredno uz Zadar?','Ugljan','Brač','Hvar','Vis'],
['Koji otok je povezan mostom s kopnom kod Nina i Privlake?','Vir','Pag','Ugljan','Dugi otok'],
['Koji je otok poznat po parku prirode Telašćica u svojoj blizini?','Dugi otok','Ugljan','Pašman','Šolta'],
['Koji je hrvatski otok najpoznatiji po Parku prirode Telašćica?','Dugi otok','Brač','Hvar','Korčula'],
['Koji otok je poznat po parku prirode Lastovsko otočje?','Lastovo','Vis','Mljet','Korčula'],
['Koji je grad poznat kao „grad na četiri rijeke“?','Karlovac','Sisak','Osijek','Varaždin'],
['Koji je grad poznat po kuli Kamerlengo?','Trogir','Split','Zadar','Šibenik'],
['Koji grad je poznat po Forumu i Morskim orguljama?','Zadar','Pula','Dubrovnik','Trogir'],
['Koji je grad poznat po Dioklecijanovoj palači?','Split','Zadar','Trogir','Dubrovnik'],
['Koji je grad poznat po Stradunu?','Dubrovnik','Split','Zadar','Šibenik'],
['Koji je grad poznat po Areni?','Pula','Rijeka','Zadar','Šibenik'],
['Koji je grad poznat po katedrali sv. Jakova?','Šibenik','Trogir','Zadar','Split'],
['Koji je grad poznat po Eufrazijevoj bazilici?','Poreč','Rovinj','Pula','Umag'],
['Koji je grad na ušću rijeke Neretve i važna luka?','Ploče','Metković','Opuzen','Makarska'],
['Koji je hrvatski grad na Dunavu?','Vukovar','Karlovac','Rijeka','Pula'],
['Koji grad leži na ušću Drave u Dunav?','Osijek','Vukovar','Ilok','Varaždin'],
['Koji je grad poznat po srednjovjekovnoj tvrđavi Trakošćan u okolici?','Varaždin','Čakovec','Krapina','Koprivnica'],
['Koji je grad poznat po Starom gradu i festivalu barokne glazbe?','Varaždin','Zagreb','Samobor','Križevci'],
['Koji je grad poznat po Muzeju krapinskih neandertalaca?','Krapina','Varaždin','Čakovec','Zabok'],
['Koji grad je središte Međimurske županije?','Čakovec','Varaždin','Koprivnica','Virovitica'],
['Koji grad je središte Istre?','Pazin','Pula','Rovinj','Labin'],
['Koji je najveći grad Istre?','Pula','Pazin','Rovinj','Umag'],
['Koji grad je poznat po Limskom kanalu u blizini?','Rovinj','Pula','Pazin','Labin'],
['Koji grad je poznat po staroj jezgri na brežuljku iznad Kvarnera?','Labin','Rijeka','Opatija','Crikvenica'],
['Koji grad je poznat po Opatijskoj rivijeri?','Opatija','Senj','Novi Vinodolski','Crikvenica'],
['Koji grad je poznat po tvrđavi Nehaj?','Senj','Rijeka','Karlovac','Gospić'],
['Koji grad je središte Like?','Gospić','Knin','Ogulin','Otočac'],
['Koji grad je poznat po tvrđavi i Frankopanima?','Ogulin','Gospić','Slunj','Karlovac'],
['Koji grad je poznat po Rastokama?','Slunj','Ogulin','Karlovac','Glina'],
['Koji grad je poznat po slapovima Rastoka u svojoj blizini?','Slunj','Sisak','Petrinja','Gospić'],
['Koji je grad središte Karlovačke županije?','Karlovac','Ogulin','Slunj','Duga Resa'],
['Koji je grad središte Zadarske županije?','Zadar','Biograd','Pag','Benkovac'],
['Koji je grad središte Šibensko-kninske županije?','Šibenik','Knin','Drniš','Vodice'],
['Koji je grad središte Splitsko-dalmatinske županije?','Split','Sinj','Trogir','Omiš'],
['Koji je grad središte Dubrovačko-neretvanske županije?','Dubrovnik','Metković','Ploče','Korčula'],
['Koji je grad središte Primorsko-goranske županije?','Rijeka','Opatija','Krk','Delnice'],
['Koji je grad središte Ličko-senjske županije?','Gospić','Senj','Otočac','Korenica'],
['Koji je grad središte Vukovarsko-srijemske županije?','Vukovar','Vinkovci','Županja','Ilok'],
['Koji je grad središte Brodsko-posavske županije?','Slavonski Brod','Nova Gradiška','Požega','Đakovo'],
['Koji je grad središte Osječko-baranjske županije?','Osijek','Đakovo','Našice','Beli Manastir'],
['Koji je grad središte Požeško-slavonske županije?','Požega','Pakrac','Lipik','Slavonska Požega'],
['Koji je grad središte Virovitičko-podravske županije?','Virovitica','Slatina','Orahovica','Pitomača'],
['Koji je grad središte Koprivničko-križevačke županije?','Koprivnica','Križevci','Đurđevac','Bjelovar'],
['Koji je grad središte Bjelovarsko-bilogorske županije?','Bjelovar','Garešnica','Čazma','Daruvar'],
['Koji je grad središte Sisačko-moslavačke županije?','Sisak','Petrinja','Kutina','Novska'],
['Koji je grad središte Zagrebačke županije?','Zagreb','Velika Gorica','Samobor','Zaprešić'],
['Koji je grad najveći u Zagrebačkoj županiji?','Velika Gorica','Samobor','Zaprešić','Dugo Selo'],
['Koji je grad poznat po Samoborskoj kremšniti?','Samobor','Zaprešić','Jastrebarsko','Velika Gorica'],
['Koji je grad poznat po Tuheljskim toplicama u svojoj županiji?','Krapina','Zabok','Pregrada','Klanjec'],
['Koji je grad središte Krapinsko-zagorske županije?','Krapina','Zabok','Varaždin','Čakovec'],
['Koji je grad središte Varaždinske županije?','Varaždin','Ivanec','Ludbreg','Novi Marof'],
['Koji je grad središte Koprivničko-križevačke županije?','Koprivnica','Križevci','Đurđevac','Bjelovar']
]);

// Gradovi i znamenitosti
window.PATRIA_EXTRA_QUESTIONS.gradovi=makeBank('gradovi',[
['Koji je glavni grad Hrvatske?','Zagreb','Split','Rijeka','Osijek'],['U kojem je gradu Hrvatski sabor?','Zagreb','Split','Zadar','Varaždin'],['U kojem je gradu Ban Jelačićev trg?','Zagreb','Rijeka','Pula','Osijek'],['Koji grad ima katedralu Uznesenja Marijina?','Zagreb','Split','Dubrovnik','Pula'],['Koji grad ima Lotrščak?','Zagreb','Varaždin','Karlovac','Samobor'],['Koji grad ima Kamenita vrata?','Zagreb','Split','Zadar','Dubrovnik'],['Koji grad ima Mirogoj?','Zagreb','Rijeka','Osijek','Pula'],['Koji grad je poznat po Jarunu?','Zagreb','Split','Rijeka','Zadar'],['Koji grad je poznat po Maksimiru?','Zagreb','Osijek','Varaždin','Karlovac'],['Koji grad ima Medvedgrad iznad sebe?','Zagreb','Samobor','Krapina','Karlovac'],
['Koji grad ima Dioklecijanovu palaču?','Split','Zadar','Dubrovnik','Trogir'],['Koji grad ima Peristil?','Split','Zagreb','Pula','Šibenik'],['Koji grad ima Rivu poznatu kao gradsko šetalište?','Split','Rijeka','Zadar','Pula'],['Koji grad ima katedralu sv. Duje?','Split','Dubrovnik','Zagreb','Trogir'],['Koji grad je polazište za Marjan?','Split','Šibenik','Zadar','Trogir'],['Koji grad ima stadion Poljud?','Split','Zagreb','Rijeka','Osijek'],['Koji grad ima tvrđavu Klis u neposrednoj blizini?','Split','Zadar','Pula','Rijeka'],['Koji grad je povezan s tvrđavom Gripe?','Split','Dubrovnik','Varaždin','Osijek'],['Koji grad ima Bačvice?','Split','Zadar','Rijeka','Pula'],['Koji grad je središte Dalmacije?','Split','Zadar','Šibenik','Dubrovnik'],
['Koji grad ima Stradun?','Dubrovnik','Split','Zadar','Trogir'],['Koji grad ima gradske zidine poznate u svijetu?','Dubrovnik','Pula','Šibenik','Rijeka'],['Koji grad ima tvrđavu Lovrijenac?','Dubrovnik','Split','Zadar','Trogir'],['Koji grad ima Onofrijevu česmu?','Dubrovnik','Zadar','Šibenik','Pula'],['Koji grad ima crkvu sv. Vlaha?','Dubrovnik','Split','Trogir','Zadar'],['Koji grad ima Knežev dvor?','Dubrovnik','Zagreb','Rijeka','Osijek'],['Koji grad ima otok Lokrum u neposrednoj blizini?','Dubrovnik','Split','Pula','Zadar'],['Koji grad je povijesno povezan s Dubrovačkom Republikom?','Dubrovnik','Rijeka','Osijek','Varaždin'],['Koji grad je poznat po vratima od Pila?','Dubrovnik','Zadar','Trogir','Pula'],['Koji grad je poznat po Festi sv. Vlaha?','Dubrovnik','Split','Šibenik','Zadar'],
['Koji grad ima Morske orgulje?','Zadar','Split','Pula','Šibenik'],['Koji grad ima Pozdrav Suncu?','Zadar','Rijeka','Dubrovnik','Trogir'],['Koji grad ima crkvu sv. Donata?','Zadar','Split','Pula','Šibenik'],['Koji grad ima Forum iz rimskog doba?','Zadar','Osijek','Varaždin','Rijeka'],['Koji grad ima Narodni trg i Kalelargu?','Zadar','Split','Trogir','Pula'],['Koji grad je poznat po zadarskim zidinama na UNESCO popisu?','Zadar','Dubrovnik','Šibenik','Trogir'],['Koji grad ima Arsenal kao dio povijesne jezgre?','Zadar','Pula','Rijeka','Split'],['Koji grad je povijesno središte sjeverne Dalmacije?','Zadar','Split','Dubrovnik','Šibenik'],['Koji grad je poznat po crkvi sv. Marije i benediktinskom samostanu?','Zadar','Trogir','Pula','Šibenik'],['Koji grad je poznat po relikvijama sv. Šimuna?','Zadar','Split','Dubrovnik','Rijeka'],
['Koji grad ima katedralu sv. Jakova?','Šibenik','Zadar','Trogir','Split'],['Koji grad ima tvrđavu sv. Mihovila?','Šibenik','Split','Pula','Dubrovnik'],['Koji grad ima tvrđavu Barone?','Šibenik','Zadar','Trogir','Knin'],['Koji grad ima tvrđavu sv. Ivana?','Šibenik','Split','Dubrovnik','Zadar'],['Koji grad je poznat po kanalu sv. Ante?','Šibenik','Zadar','Pula','Rijeka'],['Koji grad je povezan sa Skradinskim bukom?','Šibenik','Dubrovnik','Split','Zadar'],['Koji grad je poznat po tvrđavi sv. Nikole na ulazu u kanal?','Šibenik','Pula','Zadar','Trogir'],['Koji grad je povijesno sjedište Šibenske biskupije?','Šibenik','Split','Zadar','Dubrovnik'],['Koji grad ima katedralu građenu od kamenih blokova bez žbuke?','Šibenik','Pula','Zadar','Rijeka'],['Koji grad je važan za posjet NP Krka?','Šibenik','Varaždin','Osijek','Karlovac'],
['Koji grad ima katedralu sv. Lovre?','Trogir','Split','Šibenik','Zadar'],['Koji grad ima Kamerlengo?','Trogir','Dubrovnik','Pula','Zadar'],['Koji grad ima Radovanov portal?','Trogir','Split','Šibenik','Dubrovnik'],['Koji grad je na UNESCO popisu zbog povijesne jezgre?','Trogir','Rijeka','Osijek','Karlovac'],['Koji grad ima tvrđavu Kamerlengo uz more?','Trogir','Pula','Zadar','Dubrovnik'],['Koji grad ima ložu i katedralu sv. Lovre?','Trogir','Split','Rijeka','Pula'],['Koji grad se nalazi na otoku i kopnu povezanom mostom?','Trogir','Pula','Zadar','Rijeka'],['Koji grad je poznat po Ćipikovoj palači?','Trogir','Split','Dubrovnik','Šibenik'],['Koji grad je dio UNESCO baštine zajedno s povijesnom jezgrom?','Trogir','Osijek','Varaždin','Sisak'],['Koji grad se nalazi između Splita i Šibenika?','Trogir','Pula','Rijeka','Dubrovnik'],
['Koji grad ima rimsku Arenu?','Pula','Rijeka','Zadar','Šibenik'],['Koji grad ima Augustov hram?','Pula','Split','Trogir','Dubrovnik'],['Koji grad je najveći u Istri?','Pula','Pazin','Rovinj','Umag'],['Koji grad ima slavoluk Sergijevaca?','Pula','Rijeka','Zadar','Poreč'],['Koji grad je poznat po Brijunima u blizini?','Pula','Rijeka','Split','Dubrovnik'],['Koji grad ima povijesni Kaštel na brežuljku?','Pula','Zadar','Šibenik','Trogir'],['Koji grad ima Forum iz rimskog razdoblja?','Pula','Osijek','Varaždin','Rijeka'],['Koji grad je važna luka Istre?','Pula','Pazin','Rovinj','Labin'],['Koji grad ima brodograđevnu tradiciju Uljanika?','Pula','Rijeka','Split','Zadar'],['Koji grad je središte Istarske županije?','Pazin','Pula','Rovinj','Umag'],
['Koji grad ima Trsatsku gradinu?','Rijeka','Pula','Senj','Opatija'],['Koji grad ima Korzo kao glavnu gradsku promenadu?','Rijeka','Split','Zadar','Osijek'],['Koji grad ima Riječki karneval?','Rijeka','Pula','Zagreb','Varaždin'],['Koji grad je najveća luka Hrvatske?','Rijeka','Split','Pula','Zadar'],['Koji grad ima Guvernerovu palaču?','Rijeka','Zadar','Pula','Dubrovnik'],['Koji grad je povezan s otokom Krkom mostom?','Rijeka','Zadar','Split','Šibenik'],['Koji grad ima svetište Majke Božje Trsatske?','Rijeka','Split','Zagreb','Dubrovnik'],['Koji grad je središte Primorsko-goranske županije?','Rijeka','Krk','Opatija','Delnice'],['Koji grad ima Muzej moderne i suvremene umjetnosti?','Rijeka','Pula','Zadar','Osijek'],['Koji grad je europska prijestolnica kulture 2020. u Hrvatskoj?','Rijeka','Zagreb','Split','Dubrovnik'],
['Koji grad je na Dunavu i simbol obrane 1991.?','Vukovar','Osijek','Ilok','Slavonski Brod'],['Koji grad je poznat po Vučedolskoj kulturi?','Vukovar','Osijek','Vinkovci','Đakovo'],['Koji grad ima Muzej vučedolske kulture u blizini?','Vukovar','Zagreb','Split','Pula'],['Koji grad ima Vodotoranj kao simbol?','Vukovar','Osijek','Zadar','Knin'],['Koji grad je središte Vukovarsko-srijemske županije?','Vukovar','Vinkovci','Ilok','Županja'],['Koji grad je poznat po rimskom caru Valentinu?','Vinkovci','Vukovar','Osijek','Đakovo'],['Koji grad je poznat po baroknoj Tvrđi?','Osijek','Varaždin','Vukovar','Požega'],['Koji grad leži na Dravi?','Osijek','Vukovar','Vinkovci','Slavonski Brod'],['Koji grad ima konkatedralu sv. Petra i Pavla?','Osijek','Varaždin','Zagreb','Đakovo'],['Koji grad je poznat po osječkoj Tvrđi?','Osijek','Vukovar','Požega','Slavonski Brod'],
['Koji grad je poznat po katedrali sv. Petra u Đakovu?','Đakovo','Osijek','Požega','Vinkovci'],['Koji grad je poznat po ergeli lipicanaca u blizini?','Đakovo','Varaždin','Zagreb','Rijeka'],['Koji grad je poznat po tvrđavi u centru i četiri rijeke?','Karlovac','Sisak','Osijek','Varaždin'],['Koji grad ima Staru jezgru i Dubovac?','Karlovac','Zagreb','Rijeka','Varaždin'],['Koji grad ima tvrđavu Dubovac?','Karlovac','Ogulin','Sisak','Slunj'],['Koji grad je poznat po kuli Nehaj?','Senj','Rijeka','Zadar','Karlovac'],['Koji grad je poznat po muzeju neandertalaca?','Krapina','Varaždin','Čakovec','Zagreb'],['Koji grad ima baroknu jezgru i Špancirfest?','Varaždin','Zagreb','Samobor','Koprivnica'],['Koji grad je poznat po Samoborskom fašniku?','Samobor','Varaždin','Zagreb','Krapina'],['Koji grad je poznat po Starom gradu Ozlju u okolici?','Ozalj','Karlovac','Jastrebarsko','Samobor']
]);

// Hrvatski kraljevi – 100 pitanja o vladarima i ranosrednjovjekovnoj državnoj tradiciji
window.PATRIA_EXTRA_QUESTIONS.kraljevi=makeBank('kraljevi',[
['Koji se vladar tradicionalno navodi kao prvi hrvatski kralj?','Tomislav','Trpimir I.','Branimir','Zvonimir'],['Koji se vladar u papinskom pismu iz 879. spominje kao knez?','Branimir','Tomislav','Zvonimir','Krešimir IV.'],['Koji je vladar povezan s Trpimirovom darovnicom iz 852.?','Trpimir I.','Muncimir','Branimir','Tomislav'],['Koji je vladar poznat po Muncimirovoj darovnici?','Muncimir','Trpimir I.','Branimir','Zvonimir'],['Koji je kralj povezan s Bašćanskom pločom?','Dmitar Zvonimir','Tomislav','Petar Krešimir IV.','Stjepan Držislav'],['Koji je kralj poznat kao Petar Krešimir IV.?','Petar Krešimir IV.','Petar Svačić','Dmitar Zvonimir','Krešimir III.'],['Koji je kralj nosio ime Stjepan Držislav?','Stjepan Držislav','Stjepan II.','Stjepan I.','Krešimir III.'],['Koji se kralj povezuje s crkvom sv. Petra i Mojsija u Solinu?','Petar Krešimir IV.','Tomislav','Zvonimir','Stjepan Držislav'],['Koji se kralj povezuje s obnovom Splitske nadbiskupije?','Petar Krešimir IV.','Tomislav','Zvonimir','Mihajlo Krešimir II.'],['Koji je kralj okrunjen u Solinu prema tradicionalnoj predaji?','Dmitar Zvonimir','Tomislav','Petar Krešimir IV.','Stjepan Držislav'],
['Koji je vladar bio hrvatski knez prije kraljevske titule?','Tomislav','Zvonimir','Krešimir IV.','Stjepan Držislav'],['Koji je vladar vladao Hrvatskom u 9. stoljeću i povezuje se s Trpimirovom darovnicom?','Trpimir I.','Muncimir','Branimir','Domagoj'],['Koji je vladar naslijedio Trpimira I. prema tradicionalnoj kronologiji?','Domagoj','Tomislav','Zvonimir','Krešimir IV.'],['Koji je vladar poznat po sukobima s Mlečanima u 9. stoljeću?','Domagoj','Branimir','Muncimir','Tomislav'],['Koji je knez naslijedio Domagoja?','Zdeslav','Trpimir II.','Muncimir','Branimir'],['Koji je knez svrgnuo Zdeslava?','Branimir','Tomislav','Muncimir','Zvonimir'],['Koji je knez dobio papinsko priznanje 879.?','Branimir','Domagoj','Zdeslav','Muncimir'],['Koji je vladar naslijedio Branimira?','Muncimir','Tomislav','Zvonimir','Krešimir IV.'],['Koji je vladar povezan s Višeslavovom krstionicom?','Višeslav','Branimir','Trpimir','Tomislav'],['Koji se vladar spominje na Višeslavovoj krstionici?','Višeslav','Muncimir','Zdeslav','Domagoj'],
['Koji je kralj bio iz dinastije Trpimirovića?','Tomislav','Ladislav Napuljski','Koloman','Karlo Robert'],['Koji je kralj bio posljednji vladar iz dinastije Trpimirovića?','Stjepan II.','Tomislav','Zvonimir','Krešimir IV.'],['Koji se kralj tradicionalno navodi kao nasljednik Petra Krešimira IV.?','Dmitar Zvonimir','Tomislav','Stjepan Držislav','Petar Svačić'],['Koji je kralj imao papinskog legata kao krunidbenog posrednika prema predaji?','Dmitar Zvonimir','Tomislav','Krešimir IV.','Stjepan Držislav'],['Koji je kralj poznat po Zvonimirovoj zavjernici?','Dmitar Zvonimir','Tomislav','Petar Krešimir IV.','Stjepan Držislav'],['Koji je kralj imao suprugu Jelenu?','Dmitar Zvonimir','Tomislav','Petar Krešimir IV.','Stjepan Držislav'],['Kako se zvala supruga Dmitra Zvonimira?','Jelena','Margareta','Katarina','Jelena Lijepa'],['Koji je kralj povezan s crkvom sv. Lucije u Jurandvoru?','Dmitar Zvonimir','Tomislav','Krešimir IV.','Stjepan Držislav'],['Koji je hrvatski kralj poznat po proširenju vlasti prema dalmatinskim gradovima?','Petar Krešimir IV.','Tomislav','Branimir','Zdeslav'],['Koji kralj nosi naziv „kralj Hrvata i Dalmatinaca“ u izvorima?','Petar Krešimir IV.','Tomislav','Branimir','Muncimir'],
['Koji je vladar povezan s jačanjem hrvatske mornarice u 10. stoljeću?','Tomislav','Zvonimir','Krešimir IV.','Branimir'],['Koji je vladar tradicionalno povezan s pobjedom nad Mađarima?','Tomislav','Zvonimir','Krešimir IV.','Branimir'],['Koji je kralj povezan s Hrvatskom u doba crkvenih reformi 11. stoljeća?','Dmitar Zvonimir','Tomislav','Muncimir','Branimir'],['Koji vladar je prema tradicionalnoj kronologiji vladao oko sredine 10. stoljeća?','Mihajlo Krešimir II.','Tomislav','Zvonimir','Branimir'],['Koji vladar je bio sin Trpimira I.?','Krešimir I.','Tomislav','Branimir','Zvonimir'],['Koji vladar se navodi kao otac Mihajla Krešimira II.?','Krešimir I.','Tomislav','Zvonimir','Branimir'],['Koji je vladar bio sin Mihajla Krešimira II.?','Stjepan Držislav','Zvonimir','Tomislav','Branimir'],['Koji je vladar bio otac Stjepana Držislava?','Mihajlo Krešimir II.','Petar Krešimir IV.','Tomislav','Zvonimir'],['Koji je kralj vladao prije Petra Krešimira IV.?','Stjepan Držislav','Zvonimir','Tomislav','Stjepan II.'],['Koji je kralj vladao nakon Dmitra Zvonimira?','Stjepan II.','Tomislav','Krešimir IV.','Branimir'],
['Koji je vladar bio povezan s dinastijom Trpimirovića?','Muncimir','Koloman','Ladislav Napuljski','Karlo Robert'],['Koji je vladar bio knez, a ne kralj?','Branimir','Zvonimir','Krešimir IV.','Stjepan Držislav'],['Koji je vladar bio knez u vrijeme pape Ivana VIII.?','Branimir','Tomislav','Zvonimir','Mihajlo Krešimir II.'],['Koji je papa poslao pismo Branimiru 879.?','Ivan VIII.','Ivan XII.','Lav III.','Grgur VII.'],['Koji se datum često navodi u hrvatskoj tradiciji kao priznanje Branimira?','7. lipnja 879.','25. lipnja 1991.','5. kolovoza 1995.','30. svibnja 1990.'],['Koji je vladar povezan s darovnicom iz 852.?','Trpimir I.','Branimir','Muncimir','Zdeslav'],['Koji se samostan spominje u Trpimirovoj darovnici?','Rižinice','Lepoglava','Trsat','Brač'],['Koji je vladar povezan s benediktinskim samostanima u ranom srednjem vijeku?','Trpimir I.','Tomislav','Zvonimir','Branimir'],['Koji je kralj povezan s jačanjem Splita i Trogira u 11. stoljeću?','Petar Krešimir IV.','Tomislav','Branimir','Muncimir'],['Koji je kralj imao vlast nad većim dijelom dalmatinske obale prema izvorima?','Petar Krešimir IV.','Branimir','Trpimir I.','Muncimir'],
['Koji je vladar poznat po naslovu „rex Croatorum“?','Dmitar Zvonimir','Trpimir I.','Branimir','Muncimir'],['Koji je kralj povezan s papom Grgurom VII.?','Dmitar Zvonimir','Tomislav','Krešimir IV.','Stjepan Držislav'],['Koji je kralj prema predaji imao krunidbu u Solinu 1076.?','Dmitar Zvonimir','Tomislav','Petar Krešimir IV.','Stjepan Držislav'],['Koji je kralj povezan s Bašćanskom pločom iz kraja 11. ili početka 12. stoljeća?','Dmitar Zvonimir','Tomislav','Petar Krešimir IV.','Stjepan Držislav'],['Koji se vladar spominje na Bašćanskoj ploči?','Dmitar Zvonimir','Tomislav','Branimir','Stjepan Držislav'],['Koji je vladar povezan s crkvom sv. Lucije u Jurandvoru?','Dmitar Zvonimir','Petar Krešimir IV.','Tomislav','Muncimir'],['Koji je vladar bio kralj krajem 11. stoljeća?','Dmitar Zvonimir','Tomislav','Trpimir I.','Branimir'],['Koji je vladar bio kralj sredinom 11. stoljeća?','Petar Krešimir IV.','Zvonimir','Tomislav','Branimir'],['Koji je vladar bio kralj početkom 10. stoljeća?','Tomislav','Zvonimir','Krešimir IV.','Stjepan II.'],['Koji je vladar bio knez krajem 9. stoljeća?','Muncimir','Tomislav','Zvonimir','Krešimir IV.'],
['Koji je vladar poznat kao „dux Chroatorum“ u papinskim pismima?','Branimir','Zvonimir','Tomislav','Krešimir IV.'],['Koji je vladar bio povezan s papom Ivanom VIII.?','Branimir','Tomislav','Zvonimir','Krešimir IV.'],['Koji je vladar bio suvremenik pape Ivana VIII.?','Branimir','Tomislav','Zvonimir','Petar Krešimir IV.'],['Koji je vladar bio suvremenik pape Grgura VII.?','Dmitar Zvonimir','Branimir','Tomislav','Muncimir'],['Koji je vladar bio suvremenik bizantskog cara Bazilija II.?','Dmitar Zvonimir','Tomislav','Branimir','Trpimir I.'],['Koji je kralj povezan s bizantskim naslovima i utjecajem u Dalmaciji?','Stjepan Držislav','Branimir','Muncimir','Trpimir I.'],['Koji je vladar prema tradiciji dobio znakove kraljevske vlasti od Bizanta?','Stjepan Držislav','Zvonimir','Tomislav','Branimir'],['Koji je vladar imao sinove Svetoslava, Krešimira i Gojslava?','Stjepan Držislav','Tomislav','Zvonimir','Branimir'],['Koji se kralj povezuje s početkom 11. stoljeća?','Stjepan Držislav','Tomislav','Zvonimir','Krešimir IV.'],['Koji vladar se povezuje s prijelazom iz kneževine u kraljevstvo u hrvatskoj tradiciji?','Tomislav','Branimir','Muncimir','Trpimir I.'],
['Koji se kralj tradicionalno povezuje s krunom na spomeniku u Zagrebu?','Tomislav','Zvonimir','Krešimir IV.','Stjepan Držislav'],['Koji je vladar prikazan na Trgu kralja Tomislava u Zagrebu?','Tomislav','Zvonimir','Krešimir IV.','Stjepan Držislav'],['Koji se hrvatski kralj obilježava spomenikom ispred Glavnog kolodvora u Zagrebu?','Tomislav','Zvonimir','Krešimir IV.','Stjepan Držislav'],['Koji je vladar dao ime zagrebačkom Trgu kralja Tomislava?','Tomislav','Branimir','Zvonimir','Krešimir IV.'],['Koji kralj je povezan s Hrvatskom u 10. stoljeću?','Tomislav','Zvonimir','Krešimir IV.','Stjepan II.'],['Koji kralj je povezan s Hrvatskom u drugoj polovici 11. stoljeća?','Dmitar Zvonimir','Tomislav','Branimir','Muncimir'],['Koji kralj je povezan s Hrvatskom sredinom 11. stoljeća?','Petar Krešimir IV.','Tomislav','Branimir','Zvonimir'],['Koji knez je povezan s Hrvatskom u drugoj polovici 9. stoljeća?','Branimir','Tomislav','Zvonimir','Krešimir IV.'],['Koji knez je povezan s Hrvatskom početkom 9. stoljeća?','Trpimir I.','Branimir','Tomislav','Zvonimir'],['Koji vladar je povezan s ranom hrvatskom kneževinom?','Trpimir I.','Petar Krešimir IV.','Zvonimir','Stjepan Držislav'],
['Koji je vladar poznat po darovnici koja se smatra važnim izvorom za 9. stoljeće?','Trpimir I.','Tomislav','Zvonimir','Branimir'],['Koji je vladar povezan s Rižinicama?','Trpimir I.','Tomislav','Zvonimir','Branimir'],['Koji je vladar povezan s Bijaćima?','Trpimir I.','Branimir','Zvonimir','Tomislav'],['Koji je vladar povezan s Ninom u ranom srednjem vijeku?','Višeslav','Tomislav','Zvonimir','Krešimir IV.'],['Koji vladar je povezan s Ninskom biskupijom u ranoj hrvatskoj povijesti?','Višeslav','Branimir','Tomislav','Zvonimir'],['Koji je kralj povezan s crkvenim saborima u Splitu u 11. stoljeću?','Petar Krešimir IV.','Tomislav','Branimir','Muncimir'],['Koji je kralj bio suvremenik pape Nikole II.?','Petar Krešimir IV.','Tomislav','Branimir','Zvonimir'],['Koji je kralj bio suvremenik pape Aleksandra II.?','Dmitar Zvonimir','Tomislav','Branimir','Muncimir'],['Koji je kralj povezan s crkvenim reformama 11. stoljeća?','Dmitar Zvonimir','Tomislav','Trpimir I.','Branimir'],['Koji je kralj bio posljednji poznati vladar Trpimirovića prije personalne unije?','Stjepan II.','Tomislav','Zvonimir','Krešimir IV.'],
['Koji je kralj povezan s 1102. kao krajem samostalne kraljevske dinastije?','Stjepan II.','Tomislav','Zvonimir','Krešimir IV.'],['Koji je ugarski kralj povezan s hrvatskom krunom početkom 12. stoljeća?','Koloman','Ladislav','Bela IV.','Andrija II.'],['Koji ugarski kralj je povezan s Pacta conventa prema tradicionalnoj historiografiji?','Koloman','Bela IV.','Ladislav I.','Stjepan I.'],['Koji je kralj iz dinastije Arpadovića vladao Hrvatskom početkom 12. stoljeća?','Koloman','Karlo Robert','Ludovik I.','Matija Korvin'],['Koji kralj je dao Zlatnu bulu Gradecu?','Bela IV.','Koloman','Ludovik I.','Matija Korvin'],['Koji kralj je povezan s obnovom hrvatskih zemalja nakon tatarske provale?','Bela IV.','Koloman','Zvonimir','Stjepan Držislav'],['Koji ugarski kralj bio je otac Bele IV.?','Andrija II.','Koloman','Ladislav I.','Stjepan II.'],['Koji je kralj vladao u vrijeme tatarske provale 1242.?','Bela IV.','Koloman','Ludovik I.','Matija Korvin'],['Koji je kralj povezan s razdobljem Anžuvinaca u Hrvatskoj?','Ludovik I.','Koloman','Bela IV.','Matija Korvin'],['Koji je kralj poznat kao Ludovik Veliki?','Ludovik I.','Karlo Robert','Matija Korvin','Žigmund'],
['Koji kralj je povezan s bitkom na Krbavskom polju 1493. kao vladar Hrvatske?','Vladislav II. Jagelović','Matija Korvin','Ludovik I.','Žigmund'],['Koji kralj je vladao Hrvatskom u vrijeme Mohačke bitke 1526.?','Ludovik II. Jagelović','Vladislav II.','Matija Korvin','Ferdinand I.'],['Koji kralj je poginuo u Mohačkoj bitci 1526.?','Ludovik II.','Vladislav II.','Matija Korvin','Ferdinand I.'],['Koji je vladar izabran za hrvatskog kralja na saboru u Cetinu 1527.?','Ferdinand I. Habsburški','Ludovik II.','Matija Korvin','Bela IV.'],['Koji je kralj bio iz dinastije Habsburg?','Ferdinand I.','Koloman','Ludovik I.','Matija Korvin'],['Koji je kralj bio poznat kao „Crni kralj“?','Matija Korvin','Ludovik I.','Bela IV.','Koloman'],['Koji kralj je povezan s razvojem Zagreba kao slobodnog kraljevskog grada?','Bela IV.','Matija Korvin','Koloman','Ludovik II.'],['Koji je kralj povezan sa Zlatnom bulom iz 1242.?','Bela IV.','Koloman','Matija Korvin','Ludovik I.'],['Koji je kralj povezan s Anžuvinskom obnovom Hrvatske?','Karlo Robert','Bela IV.','Koloman','Matija Korvin'],['Koji kralj je bio otac Ludovika I.?','Karlo Robert','Bela IV.','Koloman','Matija Korvin']
]);

// Kulturna baština
window.PATRIA_EXTRA_QUESTIONS.kulturna_bastina=makeBank('kulturna_bastina',[
['Koji je spomenik poznat kao najstariji hrvatski glagoljski natpis velikog značenja?','Bašćanska ploča','Vinodolski zakonik','Istarski razvod','Povaljska listina'],['Gdje se nalazi Bašćanska ploča?','Jurandvor','Nin','Knin','Trogir'],['Koji je grad poznat po Eufrazijevoj bazilici?','Poreč','Pula','Rovinj','Zadar'],['Koji je grad poznat po Dioklecijanovoj palači?','Split','Dubrovnik','Trogir','Zadar'],['Koji je grad poznat po povijesnim zidinama i Stradunu?','Dubrovnik','Split','Zadar','Pula'],['Koji je grad poznat po katedrali sv. Jakova?','Šibenik','Trogir','Zadar','Split'],['Koji je grad poznat po povijesnoj jezgri i Kamerlengu?','Trogir','Šibenik','Pula','Dubrovnik'],['Koji je spomenik povezan s Vučedolskom kulturom?','Vučedolska golubica','Bašćanska ploča','Zlatna bula','Višeslavova krstionica'],['Koje pismo je snažno povezano s hrvatskom srednjovjekovnom kulturom?','Glagoljica','Ćirilica','Latinica','Runica'],['Koji je oblik glagoljice posebno poznat u hrvatskoj tradiciji?','Uglata glagoljica','Obla glagoljica','Bosanska glagoljica','Staroslavenska latinica'],
['Koji je grad povezan s Vinodolskim zakonikom?','Novi Vinodolski','Dubrovnik','Split','Zadar'],['Koji je grad povezan s Povaljskom listinom?','Brač','Hvar','Krk','Korčula'],['Koji je spomenik povezan s Jurandvorom?','Bašćanska ploča','Vinodolski zakonik','Istarski razvod','Povaljska listina'],['Koji je hrvatski lokalitet UNESCO baštine poznat po stećcima?','Stećci','Dubrovnik','Poreč','Trogir'],['Koji je lokalitet UNESCO baštine poznat po Starogradskom polju?','Stari Grad na Hvaru','Vis','Brač','Korčula'],['Koji je prirodni lokalitet UNESCO baštine poznat po sedrenim jezerima?','Plitvička jezera','Kornati','Velebit','Biokovo'],['Koji je hrvatski UNESCO lokalitet poznat po obrambenim zidinama?','Dubrovnik','Osijek','Karlovac','Senj'],['Koji je grad s povijesnom jezgrom UNESCO baština zajedno s Trogirem?','Split','Rijeka','Osijek','Varaždin'],['Koji je grad poznat po zadarskim obrambenim zidinama?','Zadar','Pula','Split','Dubrovnik'],
['Koja je tradicionalna viteška igra iz Sinja?','Sinjska alka','Moreška','Trka na prstenac','Kumpanija'],['Koja viteška igra tradicionalno se izvodi na Korčuli?','Moreška','Sinjska alka','Alka','Kumpanija'],['Koja se viteška igra održava u Barbanu?','Trka na prstenac','Sinjska alka','Moreška','Kumpanija'],['Koji je običaj povezan s Lastovom i karnevalom?','Pokladni običaji','Alka','Moreška','Trka na prstenac'],['Koja je tradicija povezana s Hvarom i procesijom „Za križem“?','Za križem','Alka','Moreška','Bećarac'],['Koja je tradicija zaštićena UNESCO-om povezana s dalmatinskim pjevanjem?','Klapsko pjevanje','Tamburaško pjevanje','Ganga','Ojkanje'],['Koja je tradicija zaštićena UNESCO-om povezana sa Slavonijom?','Bećarac','Klapsko pjevanje','Ojkanje','Ganga'],['Koja je tradicija poznata po kratkom i snažnom pjevanju u Dalmaciji?','Ojkanje','Bećarac','Klapsko pjevanje','Međimurska popevka'],['Koja je tradicija upisana na UNESCO popis povezana s Međimurjem?','Međimurska popevka','Bećarac','Klapsko pjevanje','Ojkanje'],['Koja je tradicija vezana uz izradu čipke na otoku Hvaru?','Paška čipka','Hvarska čipka od agave','Lepoglavska čipka','Svetomarska čipka'],
['Koja čipka se izrađuje od agave na Hvaru?','Hvarska čipka','Paška čipka','Lepoglavska čipka','Međimurska čipka'],['Koji je grad poznat po čipki od agave?','Hvar','Pag','Lepoglava','Samobor'],['Koji je grad poznat po paškoj čipki?','Pag','Hvar','Lepoglava','Dubrovnik'],['Koji je grad poznat po lepoglavskoj čipki?','Lepoglava','Pag','Hvar','Varaždin'],['Koji je oblik čipke izrađen od agave?','Hvarska čipka','Paška čipka','Lepoglavska čipka','Svetomarska čipka'],['Koja je tradicionalna igra povezana s dubrovačkim krajem?','Linđo','Moreška','Alka','Trka na prstenac'],['Koji je ples povezan s Dubrovnikom?','Linđo','Nijemo kolo','Moreška','Kolo'],['Koja tradicija je poznata kao ples bez glazbene pratnje?','Nijemo kolo','Linđo','Moreška','Alka'],['Koji je oblik tradicijskog pjevanja povezan s Dalmatinskom zagorom?','Ganga','Bećarac','Klapa','Međimurska popevka'],['Koji je običaj povezan s karnevalom u Rijeci?','Riječki karneval','Festa sv. Vlaha','Sinjska alka','Trka na prstenac'],
['Koji je dubrovački blagdan zaštitnika grada?','Festa sv. Vlaha','Tijelovo','Alka','Za križem'],['Koji je svetac zaštitnik Dubrovnika?','Sveti Vlaho','Sveti Duje','Sveti Donat','Sveti Marko'],['Koji je svetac zaštitnik Splita?','Sveti Duje','Sveti Vlaho','Sveti Juraj','Sveti Josip'],['Koji je grad poznat po procesiji sv. Vlaha?','Dubrovnik','Split','Zadar','Šibenik'],['Koji je grad poznat po procesiji „Za križem“?','Hvar','Korčula','Brač','Vis'],['Koji je hrvatski grad poznat po licitarskom srcu kao tradiciji?','Zagreb','Split','Dubrovnik','Rijeka'],['Koji je tradicijski ukras iz Hrvatskog zagorja?','Licitarsko srce','Alka','Moreška','Bašćanska ploča'],['Koja je tradicija povezana s drvenim dječjim igračkama Hrvatskog zagorja?','Tradicijske drvene igračke','Licitarsko srce','Paška čipka','Alka'],['Koje je mjesto posebno poznato po tradicijskim drvenim igračkama?','Marija Bistrica','Sinj','Pag','Dubrovnik'],['Koja je tradicija izrade drvenih igračaka povezana s Hrvatskim zagorjem?','Tradicijske drvene igračke','Paška čipka','Hvarska čipka','Moreška'],
['Koji je grad poznat po Muzeju krapinskih neandertalaca?','Krapina','Zagreb','Varaždin','Čakovec'],['Koji je arheološki lokalitet poznat po neandertalcima?','Hušnjakovo brdo','Vučedol','Salona','Narona'],['Koji je lokalitet poznat po Vučedolskoj kulturi?','Vučedol','Krapina','Salona','Nin'],['Koji je lokalitet bio antički glavni grad rimske provincije Dalmacije?','Salona','Narona','Pola','Andautonija'],['Gdje se nalazila antička Salona?','Solin','Split','Trogir','Klis'],['Koji antički grad leži blizu Metkovića?','Narona','Salona','Pola','Andautonija'],['Koji rimski grad je današnji Pula?','Pola','Salona','Narona','Andautonija'],['Koji rimski grad je današnji Zagreb?','Andautonija','Salona','Narona','Pola'],['Koji je antički lokalitet kod Varaždinskih Toplica?','Aquae Iasae','Salona','Narona','Pola'],['Koji je rimski naziv za Pulu?','Pola','Salona','Narona','Sirmium'],
['Koji je hrvatski lokalitet poznat po rimskom amfiteatru?','Pula','Split','Zadar','Trogir'],['Koji je rimski car dao izgraditi palaču u Splitu?','Dioklecijan','Konstantin','Trajan','Hadrijan'],['Koji je car povezan s palačom u Splitu?','Dioklecijan','August','Neron','Vespazijan'],['Koji je rimski car rođen u Saloni?','Dioklecijan','Trajan','August','Konstantin'],['Koji je rimski car rođen u okolici Sirmija, a povezan s Panonijom?','Probus','Dioklecijan','Trajan','Hadrijan'],['Koji je grad poznat po ranokršćanskom kompleksu Manastirine?','Solin','Pula','Zadar','Trogir'],['Koji je grad poznat po kompleksu Eufrazijeve bazilike?','Poreč','Rovinj','Pula','Umag'],['Koji je grad poznat po ranokršćanskim mozaicima u bazilici?','Poreč','Dubrovnik','Split','Šibenik'],['Koji je grad povezan s arheološkim lokalitetom Narona?','Vid kod Metkovića','Solin','Nin','Pula'],['Koji je lokalitet kod Metkovića poznat po Augusteumu?','Narona','Salona','Andautonija','Aquae Iasae'],
['Koji je spomenik važan za razvoj hrvatske pravne tradicije?','Vinodolski zakonik','Bašćanska ploča','Istarski razvod','Povaljska listina'],['Koji je pravni spomenik iz 1288.?','Vinodolski zakonik','Bašćanska ploča','Zlatna bula','Pacta conventa'],['Koji je dokument povezan s razgraničenjem Istre?','Istarski razvod','Vinodolski zakonik','Bašćanska ploča','Povaljska listina'],['Koji je dokument jedan od najvažnijih hrvatskih srednjovjekovnih pravnih tekstova?','Vinodolski zakonik','Judita','Planine','Ribanje'],['Koji je hrvatski srednjovjekovni tekst pisan glagoljicom?','Bašćanska ploča','Gundulićev Osman','Judita','Dundo Maroje'],['Koji je najpoznatiji hrvatski glagoljski misal?','Misal po zakonu rimskoga dvora','Missale Romanum','Lekcionar','Evangeliar'],['Koji je hrvatski prvotisak iz 1483.?','Misal po zakonu rimskoga dvora','Judita','Vinodolski zakonik','Istarski razvod'],['Koje je pismo korišteno u Misalu iz 1483.?','Glagoljica','Latinica','Ćirilica','Runica'],['Koja je godina tiskanja prvog hrvatskog misala?','1483.','1493.','1527.','1561.'],['Koji se grad često povezuje s tiskarskom djelatnošću Šimuna Kožičića Benje?','Rijeka','Zagreb','Split','Dubrovnik'],
['Koji je književni spomenik Marka Marulića dio hrvatske baštine?','Judita','Osman','Dubravka','Planine'],['Koji je književni spomenik Petra Zoranića?','Planine','Judita','Ribanje','Dundo Maroje'],['Koji je književni spomenik Petra Hektorovića?','Ribanje i ribarsko prigovaranje','Planine','Judita','Osman'],['Koji je književni spomenik Ivana Gundulića?','Dubravka','Judita','Planine','Ribanje'],['Koji je književni spomenik Marina Držića?','Dundo Maroje','Judita','Dubravka','Osman'],['Koji je barokni ep Ivana Gundulića?','Osman','Judita','Planine','Ribanje'],['Koji je hrvatski renesansni pisac autor „Ribanja“?','Petar Hektorović','Marko Marulić','Marin Držić','Petar Zoranić'],['Koji je hrvatski renesansni pisac autor „Planina“?','Petar Zoranić','Marin Držić','Marko Marulić','Ivan Gundulić'],['Koji je hrvatski renesansni pisac autor „Dunda Maroja“?','Marin Držić','Petar Hektorović','Marko Marulić','Ivan Gundulić'],['Koji je hrvatski renesansni pisac autor „Judite“?','Marko Marulić','Petar Zoranić','Marin Držić','Ivan Gundulić']
]);

// Katolička baština
window.PATRIA_EXTRA_QUESTIONS.katolicka_bastina=makeBank('katolicka_bastina',[
['Koji je blagdan poznat kao Tijelovo?','Svetkovina Presvetog Tijela i Krvi Kristove','Bogojavljenje','Blagovijest','Velika Gospa'],['Koji se blagdan slavi 15. kolovoza?','Uznesenje Marijino','Tijelovo','Svi sveti','Božić'],['Koji se blagdan slavi 1. studenoga?','Svi sveti','Dušni dan','Velika Gospa','Tijelovo'],['Koji se dan slavi 2. studenoga?','Dušni dan','Svi sveti','Tijelovo','Blagovijest'],['Koji se blagdan slavi 25. ožujka?','Blagovijest','Uskrs','Božić','Velika Gospa'],['Koji se blagdan slavi 6. siječnja?','Bogojavljenje','Tijelovo','Blagovijest','Duhovi'],['Koji se blagdan slavi 25. prosinca?','Božić','Uskrs','Bogojavljenje','Tijelovo'],['Koji blagdan slavi uskrsnuće Isusa Krista?','Uskrs','Božić','Duhovi','Tijelovo'],['Koji blagdan slavi silazak Duha Svetoga?','Duhovi','Uskrs','Božić','Tijelovo'],['Koji je blagdan posvećen Isusovu rođenju?','Božić','Uskrs','Bogojavljenje','Blagovijest'],
['Koje je hrvatsko nacionalno marijansko svetište?','Marija Bistrica','Sinj','Trsat','Aljmaš'],['Gdje se nalazi Marija Bistrica?','Hrvatsko zagorje','Istra','Dalmacija','Slavonija'],['Koje je svetište poznato kao Majka Božja Trsatska?','Trsat','Marija Bistrica','Sinj','Vepric'],['Gdje se nalazi Trsat?','Rijeka','Zagreb','Split','Dubrovnik'],['Koje je svetište povezano s Čudotvornom slikom Gospe Sinjske?','Sinj','Trsat','Marija Bistrica','Aljmaš'],['Koje je svetište povezano s Gospi od Sinja?','Sinj','Rijeka','Zagreb','Poreč'],['Koje se svetište nalazi kod Makarske?','Vepric','Trsat','Sinj','Aljmaš'],['Koje je svetište poznato kao Gospa od Utočišta u Aljmašu?','Aljmaš','Trsat','Marija Bistrica','Sinj'],['Koje je svetište u Istri poznato po Gospi od Mora?','Rovinj','Pula','Pazin','Motovun'],['Koje je svetište u Međimurju poznato po Majci Božjoj?','Sveti Martin na Muri','Marija Bistrica','Trsat','Sinj'],
['Tko je zaštitnik Dubrovnika?','Sveti Vlaho','Sveti Duje','Sveti Josip','Sveti Marko'],['Tko je zaštitnik Splita?','Sveti Duje','Sveti Vlaho','Sveti Donat','Sveti Juraj'],['Tko je zaštitnik Zagrebačke nadbiskupije?','Sveti Josip','Sveti Vlaho','Sveti Duje','Sveti Marko'],['Tko je zaštitnik Šibenika?','Sveti Jakov','Sveti Duje','Sveti Vlaho','Sveti Donat'],['Tko je zaštitnik Zadra?','Sveti Krševan','Sveti Vlaho','Sveti Duje','Sveti Josip'],['Tko je zaštitnik Rijeke?','Sveti Vid','Sveti Duje','Sveti Vlaho','Sveti Jakov'],['Tko je zaštitnik Varaždina?','Sveti Nikola','Sveti Josip','Sveti Vid','Sveti Marko'],['Tko je zaštitnik Osijeka?','Sveti Petar i Pavao','Sveti Vlaho','Sveti Duje','Sveti Vid'],['Tko je zaštitnik Vukovara?','Sveti Filip i Jakov','Sveti Vlaho','Sveti Josip','Sveti Nikola'],['Tko je zaštitnik Karlovca?','Sveti Josip','Sveti Vid','Sveti Duje','Sveti Vlaho'],
['Koja je katedrala sjedište Zagrebačke nadbiskupije?','Katedrala Uznesenja Blažene Djevice Marije','Katedrala sv. Duje','Katedrala sv. Jakova','Katedrala sv. Stošije'],['Koja je katedrala sjedište Splitsko-makarske nadbiskupije?','Katedrala sv. Duje','Zagrebačka katedrala','Katedrala sv. Jakova','Katedrala sv. Stošije'],['Koja je katedrala u Zadru posvećena sv. Stošiji?','Katedrala sv. Stošije','Katedrala sv. Duje','Katedrala sv. Jakova','Katedrala sv. Vida'],['Koja je katedrala u Šibeniku posvećena sv. Jakovu?','Katedrala sv. Jakova','Katedrala sv. Duje','Katedrala sv. Stošije','Katedrala sv. Vlaha'],['Koja je katedrala u Dubrovniku posvećena Uznesenju Marijinu?','Dubrovačka katedrala','Katedrala sv. Duje','Zagrebačka katedrala','Katedrala sv. Jakova'],['Koja je katedrala u Đakovu poznata po velikoj neoromaničkoj arhitekturi?','Katedrala sv. Petra','Katedrala sv. Duje','Katedrala sv. Jakova','Katedrala sv. Stošije'],['Koja je katedrala u Varaždinu posvećena Uznesenju Marijinu?','Varaždinska katedrala','Katedrala sv. Duje','Katedrala sv. Jakova','Katedrala sv. Stošije'],['Koja je crkva u Rijeci povezana s Majkom Božjom Trsatskom?','Bazilika Majke Božje Trsatske','Katedrala sv. Vida','Katedrala sv. Duje','Zagrebačka katedrala'],['Koja je riječ katedrala posvećena sv. Vidu?','Katedrala sv. Vida','Katedrala sv. Duje','Katedrala sv. Stošije','Katedrala sv. Jakova'],['Koji je zagrebački katedralni blagdan 15. kolovoza?','Uznesenje Blažene Djevice Marije','Sveti Duje','Sveti Vlaho','Sveti Marko'],
['Koji red ima snažnu povijesnu prisutnost u Hrvatskoj i poznat je po benediktinskim samostanima?','Benediktinci','Franjevci','Dominikanci','Isusovci'],['Koji red je snažno povezan s franjevačkim samostanima u Hrvatskoj?','Franjevci','Benediktinci','Karmelićani','Kartuzijanci'],['Koji red ima poznati samostan u Dubrovniku?','Franjevci','Karmelićani','Kartuzijanci','Trapisti'],['Koji red je osnovao samostan u Lepoglavi?','Paulini','Franjevci','Dominikanci','Isusovci'],['Koji red je povezan s Marijom Bistricom?','Cisterciti','Franjevci','Paulini','Dominikanci'],['Koji red je povezan s isusovačkom tradicijom u Zagrebu?','Isusovci','Benediktinci','Paulini','Karmelićani'],['Koji red je poznat po kontemplativnom životu i karmelskoj tradiciji?','Karmelićani','Franjevci','Dominikanci','Isusovci'],['Koji red je posebno povezan s propovijedanjem?','Dominikanci','Benediktinci','Karmelićani','Kartuzijanci'],['Koji red slijedi Pravilo sv. Benedikta?','Benediktinci','Franjevci','Dominikanci','Isusovci'],['Koji je red utemeljio sv. Franjo Asiški?','Franjevci','Dominikanci','Benediktinci','Isusovci'],
['Koji je svetac utemeljio franjevački red?','Sveti Franjo Asiški','Sveti Dominik','Sveti Benedikt','Sveti Ignacije'],['Koji je svetac utemeljio dominikanski red?','Sveti Dominik','Sveti Franjo','Sveti Benedikt','Sveti Ignacije'],['Koji je svetac utemeljio benediktinsku tradiciju?','Sveti Benedikt','Sveti Franjo','Sveti Dominik','Sveti Ignacije'],['Koji je svetac utemeljio Družbu Isusovu?','Sveti Ignacije Lojolski','Sveti Franjo','Sveti Dominik','Sveti Benedikt'],['Koji je svetac zaštitnik Hrvatske prema tradicionalnom štovanju?','Sveti Josip','Sveti Vlaho','Sveti Duje','Sveti Marko'],['Koji je papa 1994. proglasio svetog Josipa zaštitnikom Hrvatske?','Ivan Pavao II.','Ivan XXIII.','Pavao VI.','Benedikt XVI.'],['Koji je papa posjetio Hrvatsku 1994., 1998. i 2003.?','Ivan Pavao II.','Benedikt XVI.','Franjo','Pavao VI.'],['Koji je papa posjetio Hrvatsku 2011.?','Benedikt XVI.','Ivan Pavao II.','Franjo','Ivan XXIII.'],['Koji je papa posjetio Hrvatsku 1994.?','Ivan Pavao II.','Benedikt XVI.','Franjo','Pavao VI.'],['Koji je papa proglasio kardinala Stepinca blaženim 1998.?','Ivan Pavao II.','Benedikt XVI.','Pavao VI.','Franjo'],
['Gdje je blaženi Alojzije Stepinac rođen?','Brezarić','Zagreb','Krašić','Lepoglava'],['Gdje je blaženi Alojzije Stepinac umro?','Krašić','Zagreb','Brezarić','Lepoglava'],['Gdje je blaženi Alojzije Stepinac pokopan?','Zagrebačka katedrala','Krašić','Marija Bistrica','Lepoglava'],['Koji je kardinal bio zagrebački nadbiskup tijekom Drugog svjetskog rata?','Alojzije Stepinac','Franjo Kuharić','Josip Bozanić','Franjo Šeper'],['Koji je kardinal bio zagrebački nadbiskup od 1970-ih?','Franjo Kuharić','Alojzije Stepinac','Franjo Šeper','Josip Bozanić'],['Koji je hrvatski kardinal bio predsjednik Biskupske konferencije?','Franjo Kuharić','Alojzije Stepinac','Franjo Šeper','Josip Bozanić'],['Koji je hrvatski kardinal bio prefekt Kongregacije za nauk vjere?','Franjo Šeper','Franjo Kuharić','Alojzije Stepinac','Josip Bozanić'],['Koji je hrvatski kardinal zagrebački nadbiskup postao 1997.?','Josip Bozanić','Franjo Kuharić','Franjo Šeper','Alojzije Stepinac'],['Koji je hrvatski kardinal bio nadbiskup Splita i Makarske?','Sveti Duje nije kardinal','Franjo Kuharić','Josip Bozanić','Alojzije Stepinac'],['Koji je blagdan posebno povezan s hrvatskim marijanskim svetištima?','Velika Gospa','Tijelovo','Svi sveti','Bogojavljenje'],
['Koji je sakrament prvi nakon krštenja u katoličkoj inicijaciji?','Potvrda','Euharistija','Pomirenje','Bolesničko pomazanje'],['Koji je sakrament središnji u katoličkom bogoslužju?','Euharistija','Krštenje','Potvrda','Pomirenje'],['Koji je sakrament povezan s oproštenjem grijeha nakon krštenja?','Pomirenje','Potvrda','Euharistija','Ženidba'],['Koji je sakrament označava ulazak u kršćanski život?','Krštenje','Potvrda','Euharistija','Red svetog reda'],['Koji je sakrament za bolesne i nemoćne?','Bolesničko pomazanje','Potvrda','Pomirenje','Ženidba'],['Koji sakrament ženidbom povezuje muškarca i ženu?','Ženidba','Potvrda','Krštenje','Euharistija'],['Koji sakrament se prima za službu đakona, prezbitera i biskupa?','Red sveti','Ženidba','Potvrda','Pomirenje'],['Koja je najpoznatija molitva Gospodnja?','Oče naš','Zdravo Marijo','Slava Ocu','Vjerovanje'],['Koja molitva počinje riječima „Zdravo, Marijo“?','Zdravo Marijo','Oče naš','Vjerovanje','Slava Ocu'],['Koja molitva je temeljni iskaz kršćanske vjere?','Vjerovanje','Oče naš','Zdravo Marijo','Slava Ocu']
]);

// Jezik i književnost
window.PATRIA_EXTRA_QUESTIONS.jezik=makeBank('jezik',[
['Tko je napisao Juditu?','Marko Marulić','Marin Držić','Ivan Gundulić','Petar Hektorović'],['Tko je napisao Planine?','Petar Zoranić','Marko Marulić','Marin Držić','Ivan Gundulić'],['Tko je napisao Ribanje i ribarsko prigovaranje?','Petar Hektorović','Marko Marulić','Petar Zoranić','Marin Držić'],['Tko je napisao Dunda Maroja?','Marin Držić','Ivan Gundulić','Marko Marulić','Petar Zoranić'],['Tko je napisao Osmana?','Ivan Gundulić','Marko Marulić','Marin Držić','Petar Hektorović'],['Tko je napisao Dubravku?','Ivan Gundulić','Marin Držić','Marko Marulić','Petar Zoranić'],['Tko je napisao U registraturi?','Ante Kovačić','August Šenoa','Miroslav Krleža','Vjenceslav Novak'],['Tko je napisao Zlatarovo zlato?','August Šenoa','Ante Kovačić','Miroslav Krleža','Josip Kozarac'],['Tko je napisao Gospodu Glembajeve?','Miroslav Krleža','August Šenoa','Ante Kovačić','Vjenceslav Novak'],['Tko je napisao Posljednje Stipančiće?','Vjenceslav Novak','August Šenoa','Miroslav Krleža','Ante Kovačić'],
['Tko je napisao Kiklop?','Ranko Marinković','Miroslav Krleža','Tin Ujević','Vladimir Nazor'],['Tko je napisao Ruke?','Ranko Marinković','Antun Gustav Matoš','Tin Ujević','Dobriša Cesarić'],['Tko je napisao Povratak Filipa Latinovicza?','Miroslav Krleža','Ranko Marinković','Vjenceslav Novak','August Šenoa'],['Tko je napisao Na Drini ćuprija?','Ivo Andrić','Miroslav Krleža','Vladimir Nazor','August Šenoa'],['Tko je napisao Smrt Smail-age Čengića?','Ivan Mažuranić','Petar Preradović','August Šenoa','Ivan Gundulić'],['Tko je napisao Horvatovu pjesmu?','Ivan Mažuranić','Antun Gustav Matoš','Tin Ujević','Vladimir Nazor'],['Tko je napisao Hrvatsku domovinu?','Antun Mihanović','Ivan Mažuranić','Petar Preradović','August Šenoa'],['Tko je napisao pjesmu Horvatska domovina?','Antun Mihanović','Ivan Mažuranić','Tin Ujević','Vladimir Nazor'],['Tko je skladao melodiju hrvatske himne?','Josip Runjanin','Vatroslav Lisinski','Ivan pl. Zajc','Jakov Gotovac'],['Tko je napisao tekst hrvatske himne?','Antun Mihanović','Ivan Mažuranić','August Šenoa','Petar Preradović'],
['Koje je ime hrvatske himne?','Lijepa naša domovino','Hrvatska domovina','Moja domovina','Bože, čuvaj Hrvatsku'],['Tko je autor pjesme „Notturno“?','Antun Gustav Matoš','Tin Ujević','Dobriša Cesarić','Vladimir Nazor'],['Tko je napisao „Pobratimstvo lica u svemiru“?','Tin Ujević','Matoš','Cesarić','Nazor'],['Tko je napisao „Voćku poslije kiše“?','Dobriša Cesarić','Tin Ujević','Matoš','Nazor'],['Tko je napisao „Veli Jože“?','Vladimir Nazor','August Šenoa','Ivan Mažuranić','Miroslav Krleža'],['Tko je napisao „Priče iz davnine“?','Ivana Brlić-Mažuranić','Marija Jurić Zagorka','Jagoda Truhelka','Zlata Kolarić-Kišur'],['Tko je napisao „Šegrta Hlapića“?','Ivana Brlić-Mažuranić','Vladimir Nazor','August Šenoa','Mato Lovrak'],['Tko je napisao „Družbu Pere Kvržice“?','Mato Lovrak','Ivana Brlić-Mažuranić','Grigor Vitez','Vladimir Nazor'],['Tko je napisao „Vlak u snijegu“?','Mato Lovrak','Ivana Brlić-Mažuranić','Grigor Vitez','August Šenoa'],['Tko je napisao „Zlatarevo zlato“?','August Šenoa','Ante Kovačić','Josip Kozarac','Miroslav Krleža'],
['Koji je hrvatski književnik poznat kao otac hrvatske književnosti?','Marko Marulić','Marin Držić','Ivan Gundulić','August Šenoa'],['Koji je književni pravac obilježio August Šenou?','Realizam i romantizam','Barok','Modernizam','Avangarda'],['Koji je književni pravac povezan s Antunom Gustavom Matošem?','Moderna','Renesansa','Barok','Ilirizam'],['Koji je književni pravac prethodio moderni u 19. stoljeću?','Realizam','Postmodernizam','Avangarda','Simbolizam'],['Koji je književni pravac povezan s Ivanom Gundulićem?','Barok','Renesansa','Realizam','Moderna'],['Koji je književni pravac povezan s Marinom Držićem?','Renesansa','Barok','Realizam','Moderna'],['Koji je književni pravac povezan s Markom Marulićem?','Renesansa','Barok','Realizam','Moderna'],['Koji je književni pravac povezan s Ivanom Mažuranićem?','Romantizam','Renesansa','Barok','Postmodernizam'],['Koji je hrvatski književni preporod povezan s Ljudevitom Gajem?','Ilirski pokret','Moderna','Barok','Realizam'],['Koje su novine Ljudevita Gaja bile važne za preporod?','Novine Horvatzke','Obzor','Vijenac','Danica'],
['Kako se zvala Gajeva književna publikacija?','Danica','Vijenac','Obzor','Vienac'],['Koje je pismo uveo Ljudevit Gaj u hrvatski pravopisni sustav?','Gajica','Glagoljica','Ćirilica','Bosančica'],['Koji je pravopis povezan s Ljudevitom Gajem?','Gajica','Vukovica','Ilirica','Bosančica'],['Koji je događaj povezan s 1835. u hrvatskoj kulturi?','Pokretanje Novina Horvatzkih i Danice','Osnivanje HAZU','Osnivanje Sveučilišta','Tiskanje Judite'],['Koje je godine pokrenuta Danica?','1835.','1848.','1861.','1900.'],['Koji je jezik bio važan u hrvatskom narodnom preporodu?','Štokavsko-ijekavski hrvatski','Latinski','Njemački','Talijanski'],['Koji su govori hrvatskog standardnog jezika?','Štokavsko, čakavsko i kajkavsko narječje','Samo štokavsko','Samo čakavsko','Samo kajkavsko'],['Koje je narječje povezano s riječju „kaj“?','Kajkavsko','Čakavsko','Štokavsko','Torcija'],['Koje je narječje povezano s riječju „ča“?','Čakavsko','Kajkavsko','Štokavsko','Ikavsko'],['Koje je narječje povezano s riječju „što/šta“?','Štokavsko','Čakavsko','Kajkavsko','Glagoljsko'],
['Koji je hrvatski pisac napisao „Kolar“?','Slavko Kolar','Miroslav Krleža','Mato Lovrak','Vladimir Nazor'],['Koji je hrvatski pisac napisao „Breza“?','Slavko Kolar','August Šenoa','Ante Kovačić','Vjenceslav Novak'],['Koji je pisac napisao „Tena“?','Josip Kozarac','Slavko Kolar','August Šenoa','Mato Lovrak'],['Koji je pisac napisao „Prosjak Luka“?','August Šenoa','Josip Kozarac','Ante Kovačić','Vjenceslav Novak'],['Koji je pisac napisao „Camao“?','Antun Gustav Matoš','August Šenoa','Miroslav Krleža','Vladimir Nazor'],['Koji je pisac napisao „Cvijet sa raskršća“?','Antun Gustav Matoš','Tin Ujević','Dobriša Cesarić','Vladimir Nazor'],['Koji je pisac napisao „Juditu“?','Marko Marulić','Ivan Gundulić','Marin Držić','Petar Zoranić'],['Koji je pisac napisao „Dubravku“?','Ivan Gundulić','Marko Marulić','Marin Držić','Petar Hektorović'],['Koji je pisac napisao „Dunda Maroja“?','Marin Držić','Ivan Gundulić','Marko Marulić','Petar Zoranić'],['Koji je pisac napisao „Planine“?','Petar Zoranić','Marko Marulić','Marin Držić','Ivan Gundulić'],
['Koji je pisac napisao „Ribanje i ribarsko prigovaranje“?','Petar Hektorović','Petar Zoranić','Marko Marulić','Marin Držić'],['Koji je pisac napisao „Osman“?','Ivan Gundulić','Marin Držić','Marko Marulić','Petar Hektorović'],['Koji je hrvatski književnik bio i ban?','Ivan Mažuranić','August Šenoa','Tin Ujević','Mato Lovrak'],['Koji je hrvatski književnik bio i liječnik?','August Šenoa','Mato Lovrak','Ivan Mažuranić','Vladimir Nazor'],['Koji je hrvatski književnik bio pravnik i književni kritičar?','Antun Gustav Matoš','Marko Marulić','Marin Držić','Ivan Gundulić'],['Koji je književnik poznat po nadimku „Tin“?','Augustin Tin Ujević','Miroslav Krleža','Vladimir Nazor','Dobriša Cesarić'],['Koji je književnik poznat kao „A. G. Matoš“?','Antun Gustav Matoš','Ante Kovačić','August Šenoa','Ivan Mažuranić'],['Koji je književnik autor „Balada Petrice Kerempuha“?','Miroslav Krleža','Tin Ujević','August Šenoa','Vladimir Nazor'],['Koji je književnik autor „Hrvatskog boga Marsa“?','Miroslav Krleža','August Šenoa','Antun Gustav Matoš','Vladimir Nazor'],['Koji je književnik autor „Glembajevih“?','Miroslav Krleža','Ranko Marinković','August Šenoa','Vjenceslav Novak'],
['Koji je roman Augusta Šenoe smješten u Zagreb?','Zlatarovo zlato','U registraturi','Posljednji Stipančići','Tena'],['Koji je roman Ante Kovačića?','U registraturi','Zlatarovo zlato','Tena','Glembajevi'],['Koji je roman Vjenceslava Novaka?','Posljednji Stipančići','Zlatarovo zlato','U registraturi','Tena'],['Koji je roman Josipa Kozarca?','Tena','U registraturi','Zlatarovo zlato','Posljednji Stipančići'],['Koji je roman Miroslava Krleže?','Povratak Filipa Latinovicza','Tena','Zlatarovo zlato','U registraturi'],['Koji je roman Ranka Marinkovića?','Kiklop','Povratak Filipa Latinovicza','Tena','Zlatarovo zlato'],['Koji je roman Ivana Kozarca?','Đuka Begović','Tena','Kiklop','U registraturi'],['Koji je hrvatski književnik napisao „Đuku Begovića“?','Ivan Kozarac','Josip Kozarac','Mato Lovrak','Slavko Kolar'],['Koji je hrvatski književnik napisao „Tenu“?','Josip Kozarac','Ivan Kozarac','August Šenoa','Slavko Kolar'],['Koji je hrvatski književnik napisao „Brezu“?','Slavko Kolar','Ivan Kozarac','Josip Kozarac','August Šenoa'],
['Koji je hrvatski književni časopis pokrenuo August Šenoa?','Vijenac','Danica','Obzor','Kolo'],['Koji je časopis Matice hrvatske važan u hrvatskoj književnosti?','Vijenac','Danica','Novine Horvatzke','Vienac'],['Koji je književni časopis važan za hrvatsku modernu?','Vienac','Danica','Vijenac','Obzor'],['Koji je hrvatski književni jezik standardiziran na štokavskoj osnovi?','Da','Ne','Samo na čakavskoj','Samo na kajkavskoj'],['Koje narječje ima najrašireniju osnovu hrvatskog standardnog jezika?','Štokavsko','Čakavsko','Kajkavsko','Torcija'],['Koje pismo uz latinicu ima posebno mjesto u hrvatskoj kulturnoj baštini?','Glagoljica','Runica','Arapsko','Grčko'],['Koji je prvi hrvatski tiskani misal iz 1483. važan za jezik?','Misal po zakonu rimskoga dvora','Judita','Danica','Vinodolski zakonik'],['Koji je pisac prvi opsežniji hrvatski epistolarni i književni autor renesanse?','Marko Marulić','Marin Držić','Ivan Gundulić','Petar Hektorović'],['Koji je hrvatski jezikoslovac autor „Gramatike hrvatskoga jezika“ u preporodnom razdoblju?','Vjekoslav Babukić','Ljudevit Gaj','Bogoslav Šulek','Ivan Mažuranić'],['Koji je hrvatski leksikograf bio važan u 19. stoljeću?','Bogoslav Šulek','Marko Marulić','Ivan Gundulić','Miroslav Krleža']
]);

// Hrvatska glazba
window.PATRIA_EXTRA_QUESTIONS.glazba=makeBank('glazba',[
['Tko je skladao operu Nikola Šubić Zrinjski?','Ivan pl. Zajc','Vatroslav Lisinski','Jakov Gotovac','Boris Papandopulo'],['Tko je skladao operu Ero s onoga svijeta?','Jakov Gotovac','Ivan pl. Zajc','Vatroslav Lisinski','Ivo Tijardović'],['Tko je skladao Ljubav i zloba?','Vatroslav Lisinski','Ivan pl. Zajc','Jakov Gotovac','Blagoje Bersa'],['Koja je prva hrvatska nacionalna opera?','Ljubav i zloba','Ero s onoga svijeta','Nikola Šubić Zrinjski','Porin'],['Tko je skladao operu Porin?','Vatroslav Lisinski','Ivan pl. Zajc','Jakov Gotovac','Ivo Tijardović'],['Koji je skladatelj poznat po operi Nikola Šubić Zrinjski?','Ivan pl. Zajc','Vatroslav Lisinski','Jakov Gotovac','Boris Papandopulo'],['Koji je skladatelj poznat po operi Ero s onoga svijeta?','Jakov Gotovac','Vatroslav Lisinski','Ivan pl. Zajc','Boris Papandopulo'],['Koji je skladatelj povezan s hrvatskim narodnim preporodom?','Vatroslav Lisinski','Ivan pl. Zajc','Jakov Gotovac','Ivo Tijardović'],['Koji je skladatelj napisao „Vrag i njegov sin“?','Vatroslav Lisinski','Ivan pl. Zajc','Jakov Gotovac','Blagoje Bersa'],['Koji je hrvatski skladatelj bio važan za operu u 19. stoljeću?','Ivan pl. Zajc','Vatroslav Lisinski','Jakov Gotovac','Dora Pejačević'],
['Koja je tradicija pjevanja povezana s Dalmacijom?','Klapsko pjevanje','Bećarac','Međimurska popevka','Ojkanje'],['Koja je tradicija pjevanja povezana sa Slavonijom?','Bećarac','Klapa','Ganga','Ojkanje'],['Koja je tradicija pjevanja povezana s Međimurjem?','Međimurska popevka','Bećarac','Klapa','Ganga'],['Koji oblik pjevanja uključuje višeglasno pjevanje bez instrumenata?','Klapsko pjevanje','Bećarac','Tamburaško pjevanje','Ojkanje'],['Koji oblik pjevanja često ima šaljive stihove i povezuje se sa Slavonijom?','Bećarac','Klapa','Ganga','Ojkanje'],['Koji oblik pjevanja karakterizira specifičan način dugog pjevanja?','Ojkanje','Bećarac','Klapa','Međimurska popevka'],['Koji oblik pjevanja je tradicionalno vezan uz Dalmatinsku zagoru?','Ganga','Klapa','Bećarac','Međimurska popevka'],['Koji oblik pjevanja je dio UNESCO nematerijalne baštine?','Klapsko pjevanje','Pop-rock','Tamburaški orkestri','Jazz'],['Koja je hrvatska tradicija na UNESCO popisu povezana sa Slavonijom?','Bećarac','Klapa','Ganga','Ojkanje'],['Koja je hrvatska tradicija na UNESCO popisu povezana s Međimurjem?','Međimurska popevka','Bećarac','Klapa','Ganga'],
['Koja je skladateljica poznata kao jedna od najvažnijih hrvatskih skladateljica?','Dora Pejačević','Ivana Lang','Boris Papandopulo','Blagoje Bersa'],['Koji je hrvatski skladatelj poznat po djelima 20. stoljeća i baletima?','Boris Papandopulo','Vatroslav Lisinski','Ivan Zajc','Jakov Gotovac'],['Koji je skladatelj poznat po djelu Sunčana polja?','Blagoje Bersa','Vatroslav Lisinski','Jakov Gotovac','Ivan pl. Zajc'],['Koji je hrvatski skladatelj napisao operu „Oganj“?','Blagoje Bersa','Ivan pl. Zajc','Vatroslav Lisinski','Jakov Gotovac'],['Koji je hrvatski skladatelj bio važan u 20. stoljeću?','Boris Papandopulo','Vatroslav Lisinski','Ivan pl. Zajc','Ivan Gundulić'],['Koji je hrvatski skladatelj povezan s operom „Morana“?','Jakov Gotovac','Vatroslav Lisinski','Ivan pl. Zajc','Boris Papandopulo'],['Koji je hrvatski skladatelj skladao operu „Kamenik“?','Ivan pl. Zajc','Jakov Gotovac','Vatroslav Lisinski','Boris Papandopulo'],['Koji je skladatelj povezan s hrvatskim nacionalnim romantizmom?','Vatroslav Lisinski','Blagoje Bersa','Boris Papandopulo','Dora Pejačević'],['Koji je skladatelj poznat po operi „Nikola Šubić Zrinjski“?','Ivan pl. Zajc','Lisinski','Gotovac','Bersa'],['Koji je skladatelj poznat po operi „Porin“?','Vatroslav Lisinski','Zajc','Gotovac','Bersa'],
['Koji je glazbeni instrument posebno povezan sa slavonskom tradicijom?','Tamburica','Mandolina','Lutnja','Gusle'],['Koji instrument je tipičan za dalmatinske klape?','Glas','Tamburica','Gajde','Cimbal'],['Koji instrument je snažno povezan s istarskom tradicijom?','Istarski mih','Tamburica','Mandolina','Gusle'],['Koji je instrument poznat kao diple?','Tradicionalni puhački instrument','Gudački instrument','Udaraljka','Žičani instrument'],['Koji je instrument povezan s dubrovačkim linđom?','Mijeh i tradicijski instrumenti','Tamburica','Gajde','Harmonika'],['Koji je instrument karakterističan za sjeverozapadnu Hrvatsku?','Cimbule','Gusle','Mih','Diple'],['Koji instrument ima tipke i mijeh i raširen je u narodnoj glazbi?','Harmonika','Tamburica','Mandolina','Mih'],['Koji je žičani instrument tipičan za tamburašku glazbu?','Brač','Mih','Gajde','Diple'],['Koji tamburaški instrument je najdublji među osnovnim tamburama?','Berda','Brač','Bisernica','Čelo'],['Koji je najmanji tipični tamburaški instrument?','Bisernica','Berda','Brač','Čelo'],
['Koji festival tradicijske glazbe održava se u Đakovu?','Đakovački vezovi','Splitski festival','Dubrovačke ljetne igre','Varaždinske barokne večeri'],['Koji festival je poznat po klapskoj glazbi u Omišu?','Omiški festival klapa','Đakovački vezovi','Varaždinske barokne večeri','Splitski festival'],['Koji festival je posvećen baroknoj glazbi u Varaždinu?','Varaždinske barokne večeri','Omiški festival klapa','Splitski festival','Đakovački vezovi'],['Koji glazbeni festival se održava u Splitu?','Splitski festival','Omiški festival klapa','Varaždinske barokne večeri','Đakovački vezovi'],['Koji događaj je poznat po tradicionalnoj slavonskoj glazbi i folkloru?','Đakovački vezovi','Dubrovačke ljetne igre','Riječki karneval','Motovun Film Festival'],['Koji festival je povezan s klapama?','Omiški festival klapa','Varaždinske barokne večeri','Splitski festival','Đakovački vezovi'],['Koji festival je povezan s baroknom glazbom?','Varaždinske barokne večeri','Omiški festival','Splitski festival','Đakovački vezovi'],['Koji festival je povezan sa Splitom i popularnom glazbom?','Splitski festival','Omiški festival','Varaždinske barokne večeri','Đakovački vezovi'],['Koji festival je povezan s folklorom Slavonije?','Đakovački vezovi','Splitski festival','Omiški festival','Varaždinske barokne večeri'],['Koji događaj je poznat po dalmatinskim klapama?','Omiški festival klapa','Đakovački vezovi','Varaždinske barokne večeri','Splitski festival'],
['Koji hrvatski pjevač poznat je po pjesmi „Cesarica“?','Oliver Dragojević','Dino Dvornik','Gibonni','Arsen Dedić'],['Koji hrvatski glazbenik bio je poznat kao „kralj hrvatske zabavne glazbe“?','Oliver Dragojević','Arsen Dedić','Dino Dvornik','Mišo Kovač'],['Koji hrvatski kantautor napisao je mnoge pjesme i poznat je po šansoni?','Arsen Dedić','Oliver Dragojević','Dino Dvornik','Gibonni'],['Koji hrvatski glazbenik bio je poznat po elektroničkom funku i pjesmi „Afrika“?','Dino Dvornik','Oliver Dragojević','Arsen Dedić','Mišo Kovač'],['Koji hrvatski glazbenik poznat je po suradnjama s klapama i dalmatinskom popu?','Gibonni','Dino Dvornik','Oliver Dragojević','Arsen Dedić'],['Koji hrvatski pjevač poznat je po dugoj karijeri i nadimku Mišo?','Mišo Kovač','Oliver Dragojević','Arsen Dedić','Dino Dvornik'],['Koja je pjesma povezana s Oliverom Dragojevićem?','Cesarica','Afrika','Moderato cantabile','Moja domovina'],['Koji je glazbenik autor pjesme „Moderato cantabile“?','Arsen Dedić','Oliver Dragojević','Dino Dvornik','Gibonni'],['Koja je pjesma povezana s Mišom Kovačem?','Ostala si uvijek ista','Cesarica','Afrika','Libar'],['Koja je pjesma povezana s Gibonnijem?','Libar','Cesarica','Afrika','Moderato cantabile'],
['Koji je glazbeni žanr klapa najčešće?','Tradicionalno višeglasno pjevanje','Elektronička glazba','Jazz','Metal'],['Koji je glazbeni žanr bećerca?','Tradicionalna vokalna glazba','Opera','Jazz','Elektronika'],['Koji je glazbeni žanr tamburaške glazbe?','Tradicionalna instrumentalna i vokalna glazba','Opera','Rock','Elektronika'],['Koji je oblik glazbe povezan s liturgijom?','Crkvena glazba','Tambura','Klapa','Bećarac'],['Koji je oblik glazbe najčešće vezan uz mise?','Liturgijska glazba','Rock','Jazz','Elektronika'],['Koji je hrvatski crkveni skladatelj važan za liturgijsku glazbu?','Albe Vidaković','Ivan Zajc','Dino Dvornik','Gibonni'],['Koji je hrvatski glazbeni pedagog i skladatelj važan za zborsku glazbu?','Josip Štolcer Slavenski','Vatroslav Lisinski','Oliver Dragojević','Arsen Dedić'],['Koji je hrvatski skladatelj djelovao u 20. stoljeću i poznat je po folklornim elementima?','Josip Štolcer Slavenski','Ivan Zajc','Lisinski','Gotovac'],['Koji hrvatski skladatelj ima prezime Slavenski?','Josip Štolcer Slavenski','Boris Papandopulo','Blagoje Bersa','Ivan Zajc'],['Koji je hrvatski skladatelj poznat po zborskim djelima?','Josip Štolcer Slavenski','Dino Dvornik','Mišo Kovač','Gibonni'],
['Koji je hrvatski glazbeni festival održavan u Opatiji bio važan za popularnu glazbu?','Opatijski festival','Omiški festival','Splitski festival','Đakovački vezovi'],['Koji festival je važan za dalmatinsku popularnu pjesmu?','Splitski festival','Opatijski festival','Varaždinske večeri','Đakovački vezovi'],['Koji festival je važan za klapsku glazbu?','Omiški festival','Splitski festival','Opatijski festival','Đakovački vezovi'],['Koji festival je važan za baroknu glazbu?','Varaždinske barokne večeri','Omiški festival','Splitski festival','Opatijski festival'],['Koji festival je važan za folklor Slavonije?','Đakovački vezovi','Omiški festival','Splitski festival','Varaždinske večeri'],['Koji festival je vezan uz grad Opatiju?','Opatijski festival','Splitski festival','Omiški festival','Đakovački vezovi'],['Koji je glazbeni događaj vezan uz Varaždin?','Varaždinske barokne večeri','Splitski festival','Omiški festival','Đakovački vezovi'],['Koji je festival vezan uz Omiš?','Omiški festival klapa','Splitski festival','Opatijski festival','Đakovački vezovi'],['Koji je festival vezan uz Đakovo?','Đakovački vezovi','Varaždinske barokne večeri','Splitski festival','Omiški festival'],['Koji je festival vezan uz Split?','Splitski festival','Omiški festival','Opatijski festival','Varaždinske večeri']
]);

// Napomena: pitanja su podijeljena u dodatne banke kako bi se datoteke lakše održavale.
// Preostale kategorije koriste isti format i mogu se učitati bez promjene quiz enginea.
