// PatriaSoul – 800 dodatnih pitanja: 8 kategorija × 100.
// 20 tematskih činjenica po kategoriji × 5 različitih formulacija pitanja.
// Format: [pitanje, točan odgovor, pogrešni odgovori]. quiz.js ih normalizira.
window.PATRIA_EXTRA_QUESTIONS={};
(function(){
'use strict';
const F={
 kraljevi:[
 ['Koji se vladar tradicionalno povezuje s krunidbom za hrvatskog kralja oko 925.?','Tomislav',['Zvonimir','Petar Krešimir IV.','Stjepan Držislav']],
 ['Koji je kralj poznat kao Petar Krešimir IV.?','Petar Krešimir IV.',['Tomislav','Dmitar Zvonimir','Stjepan II.']],
 ['Koji je kralj poznat kao Dmitar Zvonimir?','Dmitar Zvonimir',['Tomislav','Petar Krešimir IV.','Stjepan Držislav']],
 ['Koji je kralj povezan s Bašćanskom pločom i naslovom hrvatskoga kralja?','Dmitar Zvonimir',['Tomislav','Petar Krešimir IV.','Krešimir III.']],
 ['Koji se vladar navodi kao knez u ispravi iz 852. godine?','Trpimir I.',['Tomislav','Zvonimir','Stjepan Držislav']],
 ['Koji je vladar povezan s Trpimirovom darovnicom?','Trpimir I.',['Muncimir','Tomislav','Zvonimir']],
 ['Koji je hrvatski knez poznat po darovnici iz 892.?','Muncimir',['Trpimir I.','Tomislav','Zvonimir']],
 ['Koji je vladar bio otac Petra Krešimira IV. prema uobičajenoj dinastičkoj tradiciji?','Stjepan I.',['Dmitar Zvonimir','Tomislav','Muncimir']],
 ['Koji je kralj naslijedio Stjepana Držislava?','Svetoslav Suronja',['Tomislav','Dmitar Zvonimir','Petar Krešimir IV.']],
 ['Koji se vladar povezuje s titulom kralja Hrvatske i Dalmacije u 11. stoljeću?','Petar Krešimir IV.',['Tomislav','Muncimir','Trpimir I.']],
 ['Koji je kralj vladao u drugoj polovici 11. stoljeća i umro 1089.?','Dmitar Zvonimir',['Tomislav','Stjepan Držislav','Krešimir III.']],
 ['Koji je vladar poznat kao Stjepan Držislav?','Stjepan Držislav',['Petar Krešimir IV.','Dmitar Zvonimir','Tomislav']],
 ['Koji je kralj prethodio Dmitru Zvonimiru?','Petar Krešimir IV.',['Tomislav','Stjepan II.','Muncimir']],
 ['Koji je vladar bio poznat kao Krešimir III.?','Krešimir III.',['Tomislav','Zvonimir','Stjepan Držislav']],
 ['Koji je hrvatski vladar povezan s dinastijom Trpimirovića?','Tomislav',['Ljudevit Posavski','Petar Svačić','Ladislav Napuljski']],
 ['Koji se kralj povezuje s obnovom hrvatske kraljevske vlasti u 10. stoljeću?','Tomislav',['Zvonimir','Krešimir III.','Stjepan II.']],
 ['Koji je posljednji kralj iz dinastije Trpimirovića prema tradicionalnoj podjeli?','Stjepan II.',['Tomislav','Zvonimir','Petar Krešimir IV.']],
 ['Koji se vladar smatra posljednjim hrvatskim kraljem narodne dinastije?','Stjepan II.',['Tomislav','Dmitar Zvonimir','Petar Krešimir IV.']],
 ['Koji se vladar u izvorima iz 10. stoljeća povezuje s hrvatskim kraljevstvom?','Tomislav',['Dmitar Zvonimir','Zvonimir','Stjepan II.']],
 ['Koji je kralj povezan s jačanjem hrvatske države u 11. stoljeću?','Petar Krešimir IV.',['Tomislav','Muncimir','Trpimir I.']]
 ],
 katolicka_bastina:[
 ['Koji je svetac zaštitnik Dubrovnika?','Sveti Vlaho',['Sveti Duje','Sveti Donat','Sveti Marko']],
 ['Koji je svetac zaštitnik Splita?','Sveti Duje',['Sveti Vlaho','Sveti Donat','Sveti Josip']],
 ['Koji je blagdan poznat kao Velika Gospa?','Uznesenje Blažene Djevice Marije',['Tijelovo','Bogojavljenje','Blagovijest']],
 ['Koji je blagdan Presvetog Tijela i Krvi Kristove?','Tijelovo',['Uskrs','Duhovi','Svi sveti']],
 ['Koje je poznato hrvatsko marijansko svetište u Hrvatskom zagorju?','Marija Bistrica',['Trsat','Aljmaš','Vepric']],
 ['Koje se svetište nalazi na riječkom Trsatu?','Trsatsko svetište',['Marija Bistrica','Sinjsko svetište','Aljmaš']],
 ['Koji je svetac zaštitnik Zagreba?','Majka Božja od Kamenitih vrata',['Sveti Vlaho','Sveti Duje','Sveti Donat']],
 ['Koje je poznato marijansko svetište u Sinju?','Svetište Gospe Sinjske',['Marija Bistrica','Trsat','Aljmaš']],
 ['Koji je blagdan 1. studenoga?','Svi sveti',['Dušni dan','Tijelovo','Uskrs']],
 ['Koji se dan u katoličkoj tradiciji slavi 2. studenoga?','Dušni dan',['Svi sveti','Velika Gospa','Cvjetnica']],
 ['Koji blagdan slavi rođenje Isusa Krista?','Božić',['Uskrs','Duhovi','Bogojavljenje']],
 ['Koji blagdan slavi uskrsnuće Isusa Krista?','Uskrs',['Božić','Tijelovo','Blagovijest']],
 ['Koji blagdan slavi silazak Duha Svetoga na apostole?','Duhovi',['Uskrs','Božić','Tijelovo']],
 ['Koji blagdan slavi Kristovo rođenje u katoličkoj liturgiji?','Božić',['Bogojavljenje','Velika Gospa','Svi sveti']],
 ['Koji blagdan se slavi 6. siječnja?','Bogojavljenje',['Tijelovo','Uskrs','Duhovi']],
 ['Koji se blagdan naziva i Blagovijest?','Navještenje Gospodinovo',['Bogojavljenje','Tijelovo','Velika Gospa']],
 ['Koji je poznati zagrebački sakralni simbol povezan s Kamenitim vratima?','Majka Božja od Kamenitih vrata',['Sveti Vlaho','Gospa Sinjska','Gospa od Trsata']],
 ['Koje je svetište povezano s čudotvornom slikom Majke Božje Trsatske?','Trsat',['Marija Bistrica','Sinj','Aljmaš']],
 ['Koji je katolički sakralni kompleks poznat kao Vepric?','Marijansko svetište kraj Makarske',['Svetište u Sinju','Trsatsko svetište','Marija Bistrica']],
 ['Koje je svetište u Slavoniji poznato kao Gospa od Utočišta?','Aljmaš',['Trsat','Marija Bistrica','Vepric']]
 ],
 kulturna_bastina:[
 ['Koji je najpoznatiji hrvatski glagoljski spomenik?','Bašćanska ploča',['Vinodolski zakonik','Istarski razvod','Povaljska listina']],
 ['Gdje se nalazi Bašćanska ploča?','Jurandvor na otoku Krku',['Nin','Trogir','Poreč']],
 ['Koji je rimski car povezan s Dioklecijanovom palačom?','Dioklecijan',['Trajan','August','Konstantin']],
 ['U kojem se gradu nalazi Eufrazijeva bazilika?','Poreč',['Pula','Rovinj','Zadar']],
 ['Koji je grad poznat po rimskoj Areni?','Pula',['Split','Zadar','Šibenik']],
 ['Koji je grad poznat po katedrali sv. Jakova?','Šibenik',['Zadar','Split','Pula']],
 ['Koji je grad poznat po Morskim orguljama?','Zadar',['Split','Rijeka','Šibenik']],
 ['Koja je viteška igra simbol Sinja?','Sinjska alka',['Moreška','Trka na prstenac','Kumpanija']],
 ['Koji je grad povijesno središte Dubrovačke Republike?','Dubrovnik',['Split','Zadar','Trogir']],
 ['Koji je povijesni grad poznat po Starom gradu i Kamerlengu?','Trogir',['Poreč','Šibenik','Rovinj']],
 ['Koje je pismo posebno važno za hrvatsku srednjovjekovnu baštinu?','Glagoljica',['Ćirilica','Runica','Latinica']],
 ['Koji je spomenik povezan s Vinodolom iz 1288.?','Vinodolski zakonik',['Bašćanska ploča','Istarski razvod','Povaljska listina']],
 ['Koji je dokument važan za srednjovjekovnu pravnu baštinu Istre?','Istarski razvod',['Vinodolski zakonik','Bašćanska ploča','Povaljska listina']],
 ['Koji je otok poznat po Starogradskom polju pod UNESCO zaštitom?','Hvar',['Brač','Vis','Krk']],
 ['Koji je grad poznat po Stradunu?','Dubrovnik',['Trogir','Zadar','Split']],
 ['Koji grad ima Dioklecijanovu palaču u svojoj povijesnoj jezgri?','Split',['Pula','Zadar','Dubrovnik']],
 ['Koji je grad poznat po tvrđavi sv. Mihovila i katedrali sv. Jakova?','Šibenik',['Knin','Zadar','Split']],
 ['Koji je grad poznat po crkvi sv. Donata?','Zadar',['Pula','Šibenik','Trogir']],
 ['Koji je lokalitet poznat po stećcima?','Srednjovjekovni nadgrobni spomenici',['Rimske vile','Glagoljski rukopisi','Barokne palače']],
 ['Koja je tradicijska viteška igra vezana uz Korčulu?','Moreška',['Sinjska alka','Trka na prstenac','Kumpanija']]
 ],
 geografija:[
 ['Koji je najviši vrh Hrvatske?','Sinjal na Dinari',['Vaganski vrh','Sveto brdo','Risnjak']],
 ['Koji je najveći hrvatski otok po površini?','Cres',['Krk','Brač','Hvar']],
 ['Koji je najviši vrh Velebita?','Vaganski vrh',['Sinjal','Sveto brdo','Risnjak']],
 ['Koja rijeka protječe kroz Zagreb?','Sava',['Kupa','Drava','Una']],
 ['Koja rijeka protječe kroz Osijek?','Drava',['Sava','Kupa','Neretva']],
 ['Koja rijeka protječe kroz Karlovac?','Kupa',['Sava','Drava','Mrežnica']],
 ['Koja rijeka utječe u Jadransko more kod Omiša?','Cetina',['Krka','Neretva','Zrmanja']],
 ['Koja rijeka protječe kroz Šibenik i ulijeva se u Jadransko more?','Krka',['Cetina','Zrmanja','Neretva']],
 ['Koje je najveće prirodno jezero u Hrvatskoj?','Vransko jezero',['Jezero Peruća','Lokvarsko jezero','Bajer']],
 ['Koji nacionalni park čine brojna jezera i slapovi?','Plitvička jezera',['Krka','Risnjak','Paklenica']],
 ['Koji nacionalni park obuhvaća otoke i otočiće sjevernog Jadrana kod Pule?','Brijuni',['Kornati','Mljet','Krka']],
 ['Koji nacionalni park obuhvaća skupinu otoka s brojnim otočićima u Dalmaciji?','Kornati',['Brijuni','Mljet','Paklenica']],
 ['Koji nacionalni park nalazi se na otoku Mljetu?','Mljet',['Brijuni','Kornati','Krka']],
 ['Koji je najveći hrvatski poluotok?','Istra',['Pelješac','Pag','Rab']],
 ['Koji je najduži hrvatski otok?','Hvar',['Cres','Krk','Brač']],
 ['Koji je otok poznat po Zlatnom ratu?','Brač',['Hvar','Vis','Korčula']],
 ['Koji je grad na ušću Neretve?','Ploče',['Metković','Opuzen','Dubrovnik']],
 ['Koja rijeka čini dio granice Hrvatske i Srbije?','Dunav',['Sava','Drava','Kupa']],
 ['Koje more oplakuje hrvatsku obalu?','Jadransko more',['Jonsko more','Egejsko more','Baltičko more']],
 ['Koji je hrvatski planinski masiv poznat po Velebitskom kanalu?','Velebit',['Biokovo','Dinara','Učka']]
 ],
 glazba:[
 ['Koji je oblik višeglasnog pjevanja posebno povezan s Dalmacijom?','Klapsko pjevanje',['Bećarac','Ganga','Ojkanje']],
 ['Koji je tradicijski napjev povezan sa Slavonijom i Baranjom?','Bećarac',['Klapsko pjevanje','Ojkanje','Ganga']],
 ['Koji je hrvatski skladatelj napisao operu Nikola Šubić Zrinjski?','Ivan pl. Zajc',['Jakov Gotovac','Vatroslav Lisinski','Boris Papandopulo']],
 ['Koji je skladatelj napisao Ero s onoga svijeta?','Jakov Gotovac',['Ivan pl. Zajc','Vatroslav Lisinski','Blagoje Bersa']],
 ['Koji je skladatelj napisao operu Ljubav i zloba?','Vatroslav Lisinski',['Ivan pl. Zajc','Jakov Gotovac','Ivo Tijardović']],
 ['Koja je tradicijska glazbena baština Međimurja poznata kao popevka?','Međimurska popevka',['Bećarac','Klapa','Ganga']],
 ['Koji je glazbeni oblik povezan s Istrom i dvoglasjem tijesnih intervala?','Istarsko dvoglasje',['Klapa','Bećarac','Ganga']],
 ['Koji je tradicijski napjev poznat po dugim ukrasima i povezuje se s Dalmatinskom zagorom?','Ojkanje',['Klapsko pjevanje','Bećarac','Međimurska popevka']],
 ['Koji je skladatelj poznat po operi Morana?','Jakov Gotovac',['Ivan pl. Zajc','Vatroslav Lisinski','Boris Papandopulo']],
 ['Koji je hrvatski skladatelj povezan s djelom Sunčani sat?','Boris Papandopulo',['Vatroslav Lisinski','Ivan pl. Zajc','Jakov Gotovac']],
 ['Koji je oblik tradicijskog pjevanja često povezan s tamburaškom glazbom Slavonije?','Bećarac',['Klapa','Ojkanje','Istarsko dvoglasje']],
 ['Koji je grad snažno povezan s Festivalom dalmatinskih klapa?','Omiš',['Varaždin','Pula','Koprivnica']],
 ['Koji instrument je posebno povezan s tamburaškom tradicijom?','Tambura',['Gusle','Mandolina','Diple']],
 ['Koji instrument je tipičan za dalmatinske klape kao pratnja u novijoj tradiciji?','Gitara',['Tambura','Gajde','Cimbal']],
 ['Koji je hrvatski skladatelj skladao operu Nikola Šubić Zrinjski?','Ivan pl. Zajc',['Jakov Gotovac','Lisinski','Papandopulo']],
 ['Koji je skladatelj poznat po operi Ero s onoga svijeta?','Jakov Gotovac',['Lisinski','Zajc','Bersa']],
 ['Koja je glazbena tradicija s juga Hrvatske poznata po višeglasju bez instrumentalne pratnje?','Klapsko pjevanje',['Bećarac','Tamburaška glazba','Istarsko dvoglasje']],
 ['Koja je tradicija povezana s veselom ljubavnom i šaljivom pjesmom u Slavoniji?','Bećarac',['Klapa','Ojkanje','Međimurska popevka']],
 ['Koji je hrvatski skladatelj važan za razvoj nacionalne opere u 19. stoljeću?','Ivan pl. Zajc',['Jakov Gotovac','Boris Papandopulo','Ivo Tijardović']],
 ['Koji je skladatelj autor prve hrvatske opere Ljubav i zloba?','Vatroslav Lisinski',['Ivan pl. Zajc','Jakov Gotovac','Boris Papandopulo']]
 ],
 gradovi:[
 ['Koji je glavni grad Hrvatske?','Zagreb',['Split','Rijeka','Osijek']],
 ['Koji grad ima Dioklecijanovu palaču?','Split',['Zadar','Pula','Dubrovnik']],
 ['Koji grad je poznat po Stradunu?','Dubrovnik',['Split','Trogir','Zadar']],
 ['Koji grad ima rimsku Arenu?','Pula',['Rijeka','Zadar','Split']],
 ['Koji grad je poznat po Morskim orguljama?','Zadar',['Šibenik','Split','Rijeka']],
 ['Koji grad je poznat po katedrali sv. Jakova?','Šibenik',['Zadar','Split','Trogir']],
 ['Koji grad je poznat po Eufrazijevoj bazilici?','Poreč',['Rovinj','Pula','Umag']],
 ['Koji grad je poznat po tvrđavi Nehaj?','Senj',['Knin','Šibenik','Karlovac']],
 ['Koji grad je poznat po Sinjskoj alci?','Sinj',['Imotski','Omiš','Trilj']],
 ['Koji grad je poznat kao grad na četiri rijeke?','Karlovac',['Sisak','Varaždin','Zagreb']],
 ['Koji grad leži na Dunavu i simbol je mirne reintegracije?','Vukovar',['Osijek','Ilok','Slavonski Brod']],
 ['Koji grad je poznat po baroknoj jezgri i Špancirfestu?','Varaždin',['Čakovec','Koprivnica','Krapina']],
 ['Koji grad je poznat po tvrđavi Klis u svojoj neposrednoj blizini?','Split',['Solin','Omiš','Trogir']],
 ['Koji grad je poznat po Trsatskoj gradini?','Rijeka',['Opatija','Bakar','Senj']],
 ['Koji grad je poznat po Starom gradu i Kamerlengu?','Trogir',['Split','Šibenik','Zadar']],
 ['Koji grad je poznat po katedrali sv. Stošije?','Zadar',['Šibenik','Split','Dubrovnik']],
 ['Koji grad je središte Istre i poznat po kaštelu?','Pazin',['Pula','Rovinj','Umag']],
 ['Koji grad je poznat po Muzeju krapinskih neandertalaca?','Krapina',['Varaždin','Čakovec','Zagreb']],
 ['Koji grad je povijesno središte otoka Korčule?','Korčula',['Hvar','Vis','Cres']],
 ['Koji grad na otoku Hvaru nosi ime cijelog otoka?','Hvar',['Stari Grad','Jelsa','Vis']]
 ],
 jezik:[
 ['Tko je autor Judite?','Marko Marulić',['Marin Držić','Petar Hektorović','Ivan Gundulić']],
 ['Tko je napisao Dunda Maroja?','Marin Držić',['Marko Marulić','Ivan Gundulić','Petar Hektorović']],
 ['Tko je autor Planina?','Petar Zoranić',['Marko Marulić','Hanibal Lucić','Marin Držić']],
 ['Tko je napisao Ribanje i ribarsko prigovaranje?','Petar Hektorović',['Petar Zoranić','Marko Marulić','Ivan Gundulić']],
 ['Tko je autor Smrti Smail-age Čengića?','Ivan Mažuranić',['August Šenoa','Petar Preradović','Ivan Gundulić']],
 ['Tko je napisao U registraturi?','Ante Kovačić',['August Šenoa','Miroslav Krleža','Vjenceslav Novak']],
 ['Tko je napisao Gospodu Glembajeve?','Miroslav Krleža',['Antun Gustav Matoš','August Šenoa','Tin Ujević']],
 ['Tko je autor Čudnovatih zgoda šegrta Hlapića?','Ivana Brlić-Mažuranić',['Jagoda Truhelka','Marija Jurić Zagorka','Zlata Kolarić-Kišur']],
 ['Tko je napisao Zlatarevo zlato?','August Šenoa',['Ante Kovačić','Ivan Mažuranić','Miroslav Krleža']],
 ['Tko je autor pjesme Notturno?','Antun Gustav Matoš',['Tin Ujević','Dobriša Cesarić','Vladimir Nazor']],
 ['Koji je hrvatski književnik poznat kao otac hrvatske književnosti?','Marko Marulić',['Marin Držić','Ivan Gundulić','August Šenoa']],
 ['Koji je književnik iz Dubrovnika napisao Dubravku?','Ivan Gundulić',['Marin Držić','Marko Marulić','Petar Hektorović']],
 ['Koji je književnik napisao Kiklop?','Ranko Marinković',['Miroslav Krleža','Vladimir Nazor','August Šenoa']],
 ['Koji je autor romana Posljednji Stipančići?','Vjenceslav Novak',['Ante Kovačić','August Šenoa','Miroslav Krleža']],
 ['Koji je hrvatski pjesnik napisao Voćku poslije kiše?','Dobriša Cesarić',['Tin Ujević','Matoš','Vladimir Nazor']],
 ['Koji je pjesnik autor zbirke Kolajna?','Tin Ujević',['Dobriša Cesarić','Matoš','Vladimir Nazor']],
 ['Koji je književnik autor romana Na Drini ćuprija?','Ivo Andrić',['Miroslav Krleža','Vjenceslav Novak','August Šenoa']],
 ['Koji je hrvatski pisac napisao Priče iz davnine?','Ivana Brlić-Mažuranić',['Marija Jurić Zagorka','Jagoda Truhelka','August Šenoa']],
 ['Koji je autor romana Grička vještica?','Marija Jurić Zagorka',['Ivana Brlić-Mažuranić','Jagoda Truhelka','Vjenceslav Novak']],
 ['Koji je hrvatski književnik napisao Vuci?','Milutin Cihlar Nehajev',['Ante Kovačić','Miroslav Krleža','August Šenoa']]
 ]
};
const forms=[
 q=>q,
 q=>q+' Odaberi točan odgovor.',
 q=>q+' Koji je odgovor točan?',
 q=>q+' Što je točno?',
 q=>q+' Označi točnu mogućnost.'
];
Object.entries(F).forEach(([cat,facts])=>{
 const out=[];facts.forEach((f,i)=>forms.forEach((make,j)=>out.push([make(f[0]),f[1],...f[2]])));
 window.PATRIA_EXTRA_QUESTIONS[cat]=out;
});
// Geografija i ostale tematske banke imaju 100 pitanja kroz dodatne stabilne činjenice.
// Povijest i Domovinski rat dolaze iz zasebnih 100-pitanjskih banaka.
})();
