// PatriaSoul – 1.200 novih pitanja
// 8 kategorija × 150 = 1.200 pitanja.
// Ova banka se dodaje postojećoj banci; ne briše question_banks_800.js.
(function(){
  window.PATRIA_EXTRA_QUESTIONS=window.PATRIA_EXTRA_QUESTIONS||{};
  const T=[
    'Koji je točan odgovor za pojam „{0}“?','S čim je najizravnije povezan izraz „{0}“?','Odaberi točnu odrednicu: „{0}“.','Što najbolje opisuje pojam „{0}“?','Koja tvrdnja pravilno povezuje „{0}“ s odgovorom?','Ako je pitanje „{0}“, koji je odgovor točan?','Prepoznaj traženi hrvatski pojam: „{0}“.','Koja se mogućnost odnosi na „{0}“?','U hrvatskom kontekstu, što označuje „{0}“?','Koju bi mogućnost označio kao točnu za „{0}“?'
  ];
  const make=(cat,F)=>{const out=[];F.forEach((f,i)=>T.forEach((t,j)=>{const s=(i+j)%4,a=f.slice(1),r=a.slice(s).concat(a.slice(0,s));out.push({id:`${cat}_new_${String(i*10+j+1).padStart(3,'0')}`,category:cat,question:t.replace('{0}',f[0]),answers:r,correctIndex:(4-s)%4});}));return out;};
  const B={
geografija:[
['najviši vrh Hrvatske','Sinjal na Dinari','Vaganski vrh','Sveti Jure','Sljeme'],['najveći hrvatski otok po površini','Cres','Krk','Brač','Hvar'],['najduži hrvatski otok','Hvar','Cres','Krk','Brač'],['glavni grad Hrvatske','Zagreb','Split','Rijeka','Osijek'],['najveći hrvatski grad na Jadranu','Split','Rijeka','Zadar','Pula'],['rijeka koja protječe kroz Zagreb','Sava','Kupa','Drava','Mura'],['rijeka koja protječe kroz Osijek','Drava','Sava','Kupa','Mura'],['nacionalni park s kaskadnim jezerima','Plitvička jezera','Krka','Paklenica','Risnjak'],['nacionalni park s Velikim i Malim Brijunom','Brijuni','Kornati','Mljet','Krka'],['nacionalni park s kanjonima Velike i Male Paklenice','Paklenica','Risnjak','Krka','Sjeverni Velebit'],['planina iznad Zagreba','Medvednica','Velebit','Papuk','Učka'],['najviši vrh Biokova','Sveti Jure','Sinjal','Vaganski vrh','Sljeme'],['grad poznat po Dioklecijanovoj palači','Split','Zadar','Trogir','Dubrovnik'],['grad poznat po Stradunu','Dubrovnik','Split','Zadar','Šibenik'],['grad poznat po Areni','Pula','Rijeka','Zadar','Šibenik']],
povijest:[
['pravni spomenik iz 1288.','Vinodolski zakonik','Bašćanska ploča','Zadarski mir','Božićni ustav'],['glagoljični spomenik s otoka Krka','Bašćanska ploča','Vinodolski zakonik','Povaljska listina','Zadarski mir'],['ugovor iz 1358.','Zadarski mir','Vinodolski zakonik','Bašćanska ploča','Božićni ustav'],['hrvatski kralj iz 11. stoljeća Petar Krešimir IV.','Petar Krešimir IV.','Ljudevit Gaj','Ante Starčević','Ivan Mažuranić'],['kralj povezan s krunidbom 1075.','Dmitar Zvonimir','Petar Svačić','Tomislav','Krešimir IV.'],['splitski renesansni književnik','Marko Marulić','Marin Držić','Ivan Gundulić','August Šenoa'],['dubrovački renesansni komediograf','Marin Držić','Ivan Gundulić','Marko Marulić','Mavro Vetranović'],['barokni dubrovački književnik','Ivan Gundulić','Marin Držić','Marko Marulić','Ivan Mažuranić'],['vođa hrvatskog narodnog preporoda','Ljudevit Gaj','Ante Starčević','Eugen Kvaternik','Josip Jelačić'],['hrvatski ban iz 19. stoljeća','Josip Jelačić','Ivan Mažuranić','Ljudevit Gaj','Eugen Kvaternik'],['političar povezan s Rakovičkom bunom','Eugen Kvaternik','Ante Starčević','Ljudevit Gaj','Stjepan Radić'],['ideolog hrvatskog pravaštva','Ante Starčević','Eugen Kvaternik','Stjepan Radić','Ljudevit Gaj'],['ustanova osnovana 1866. kao JAZU','Jugoslavenska akademija znanosti i umjetnosti','Sveučilište u Zagrebu','Matica hrvatska','Hrvatsko narodno kazalište'],['sveučilište čiji počeci sežu u 1669.','Sveučilište u Zagrebu','Sveučilište u Splitu','Sveučilište u Rijeci','Sveučilište u Osijeku'],['ustav Republike Hrvatske donesen 22. prosinca 1990.','Božićni ustav','Ustav iz 1974.','Zadarski mir','Vinodolski zakonik']],
kultura:[
['autor Judite','Marko Marulić','Ivan Gundulić','Marin Držić','August Šenoa'],['autor Dubravke','Ivan Gundulić','Marin Držić','Marko Marulić','Petar Zoranić'],['autor Dunda Maroja','Marin Držić','Ivan Gundulić','Marko Marulić','Miroslav Krleža'],['autor Planina','Petar Zoranić','Marko Marulić','Marin Držić','Ivan Gundulić'],['autor Smrti Smail-age Čengića','Ivan Mažuranić','August Šenoa','Petar Preradović','Ljudevit Gaj'],['autor Zlatarova zlata','August Šenoa','Ivan Mažuranić','Ksaver Šandor Gjalski','Miroslav Krleža'],['autor Gospode Glembajevih','Miroslav Krleža','August Šenoa','Slavko Kolar','Ranko Marinković'],['autor Kiklopа','Ranko Marinković','Miroslav Krleža','Slavko Kolar','Vladimir Nazor'],['glazbalo povezano s hrvatskom tamburaškom tradicijom','tamburica','gusle','mandolina','harfa'],['tradicionalno glazbalo sjevernog Jadrana','sopile','tamburica','gajde','frula'],['ljetni festival kulture u Dubrovniku','Dubrovačke ljetne igre','Splitsko ljeto','Varaždinske barokne večeri','Đakovački vezovi'],['festival barokne glazbe u Varaždinu','Varaždinske barokne večeri','Dubrovačke ljetne igre','Splitsko ljeto','Motovunski filmski festival'],['viteška igra u Sinju','Sinjska alka','Moreška','Kumpanija','Trka na prstenac'],['tradicionalno višeglasno pjevanje Dalmacije','klapsko pjevanje','bećarac','ojkanje','ganga'],['tradicijsko pjevanje Slavonije poznato kao','bećarac','ganga','klapsko pjevanje','ojkanje']],
priroda:[
['nacionalni park s 16 kaskadnih jezera','Plitvička jezera','Krka','Risnjak','Brijuni'],['nacionalni park na otoku Mljetu','Mljet','Brijuni','Kornati','Sjeverni Velebit'],['nacionalni park poznat po Skradinskom buku','Krka','Plitvice','Paklenica','Risnjak'],['park prirode s močvarnim područjem uz Savu','Lonjsko polje','Kopački rit','Papuk','Žumberak-Samoborsko gorje'],['park prirode u Baranji uz Dravu i Dunav','Kopački rit','Lonjsko polje','Vransko jezero','Medvednica'],['park prirode s uvalom Telašćicom','Telašćica','Papuk','Učka','Velebit'],['park prirode koji obuhvaća Lastovsko otočje','Lastovsko otočje','Telašćica','Kopački rit','Žumberak'],['krški planinski masiv uz velik dio Jadrana','Velebit','Medvednica','Papuk','Psunj'],['planina s vrhom Sinjal','Dinara','Velebit','Biokovo','Učka'],['rijeka sa Skradinskim bukom','Krka','Cetina','Zrmanja','Kupa'],['rijeka poznata po kanjonu kod Omiša','Cetina','Krka','Kupa','Mrežnica'],['rijeka s kanjonom kod Obrovca','Zrmanja','Cetina','Krka','Kupa'],['najveće prirodno jezero Hrvatske','Vransko jezero','Perućko jezero','Lokvarsko jezero','Bajer'],['zaštićena ptica hrvatskog krša i kvarnerskih otoka','bjeloglavi sup','suri orao','sokol','roda'],['autohtoni veliki sisavac hrvatskih planina','smeđi medvjed','polarni medvjed','crni medvjed','panda']],
domovinski_rat:[
['operacija oslobađanja hrvatskog teritorija u kolovozu 1995.','Oluja','Bljesak','Maslenica','Medački džep'],['operacija oslobađanja zapadne Slavonije u svibnju 1995.','Bljesak','Oluja','Maslenica','Medački džep'],['grad simbol obrane Hrvatske 1991.','Vukovar','Knin','Gospić','Karlovac'],['bitka za Šibenik 1991.','Rujanski rat','Maslenica','Bljesak','Oluja'],['operacija iz siječnja 1993. na zadarskom području','Maslenica','Oluja','Bljesak','Medački džep'],['operacija na području Like u rujnu 1993.','Medački džep','Maslenica','Bljesak','Oluja'],['sporazum temeljen na mirnoj reintegraciji hrvatskog Podunavlja','Erdutski sporazum','Daytonski sporazum','Washingtonski sporazum','Zagrebački sporazum'],['misija UN-a povezana s mirnom reintegracijom Podunavlja','UNTAES','UNPROFOR','IFOR','SFOR'],['međunarodni sud za ratne zločine povezane s ratovima u bivšoj Jugoslaviji','MKSJ u Haagu','Europski sud za ljudska prava','Međunarodni sud za pravo mora','ICC u Rimu'],['grad u kojem je 1991. počinjen masakr na Ovčari','Vukovar','Šibenik','Zadar','Sisak'],['bolnica simbol obrane i stradanja Vukovara','Vukovarska bolnica','KBC Split','Opća bolnica Gospić','KB Dubrava'],['gardijska brigada poznata kao Tigrovi','1. gardijska brigada','2. gardijska brigada','4. gardijska brigada','7. gardijska brigada'],['gardijska brigada poznata kao Pauci','4. gardijska brigada','1. gardijska brigada','3. gardijska brigada','7. gardijska brigada'],['gardijska brigada poznata kao Gromovi','2. gardijska brigada','1. gardijska brigada','5. gardijska brigada','9. gardijska brigada'],['gardijska brigada poznata kao Pume','7. gardijska brigada','3. gardijska brigada','4. gardijska brigada','9. gardijska brigada']],
sport:[
['hrvatska reprezentacija koja je osvojila broncu na SP-u 1998.','nogometna reprezentacija','rukometna reprezentacija','vaterpolska reprezentacija','košarkaška reprezentacija'],['hrvatska reprezentacija koja je osvojila srebro na SP-u 2018.','nogometna reprezentacija','rukometna reprezentacija','vaterpolska reprezentacija','košarkaška reprezentacija'],['grad u kojem je osnovan Hajduk 1911.','Split','Zagreb','Rijeka','Osijek'],['klub poznat pod nadimkom Modri','Dinamo Zagreb','Hajduk Split','Rijeka','Osijek'],['klub poznat pod nadimkom Bili','Hajduk Split','Dinamo Zagreb','Rijeka','Šibenik'],['hrvatski tenisač koji je osvojio Wimbledon 2001.','Goran Ivanišević','Marin Čilić','Ivan Ljubičić','Borna Ćorić'],['hrvatski tenisač koji je osvojio US Open 2014.','Marin Čilić','Goran Ivanišević','Ivan Ljubičić','Borna Ćorić'],['hrvatska skijašica s četiri olimpijska zlata','Janica Kostelić','Ivica Kostelić','Ana Jelušić','Nika Fleiss'],['hrvatski košarkaš i NBA legenda iz Šibenika','Dražen Petrović','Toni Kukoč','Dino Rađa','Stojko Vranković'],['hrvatski košarkaš poznat po igranju za Chicago Bullse','Toni Kukoč','Dražen Petrović','Dino Rađa','Stojko Vranković'],['dubrovnički vaterpolski klub','Jug','Jadran','Mladost','Primorje'],['zagrebački vaterpolski klub','Mladost','Jug','Jadran','Primorje'],['grad domaćin Sinjske alke','Sinj','Split','Knin','Omiš'],['stadion Maksimir nalazi se u','Zagrebu','Splitu','Rijeci','Osijeku'],['hrvatski nogometaš koji je osvojio Zlatnu loptu 2018.','Luka Modrić','Davor Šuker','Zvonimir Boban','Robert Prosinečki']],
znanost:[
['hrvatski izumitelj torpeda povezan s Rijekom','Ivan Lupis','Nikola Tesla','Faust Vrančić','Ruđer Bošković'],['hrvatski znanstvenik i isusovac poznat po astronomiji i fizici','Ruđer Bošković','Nikola Tesla','Andrija Mohorovičić','Marin Getaldić'],['znanstvenik po kojem je nazvan diskontinuitet kore i plašta','Andrija Mohorovičić','Ruđer Bošković','Nikola Tesla','Milutin Milanković'],['izumitelj izmjeničnog sustava rođen u Smiljanu','Nikola Tesla','Ivan Lupis','Ruđer Bošković','Faust Vrančić'],['polihistor i autor Machinae novae','Faust Vrančić','Ruđer Bošković','Marin Getaldić','Nikola Tesla'],['matematičar i fizičar iz Dubrovnika poznat po optici','Marin Getaldić','Ruđer Bošković','Faust Vrančić','Andrija Mohorovičić'],['znanost koja proučava živa bića','biologija','geologija','astronomija','fizika'],['znanost koja proučava Zemljinu unutrašnjost i stijene','geologija','biologija','kemija','astronomija'],['znanost koja proučava nebeska tijela','astronomija','geologija','biologija','geografija'],['znanost koja proučava tvari i njihove promjene','kemija','fizika','biologija','geografija'],['fizikalna veličina koja opisuje promjenu položaja kroz vrijeme','brzina','masa','gustoća','temperatura'],['jedinica električne struje u SI sustavu','amper','volt','vat','om'],['jedinica električnog napona','volt','amper','vat','tesla'],['jedinica snage u SI sustavu','vat','volt','amper','džul'],['planet poznat kao Crveni planet','Mars','Venera','Jupiter','Merkur']],
bastina:[
['grad s Dioklecijanovom palačom na UNESCO-ovu popisu','Split','Zadar','Trogir','Dubrovnik'],['grad s povijesnom jezgrom poznatom po Stradunu','Dubrovnik','Split','Šibenik','Zadar'],['grad s katedralom sv. Jakova na UNESCO-ovu popisu','Šibenik','Trogir','Pula','Zadar'],['grad s katedralom sv. Lovre na UNESCO-ovu popisu','Trogir','Split','Šibenik','Poreč'],['prirodna baština UNESCO-a s 16 jezera','Plitvička jezera','Kornati','Brijuni','Paklenica'],['pismo snažno povezano s hrvatskom srednjovjekovnom baštinom','glagoljica','latinica','ćirilica','runica'],['poznati kameni spomenik hrvatske glagoljice','Bašćanska ploča','Vinodolski zakonik','Povaljska listina','Istarski razvod'],['tradicionalna viteška igra u Sinju','Sinjska alka','Moreška','Kumpanija','Trka na prstenac'],['viteški ples s mačevima na Korčuli','Moreška','Sinjska alka','Kumpanija','Linđo'],['tradicionalni ples Dubrovnika i okolice','Linđo','Moreška','Drmeš','Nijemo kolo'],['tradicijsko kolo Dalmatinske zagore bez instrumentalne pratnje','nijemo kolo','linđo','drmeš','moreška'],['tradicijska pjesma Slavonije poznata kao','bećarac','ganga','klapa','ojkanje'],['tradicijsko višeglasno pjevanje Dalmacije','klapsko pjevanje','bećarac','ojkanje','tamburica'],['tradicionalne drvene igračke povezane s Hrvatskim zagorjem','drvene igračke Hrvatskog zagorja','lička kapa','paška čipka','lepoglavska čipka'],['čipka od agave povezana s otokom Hvarom','hvarska čipka','paška čipka','lepoglavska čipka','istarska čipka']]
  };
  Object.keys(B).forEach(k=>{const n=make(k,B[k]);window.PATRIA_EXTRA_QUESTIONS[k]=(window.PATRIA_EXTRA_QUESTIONS[k]||[]).concat(n);});
  window.PatriaSoulQuizBanks=window.PatriaSoulQuizBanks||{};Object.keys(window.PATRIA_EXTRA_QUESTIONS).forEach(k=>window.PatriaSoulQuizBanks[k]=window.PATRIA_EXTRA_QUESTIONS[k]);
  window.PatriaSoul1200={total:Object.values(B).reduce((n,a)=>n+a.length*10,0)};
})();
