// PatriaSoul – dopuna od 150 pitanja
// 10 kategorija × 15 pitanja. Svaki zapis je standardizirani format.
window.PATRIA_EXTRA_QUESTIONS = window.PATRIA_EXTRA_QUESTIONS || {};
const Q150 = {
  opce: [
    ['Koji je glavni grad Hrvatske?','Zagreb','Split','Rijeka','Osijek'],
    ['Koji je službeni jezik Republike Hrvatske?','hrvatski','slovenski','talijanski','mađarski'],
    ['Koji se blagdan slavi 15. kolovoza?','Velika Gospa','Tijelovo','Svi sveti','Uzašašće'],
    ['Koji je najveći hrvatski grad prema broju stanovnika?','Zagreb','Split','Rijeka','Osijek'],
    ['Koji je grad poznat po Dioklecijanovoj palači?','Split','Zadar','Pula','Dubrovnik'],
    ['Koji je grad poznat po Stradunu?','Dubrovnik','Trogir','Zadar','Šibenik'],
    ['Koji je grad poznat po Areni?','Pula','Rijeka','Zadar','Osijek'],
    ['Koji je otok poznat po Zlatnom ratu?','Brač','Hvar','Vis','Pag'],
    ['Koji je grad poznat kao grad na četiri rijeke?','Karlovac','Sisak','Osijek','Slunj'],
    ['Koji je nacionalni park poznat po sedrenim jezerima?','Plitvička jezera','Risnjak','Brijuni','Kornati'],
    ['Koji je hrvatski grad poznat po Morskim orguljama?','Zadar','Split','Pula','Rijeka'],
    ['Koji je grad središte Istre?','Pazin','Pula','Rovinj','Labin'],
    ['Koji je hrvatski grad poznat po katedrali sv. Jakova?','Šibenik','Split','Zadar','Trogir'],
    ['Koji je hrvatski grad poznat po Eufrazijevoj bazilici?','Poreč','Rovinj','Pula','Umag'],
    ['Koji je hrvatski grad poznat po tvrđavi Nehaj?','Senj','Knin','Gospić','Karlovac']
  ],
  povijest: [
    ['Koji se hrvatski vladar tradicionalno smatra prvim hrvatskim kraljem?','Tomislav','Zvonimir','Branimir','Krešimir III.'],
    ['Koji je hrvatski kralj okrunjen u Solinu 1076.?','Dmitar Zvonimir','Tomislav','Petar Svačić','Krešimir IV.'],
    ['Koji se knez spominje na Višeslavovoj krstionici?','Višeslav','Branimir','Trpimir','Domagoj'],
    ['Koji se vladar spominje na poznatom Branimirovu natpisu?','Branimir','Tomislav','Zvonimir','Mislav'],
    ['Koji je grad bio važno središte hrvatskih kraljeva?','Knin','Rijeka','Pula','Varaždin'],
    ['Tko je autor Judite?','Marko Marulić','Marin Držić','Ivan Gundulić','Petar Hektorović'],
    ['Tko je napisao Dunda Maroja?','Marin Držić','Marko Marulić','Ivan Mažuranić','August Šenoa'],
    ['Tko je napisao Osman?','Ivan Gundulić','Marko Marulić','Marin Držić','Petar Zoranić'],
    ['Tko je predvodio obranu Sigeta 1566.?','Nikola Šubić Zrinski','Petar Zrinski','Fran Krsto Frankopan','Ivan Drašković'],
    ['Koji je ban 1848. ukinuo kmetstvo u Hrvatskoj?','Josip Jelačić','Ivan Mažuranić','Ivan Drašković','Nikola Zrinski'],
    ['Kako se zove hrvatski narodni preporod u 19. stoljeću?','Ilirski pokret','Hanza','Tridentski pokret','Prosvjetiteljstvo'],
    ['Koji je dubrovački pisac napisao Dubravku?','Ivan Gundulić','Marin Držić','Marko Marulić','Junije Palmotić'],
    ['Koji je hrvatski književnik autor Smrti Smail-age Čengića?','Ivan Mažuranić','August Šenoa','Petar Preradović','Miroslav Krleža'],
    ['Koji je hrvatski književnik autor Zlatarova zlata?','August Šenoa','Ivan Mažuranić','Ksaver Šandor Gjalski','Ante Kovačić'],
    ['Koji je hrvatski književnik autor Balada Petrice Kerempuha?','Miroslav Krleža','August Šenoa','Tin Ujević','Vladimir Nazor']
  ],
  domovinski_rat: [
    ['Koji je grad postao simbol obrane Hrvatske 1991.?','Vukovar','Varaždin','Pula','Samobor'],
    ['Koja je operacija započela 4. kolovoza 1995.?','Oluja','Bljesak','Maslenica','Medački džep'],
    ['Koja je operacija provedena u svibnju 1995. u zapadnoj Slavoniji?','Bljesak','Oluja','Maslenica','Medački džep'],
    ['Koji je grad oslobođen u operaciji Bljesak?','Okučani','Knin','Vukovar','Petrinja'],
    ['Koji je grad oslobođen 5. kolovoza 1995.?','Knin','Osijek','Vukovar','Pakrac'],
    ['Kada se obilježava Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja?','5. kolovoza','18. studenoga','8. listopada','25. lipnja'],
    ['Kada se obilježava Dan sjećanja na žrtvu Vukovara i Škabrnje?','18. studenoga','5. kolovoza','22. lipnja','15. siječnja'],
    ['Kada je Hrvatska primljena u Ujedinjene narode?','22. svibnja 1992.','15. siječnja 1992.','8. listopada 1991.','5. kolovoza 1995.'],
    ['Koja je operacija iz 1993. povezana s područjem Maslenice?','Maslenica','Bljesak','Oluja','Medački džep'],
    ['Koji je grad teško stradao u Domovinskom ratu i poznat je po vodotornju?','Vukovar','Zadar','Osijek','Šibenik'],
    ['Koji je sporazum 1995. bio temelj mirne reintegracije hrvatskog Podunavlja?','Erdutski sporazum','Daytonski sporazum','Washingtonski sporazum','Zagrebački sporazum'],
    ['Koji je proces uslijedio nakon Erdutskog sporazuma?','mirna reintegracija','operacija Bljesak','operacija Maslenica','operacija Oluja'],
    ['Koji je grad bio jedno od ključnih mjesta obrane u istočnoj Slavoniji?','Vinkovci','Rovinj','Pula','Dubrovnik'],
    ['Koji je grad poznat po obrani šibenskog mosta 1991.?','Šibenik','Zadar','Split','Trogir'],
    ['Koja je operacija 1995. prethodila Oluji u zapadnoj Slavoniji?','Bljesak','Maslenica','Medački džep','Zima 94']
  ],
  geografija: [
    ['Koji je najviši vrh Hrvatske?','Sinjal na Dinari','Vaganski vrh','Sveti Jure','Sljeme'],
    ['Koji je najveći hrvatski otok po površini?','Cres','Krk','Brač','Hvar'],
    ['Koji je najduži hrvatski otok?','Hvar','Cres','Brač','Krk'],
    ['Koja je najduža rijeka koja cijelim tokom teče Hrvatskom?','Kupa','Sava','Drava','Dunav'],
    ['Koja rijeka protječe kroz Zagreb?','Sava','Kupa','Drava','Mura'],
    ['Koja rijeka protječe kroz Osijek?','Drava','Sava','Kupa','Mura'],
    ['Koja rijeka protječe kroz Karlovac?','Kupa','Sava','Drava','Dunav'],
    ['Koji je najveći hrvatski poluotok?','Istra','Pelješac','Pag','Kvarner'],
    ['Koji je grad na Dunavu poznat po Vukovarskom vodotornju?','Vukovar','Ilok','Osijek','Slavonski Brod'],
    ['Koji grad leži na ušću Neretve u more?','Ploče','Metković','Opuzen','Makarska'],
    ['Koji je grad poznat po kuli Kamerlengo?','Trogir','Split','Zadar','Šibenik'],
    ['Koji grad je poznat po Morskim orguljama?','Zadar','Pula','Rijeka','Dubrovnik'],
    ['Koji grad je središte Ličko-senjske županije?','Gospić','Senj','Otočac','Korenica'],
    ['Koji grad je središte Primorsko-goranske županije?','Rijeka','Opatija','Krk','Delnice'],
    ['Koji grad je središte Dubrovačko-neretvanske županije?','Dubrovnik','Metković','Ploče','Korčula']
  ],
  priroda: [
    ['Koji je najstariji nacionalni park u Hrvatskoj?','Plitvička jezera','Paklenica','Risnjak','Brijuni'],
    ['Koji nacionalni park obuhvaća Kornate?','Kornati','Brijuni','Mljet','Krka'],
    ['Koji nacionalni park obuhvaća velik dio otoka Mljeta?','Mljet','Brijuni','Kornati','Risnjak'],
    ['Koji nacionalni park poznat je po kanjonima Velike i Male Paklenice?','Paklenica','Risnjak','Krka','Sjeverni Velebit'],
    ['Koji nacionalni park nalazi se u Gorskom kotaru?','Risnjak','Kornati','Mljet','Brijuni'],
    ['Koji nacionalni park obuhvaća sjeverni Velebit?','Sjeverni Velebit','Paklenica','Risnjak','Krka'],
    ['Koji je park prirode poznat po močvarnom području Drave i Dunava?','Kopački rit','Papuk','Velebit','Učka'],
    ['Koji je park prirode poznat po poplavnim livadama uz Savu?','Lonjsko polje','Kopački rit','Biokovo','Medvednica'],
    ['Koja je najveća kopnena zvijer u Hrvatskoj?','smeđi medvjed','vuk','ris','divlja svinja'],
    ['Koja je velika mačka autohtona u hrvatskim šumama?','ris','lav','gepard','puma'],
    ['Koja je poznata ptica grabljivica povezana s kvarnerskim otocima?','bjeloglavi sup','ždral','roda','flamingo'],
    ['Koji nacionalni park poznat je po Skradinskom buku?','Krka','Paklenica','Plitvička jezera','Risnjak'],
    ['Koje je najveće prirodno jezero u Hrvatskoj?','Vransko jezero','Bajer','Lokvarsko jezero','Perućko jezero'],
    ['Koja planina dominira iznad Makarske?','Biokovo','Medvednica','Papuk','Učka'],
    ['Koja planina se proteže uz velik dio hrvatske obale?','Velebit','Papuk','Medvednica','Psunj']
  ],
  bastina: [
    ['Tko je autor Judite?','Marko Marulić','Marin Držić','Ivan Gundulić','Petar Hektorović'],
    ['Tko je napisao Dunda Maroja?','Marin Držić','Marko Marulić','Ivan Mažuranić','August Šenoa'],
    ['Tko je autor Osmana?','Ivan Gundulić','Marko Marulić','Marin Držić','Petar Zoranić'],
    ['Tko je napisao Ribanje i ribarsko prigovaranje?','Petar Hektorović','Marko Marulić','Ivan Gundulić','Marin Držić'],
    ['Koji je grad poznat po Eufrazijevoj bazilici?','Poreč','Rovinj','Pula','Umag'],
    ['Koji je grad poznat po katedrali sv. Jakova?','Šibenik','Trogir','Zadar','Split'],
    ['Koji je grad poznat po dubrovačkim zidinama?','Dubrovnik','Trogir','Split','Zadar'],
    ['Koji je grad poznat po Trsatskoj gradini?','Rijeka','Pula','Zadar','Šibenik'],
    ['Koji je grad poznat po baroknoj jezgri i Špancirfestu?','Varaždin','Koprivnica','Čakovec','Krapina'],
    ['Koja je viteška igra povezana sa Sinjem?','Sinjska alka','Moreška','Trka na prstenac','Linđo'],
    ['Koji ples je tradicionalno povezan s Dubrovnikom?','Linđo','Moreška','Nijemo kolo','Drmeš'],
    ['Koji ples s mačevima izvodi se na Korčuli?','Moreška','Linđo','Drmeš','Poskočica'],
    ['Koji je grad poznat po tradicionalnoj manifestaciji Đakovački vezovi?','Đakovo','Vinkovci','Osijek','Požega'],
    ['Koji je grad domaćin Vinkovačkih jeseni?','Vinkovci','Đakovo','Vukovar','Slavonski Brod'],
    ['Koji je istarski grad poznat po Aleji glagoljaša u svojoj blizini?','Roč','Pula','Pazin','Labin']
  ],
  glagoljica: [
    ['Koje je pismo posebno povezano sa srednjovjekovnom hrvatskom kulturom?','glagoljica','gotica','hebrejsko pismo','runica'],
    ['Kako se zove prvi hrvatski tiskani misal iz 1483.?','Misal po zakonu rimskoga dvora','Hrvojev misal','Vrbnički misal','Novakov misal'],
    ['Koje je godine tiskan Misal po zakonu rimskoga dvora?','1483.','1494.','1530.','1561.'],
    ['Na kojem je pismu napisana Bašćanska ploča?','glagoljici','latinici','grčkom pismu','hebrejskom pismu'],
    ['Gdje je pronađena Bašćanska ploča?','Jurandvor kraj Baške','Vrbnik','Senj','Omišalj'],
    ['Koji se otok povezuje s Bašćanskom pločom?','Krk','Cres','Hvar','Pag'],
    ['Koji je poznati hrvatski glagoljski kodeks iz 1404.?','Hrvojev misal','Misal iz 1483.','Vinodolski zakonik','Bašćanska ploča'],
    ['Tko je povezan s Hrvojevim misalom?','Hrvoje Vukčić Hrvatinić','Nikola Šubić Zrinski','Petar Zrinski','Ivan Frankopan'],
    ['Kako se zovu svećenici povezani s glagoljaškom tradicijom?','glagoljaši','templari','trubaduri','uskoci'],
    ['Koji je istarski grad povezan s Alejom glagoljaša?','Roč','Pula','Poreč','Rovinj'],
    ['Koje mjesto se nalazi na kraju Aleje glagoljaša?','Hum','Buzet','Motovun','Grožnjan'],
    ['Koji je grad bio poznato središte glagoljskog tiskarstva?','Senj','Osijek','Varaždin','Dubrovnik'],
    ['Koja su braća povezana s počecima slavenske pismenosti?','Ćiril i Metod','Kiril i Juraj','Marko i Petar','Franjo i Ivan'],
    ['Koji je spomenik jedan od najvažnijih ranih hrvatskih glagoljskih natpisa?','Bašćanska ploča','Mirogojski natpis','Zagrebačka ploča','Dubrovački statut'],
    ['Koje se pismo tradicionalno veže uz hrvatsku liturgijsku posebnost?','glagoljica','gotica','runica','arapsko pismo']
  ],
  vjera: [
    ['Koji je svetac zaštitnik Dubrovnika?','sveti Vlaho','sveti Duje','sveti Marko','sveti Donat'],
    ['Koji je svetac zaštitnik Splita?','sveti Duje','sveti Vlaho','sveti Marko','sveti Eufemija'],
    ['Koji je svetac zaštitnik Zagreba?','sveti Marko','sveti Vlaho','sveti Duje','sveti Donat'],
    ['Koje je poznato marijansko svetište u Hrvatskom zagorju?','Marija Bistrica','Trsat','Sinj','Aljmaš'],
    ['Koje je poznato svetište na području Rijeke?','Trsat','Marija Bistrica','Sinj','Aljmaš'],
    ['Koji je blagdan 1. studenoga?','Svi sveti','Dušni dan','Velika Gospa','Bogojavljenje'],
    ['Koji se blagdan slavi 2. studenoga?','Dušni dan','Svi sveti','Tijelovo','Uzašašće'],
    ['Koji se blagdan slavi četrdeset dana nakon Uskrsa?','Uzašašće','Duhovi','Tijelovo','Velika Gospa'],
    ['Koji se blagdan slavi pedeset dana nakon Uskrsa?','Duhovi','Uzašašće','Tijelovo','Bogojavljenje'],
    ['Koji je blagdan 8. prosinca?','Bezgrješno začeće','Navještenje','Uznesenje','Rođenje Marijino'],
    ['Koja je poznata sinjska svetinja povezana s Velikom Gospom?','Gospa Sinjska','Gospa Trsatska','Majka Božja Bistrička','Gospa od Škrpjela'],
    ['Koji je svetac zaštitnik Zadra?','sveti Krševan','sveti Vlaho','sveti Duje','sveti Marko'],
    ['Koji je svetac zaštitnik Rijeke?','sveti Vid','sveti Duje','sveti Vlaho','sveti Marko'],
    ['Koji je red tradicionalno povezan s Trsatskim svetištem?','franjevci','templari','jezuiti','trapisti'],
    ['Koji je poznati hodočasnički grad u Sinjskoj krajini?','Sinj','Omiš','Imotski','Knin']
  ],
  sport: [
    ['Koji je splitski nogometni klub osnovan 1911.?','Hajduk','Dinamo','Rijeka','Osijek'],
    ['Koji je zagrebački nogometni klub poznat kao GNK Dinamo?','Dinamo','Hajduk','Lokomotiva','Rijeka'],
    ['Koji je hrvatski tenisač osvojio Wimbledon 2001.?','Goran Ivanišević','Marin Čilić','Ivan Ljubičić','Ivo Karlović'],
    ['Koji je hrvatski tenisač osvojio US Open 2014.?','Marin Čilić','Goran Ivanišević','Borna Ćorić','Ivan Ljubičić'],
    ['Koja je hrvatska atletičarka poznata po olimpijskom zlatu u bacanju diska 2012.?','Sandra Perković','Blanka Vlašić','Sara Kolak','Ivana Brkljačić'],
    ['Koja je hrvatska atletičarka osvojila olimpijsko zlato u bacanju koplja 2016.?','Sara Kolak','Sandra Perković','Blanka Vlašić','Lucija Zaninović'],
    ['Koja je hrvatska skijašica osvojila četiri olimpijska zlata?','Janica Kostelić','Blanka Vlašić','Sandra Perković','Ana Jelušić'],
    ['Koji je hrvatski skijaš osvojio olimpijsko srebro u kombinaciji 2006.?','Ivica Kostelić','Ante Kostelić','Natko Zrnčić-Dim','Ivica Olić'],
    ['Koji je dubrovački vaterpolski klub jedan od najpoznatijih u Hrvatskoj?','Jug','Mladost','Jadran','Primorje'],
    ['Koji je zagrebački vaterpolski klub poznat kao Mladost?','HAVK Mladost','Jug','Jadran','Primorje'],
    ['Koji je hrvatski košarkaš igrao za Chicago Bulls?','Toni Kukoč','Dražen Petrović','Dino Rađa','Stojko Vranković'],
    ['Koji je hrvatski košarkaš bio član New Jersey Netsa?','Dražen Petrović','Toni Kukoč','Dino Rađa','Nikola Vujčić'],
    ['Koji je hrvatski rukometni klub iz Zagreba?','Zagreb','Nexe','Metković','Dubrava'],
    ['Koji je hrvatski borac osvojio olimpijsko zlato u hrvanju 2016.?','Davor Štefanek','Filip Hrgović','Stipe Drviš','Mirko Filipović'],
    ['Koji je hrvatski automobilist poznat po uspjesima u reliju?','Juraj Šebalj','Goran Ivanišević','Ivica Kostelić','Marin Čilić']
  ],
  znanost: [
    ['Koji je hrvatski izumitelj povezan s izmjeničnom strujom?','Nikola Tesla','Ruđer Bošković','Faust Vrančić','Marin Getaldić'],
    ['Koji je hrvatski znanstvenik bio astronom, fizičar i isusovac?','Ruđer Bošković','Nikola Tesla','Andrija Mohorovičić','Lavoslav Ružička'],
    ['Tko je otkrio diskontinuitet između Zemljine kore i plašta?','Andrija Mohorovičić','Ruđer Bošković','Nikola Tesla','Vladimir Prelog'],
    ['Kako se zove granica između Zemljine kore i plašta?','Mohorovičićev diskontinuitet','Boškovićeva granica','Teslina granica','Prelogova granica'],
    ['Koji je hrvatski kemičar dobio Nobelovu nagradu 1939.?','Lavoslav Ružička','Vladimir Prelog','Ruđer Bošković','Ivan Supek'],
    ['Koji je hrvatski kemičar dobio Nobelovu nagradu 1975.?','Vladimir Prelog','Lavoslav Ružička','Nikola Tesla','Andrija Mohorovičić'],
    ['Tko je autor djela Machinae novae?','Faust Vrančić','Nikola Tesla','Ruđer Bošković','Marin Getaldić'],
    ['Koji je dubrovački znanstvenik proučavao geometriju i optiku?','Marin Getaldić','Faust Vrančić','Ruđer Bošković','Nikola Tesla'],
    ['Koji je institut u Zagrebu dobio ime po Ruđeru Boškoviću?','Institut Ruđer Bošković','Institut Nikola Tesla','Institut Prelog','Institut Mohorovičić'],
    ['Koji je hrvatski fizičar i filozof bio važna osoba hrvatske znanosti 20. stoljeća?','Ivan Supek','Vladimir Prelog','Lavoslav Ružička','Andrija Mohorovičić'],
    ['Koji se znanstvenik bavio seizmologijom i meteorologijom?','Andrija Mohorovičić','Vladimir Prelog','Lavoslav Ružička','Marin Getaldić'],
    ['Koji je znanstvenik poznat po istraživanju stereokemije?','Vladimir Prelog','Lavoslav Ružička','Ruđer Bošković','Ivan Supek'],
    ['Koji je hrvatski izumitelj povezan s radovima o električnim sustavima?','Nikola Tesla','Faust Vrančić','Marin Getaldić','Ruđer Bošković'],
    ['Koji je znanstvenik dao ime jednom od najvažnijih diskontinuiteta u geofizici?','Andrija Mohorovičić','Ruđer Bošković','Vladimir Prelog','Nikola Tesla'],
    ['Koji je hrvatski kemičar dobio Nobelovu nagradu za istraživanja prirodnih organskih spojeva?','Lavoslav Ružička','Vladimir Prelog','Ivan Supek','Ruđer Bošković']
  ]
};
for (const [category, items] of Object.entries(Q150)) {
  window.PATRIA_EXTRA_QUESTIONS[category] = (window.PATRIA_EXTRA_QUESTIONS[category] || []).concat(items.map((x,i)=>({id:`${category}_150_${String(i+1).padStart(3,'0')}`,category,question:x[0],answers:x.slice(1),correctIndex:0})));
}
