// PatriaSoul – Hrvatski sport: 100 jedinstvenih pitanja.
(function(){'use strict';
const Q=[
['Koji je hrvatski nogometni klub osvojio Kup velesajamskih gradova 1967.?','Dinamo Zagreb','Hajduk Split','Rijeka','Osijek'],
['Koji je hrvatski nogometaš osvojio Zlatnu loptu 2018.?','Luka Modrić','Davor Šuker','Zvonimir Boban','Robert Prosinečki'],
['Tko je bio najbolji strijelac Svjetskog prvenstva 1998.?','Davor Šuker','Luka Modrić','Mario Mandžukić','Robert Prosinečki'],
['Koju je medalju Hrvatska osvojila na Svjetskom prvenstvu 1998.?','Brončanu','Zlatnu','Srebrnu','Nije osvojila medalju'],
['Koju je medalju Hrvatska osvojila na Svjetskom prvenstvu 2018.?','Srebrnu','Zlatnu','Brončanu','Nije osvojila medalju'],
['Koju je medalju Hrvatska osvojila na Svjetskom prvenstvu 2022.?','Brončanu','Zlatnu','Srebrnu','Nije osvojila medalju'],
['Tko je bio kapetan hrvatske reprezentacije na SP-u 2018.?','Luka Modrić','Ivan Rakitić','Domagoj Vida','Danijel Subašić'],
['Protiv koje je reprezentacije Hrvatska igrala finale SP-a 2018.?','Francuske','Engleske','Belgije','Njemačke'],
['Koji je hrvatski napadač postigao pogodak u finalu SP-a 2018.?','Mario Mandžukić','Andrej Kramarić','Ivan Perišić','Ante Rebić'],
['Koji je klub iz Splita osnovan 1911.?','Hajduk','Dinamo','Rijeka','Osijek'],
['Koji je klub iz Zagreba poznat kao Modri?','Dinamo','Hajduk','Rijeka','Istra 1961'],
['Koji hrvatski nogometni klub nosi nadimak Bijeli?','Hajduk','Dinamo','Osijek','Varaždin'],
['Koji je klub osvojio prvenstvo Hrvatske u sezoni 2016./17. bez poraza?','Rijeka','Dinamo Zagreb','Hajduk Split','Osijek'],
['Koji je hrvatski nogometni reprezentativac poznat kao Vatreni kapetan?','Luka Modrić','Davor Šuker','Zvonimir Boban','Robert Prosinečki'],
['Koji je hrvatski vratar branio za reprezentaciju na SP-u 2018.?','Danijel Subašić','Dominik Livaković','Stipe Pletikosa','Vedran Runje'],
['Koji je hrvatski vratar bio među junacima SP-a 2022.?','Dominik Livaković','Danijel Subašić','Stipe Pletikosa','Vedran Runje'],
['Tko je zabio pobjednički pogodak protiv Engleske u polufinalu SP-a 2018.?','Mario Mandžukić','Ivan Perišić','Luka Modrić','Marcelo Brozović'],
['Koji je hrvatski nogometaš poznat po nadimku Šukerman?','Davor Šuker','Zvonimir Boban','Alen Bokšić','Robert Prosinečki'],
['Koji je hrvatski tenisač osvojio Wimbledon 2001.?','Goran Ivanišević','Marin Čilić','Ivo Karlović','Ivan Ljubičić'],
['Koji je hrvatski tenisač osvojio US Open 2014.?','Marin Čilić','Goran Ivanišević','Borna Ćorić','Ivan Ljubičić'],
['Koji je hrvatski tenisač poznat po vrlo snažnom servisu i visini od 211 cm?','Ivo Karlović','Goran Ivanišević','Marin Čilić','Ivan Ljubičić'],
['Koji je hrvatski tenisač osvojio Roland Garros u muškim parovima 2015. s Marcelom Melom?','Ivan Dodig','Mate Pavić','Nikola Mektić','Marin Čilić'],
['Koji je hrvatski par osvojio Wimbledon u muškim parovima 2021.?','Nikola Mektić i Mate Pavić','Ivan Dodig i Marin Čilić','Goran Ivanišević i Ivo Karlović','Marin Čilić i Borna Ćorić'],
['Koji je hrvatski tenisač osvojio Wimbledon u muškim parovima 2017. s Oliverom Marachom?','Mate Pavić','Ivan Dodig','Nikola Mektić','Ivo Karlović'],
['Koji je hrvatski tenisač bio olimpijski pobjednik u muškim parovima u Tokiju 2020. zajedno s Nikolom Mektićem?','Mate Pavić','Ivan Dodig','Marin Čilić','Borna Ćorić'],
['Koji je hrvatski košarkaš bio član Chicago Bullsa i osvojio tri NBA naslova?','Toni Kukoč','Dražen Petrović','Dino Rađa','Stojko Vranković'],
['Koji je hrvatski košarkaš igrao za Portland Trail Blazerse i New Jersey Netse?','Dražen Petrović','Toni Kukoč','Dino Rađa','Nikola Vujčić'],
['Koji je hrvatski košarkaš primljen u Naismithovu Kuću slavnih 2018.?','Dino Rađa','Toni Kukoč','Dražen Petrović','Stojko Vranković'],
['Koji je hrvatski košarkaški klub iz Zagreba poznat kao Cibona?','Cibona','Split','Zadar','Cedevita'],
['Koji je hrvatski košarkaški klub osvojio Kup prvaka Europe 1989. i 1990.?','Jugoplastika Split','Cibona Zagreb','Zadar','Cedevita'],
['Kako se danas zove klub koji je u vrijeme europskih naslova bio poznat kao Jugoplastika?','KK Split','KK Cibona','KK Zadar','KK Zagreb'],
['Koji je hrvatski košarkaški klub osvojio europski Kup prvaka 1985. i 1986.?','Cibona','Jugoplastika','Zadar','Cedevita'],
['Koji je hrvatski rukometaš poznat po nadimku Ivano?','Ivano Balić','Domagoj Duvnjak','Igor Vori','Mirza Džomba'],
['Koji je hrvatski rukometaš proglašen najboljim rukometašem svijeta 2013. prema IHF-u?','Domagoj Duvnjak','Ivano Balić','Igor Vori','Mirza Džomba'],
['Koji je hrvatski rukometni klub iz Zagreba osvojio Kup prvaka Europe 1992.?','RK Zagreb','RK Nexe','RK Zamet','RK Bjelovar'],
['Koji je grad bio domaćin završnice Svjetskog prvenstva u rukometu 2009.?','Zagreb','Split','Zadar','Osijek'],
['Koje je godine Hrvatska osvojila srebro na SP-u u rukometu na domaćem terenu?','2009.','2007.','2011.','2013.'],
['Koji je hrvatski rukometaš bio dugogodišnji kapetan reprezentacije i igra na poziciji srednjeg vanjskog?','Domagoj Duvnjak','Ivano Balić','Blaženko Lacković','Mirza Džomba'],
['Koji je hrvatski rukometaš bio poznat po snažnom šutu s lijevog vanjskog?','Blaženko Lacković','Ivano Balić','Domagoj Duvnjak','Igor Vori'],
['Koji je hrvatski vaterpolski klub iz Dubrovnika?','Jug','Mladost','Jadran','Primorje'],
['Koji je zagrebački vaterpolski klub poznat kao Mladost?','HAVK Mladost','Jug','Jadran','Primorje'],
['Koji je hrvatski vaterpolski klub iz Splita?','Jadran','Jug','Mladost','Primorje'],
['Koji je hrvatski vaterpolski klub iz Rijeke?','Primorje','Jug','Jadran','Mladost'],
['Koji je hrvatski vaterpolist osvojio olimpijsko zlato 2012. i bio kapetan reprezentacije?','Josip Pavić','Sandro Sukno','Andro Bušlje','Marko Bijač'],
['Koje je godine Hrvatska prvi put osvojila olimpijsko zlato u muškom vaterpolu?','2012.','2004.','2016.','2020.'],
['Koji je hrvatski vaterpolist bio kapetan momčadi koja je osvojila SP 2017.?','Sandro Sukno','Josip Pavić','Andro Bušlje','Marcelić Marko'],
['Koji je hrvatski veslački dvojac osvojio olimpijsko zlato u Riju 2016.?','Martin i Valent Sinković','Damir Martin i Luka Radonić','David Šain i Mario Vekić','Siniša i Nikša Skelin'],
['Koja braća čine najpoznatiji hrvatski veslački dvojac Sinković?','Martin i Valent','Damir i Martin','Valent i Luka','Nikola i Martin'],
['Koji je hrvatski veslač osvojio olimpijsko srebro u samcu u Riju 2016.?','Damir Martin','Martin Sinković','Valent Sinković','Mario Vekić'],
['U kojoj su disciplini braća Sinković osvojila olimpijsko zlato u Tokiju 2020.?','Dvojac bez kormilara','Četverac s kormilarom','Samac','Dvojac s kormilarom'],
['Koji je hrvatski veslač osvojio svjetsko zlato u samcu 2015.?','Damir Martin','Martin Sinković','Valent Sinković','David Šain'],
['Koja je hrvatska atletičarka osvojila olimpijsko zlato u bacanju diska 2012.?','Sandra Perković','Blanka Vlašić','Sara Kolak','Vesna Fabjan'],
['Koja je hrvatska atletičarka osvojila olimpijsko zlato u bacanju koplja 2016.?','Sara Kolak','Sandra Perković','Blanka Vlašić','Ana Šimić'],
['Koja je hrvatska atletičarka osvojila olimpijsko srebro u skoku u vis u Pekingu 2008.?','Blanka Vlašić','Sandra Perković','Sara Kolak','Ana Šimić'],
['Koja je disciplina proslavila Blanku Vlašić?','Skok u vis','Bacanje diska','Bacanje koplja','Skok u dalj'],
['Koja je disciplina proslavila Sandru Perković?','Bacanje diska','Skok u vis','Bacanje koplja','Trčanje na 100 m'],
['Koji je hrvatski skijaš osvojio olimpijsko srebro u slalomu u Vancouveru 2010.?','Ivica Kostelić','Natko Zrnčić-Dim','Dalibor Šamšal','Ivica Jerković'],
['Koji je hrvatski skijaš osvojio četiri olimpijske medalje u alpskom skijanju?','Ivica Kostelić','Ante Kostelić','Natko Zrnčić-Dim','Dalibor Šamšal'],
['Koja je hrvatska skijašica osvojila četiri olimpijske medalje u alpskom skijanju?','Janica Kostelić','Ana Jelušić','Nika Fleiss','Leona Popović'],
['Koliko je zlatnih olimpijskih medalja Janica Kostelić osvojila?','4','3','2','5'],
['Koji je hrvatski skijaš osvojio broncu u superkombinaciji na ZOI u Vancouveru 2010.?','Natko Zrnčić-Dim','Ivica Kostelić','Dalibor Šamšal','Ante Kostelić'],
['Koji je hrvatski gimnastičar osvojio svjetsko zlato na preči 2017.?','Tin Srbić','Filip Ude','Marijo Možnik','Robert Seligman'],
['Koji je hrvatski gimnastičar osvojio olimpijsko srebro na preči u Tokiju 2020.?','Tin Srbić','Filip Ude','Marijo Možnik','Robert Seligman'],
['Koji je hrvatski gimnastičar osvojio svjetsku medalju na konju s hvataljkama?','Filip Ude','Tin Srbić','Marijo Možnik','Robert Seligman'],
['Koji je hrvatski gimnastičar poznat po medaljama na konju s hvataljkama?','Robert Seligman','Tin Srbić','Marijo Možnik','Filip Ude'],
['Koji je hrvatski boksač osvojio broncu na Olimpijskim igrama u Riju 2016.?','Filip Hrgović','Stipe Drviš','Marko Milun','Hrvoje Sep'],
['Koji je hrvatski boksač poznat pod nadimkom El Animal?','Filip Hrgović','Stipe Drviš','Hrvoje Sep','Marko Milun'],
['Koji je hrvatski boksač osvojio olimpijsku medalju u Parizu 2024.?','Nijedan hrvatski boksač','Filip Hrgović','Luka Plantić','Marko Milun'],
['Koja je hrvatska taekwondoistica osvojila olimpijsko zlato u Tokiju 2020.?','Mateja Jelić','Lucija Zaninović','Ana Zaninović','Tena Kovačević'],
['Koja je hrvatska taekwondoistica osvojila olimpijsku broncu u Londonu 2012.?','Lucija Zaninović','Mateja Jelić','Ana Zaninović','Nina Kleflin'],
['Koja je hrvatska taekwondoistica osvojila srebro na OI u Londonu 2012.?','Ana Zaninović','Lucija Zaninović','Mateja Jelić','Nina Kleflin'],
['Koja je hrvatska judašica osvojila svjetsko zlato 2021. u kategoriji do 70 kg?','Barbara Matić','Karla Prodan','Matea Jelić','Marijana Mišković'],
['Koja je hrvatska judašica osvojila svjetsko zlato 2022.?','Barbara Matić','Karla Prodan','Ivana Šutalo','Tena Sikirić'],
['Koja je hrvatska judašica osvojila svjetsko srebro 2021. u kategoriji do 78 kg?','Karla Prodan','Barbara Matić','Matea Jelić','Ivana Šutalo'],
['Koji je hrvatski odbojkaški klub iz Zagreba jedan od najpoznatijih ženskih klubova?','Mladost','Ribola Kaštela','Mursa Osijek','OK Split'],
['Koji je hrvatski odbojkaški klub iz Kaštela poznat po muškoj ekipi?','Mladost Ribola Kaštela','Mladost Zagreb','Mursa Osijek','HAOK Split'],
['Koji je hrvatski rukometni klub iz Našica poznat po europskim nastupima?','Nexe','Zagreb','Zamet','Bjelovar'],
['Koji je hrvatski nogometni klub osvojio Balkanski kup 1976.?','Rijeka','Dinamo Zagreb','Hajduk Split','Osijek'],
['Koji je hrvatski nogometni klub igrao četvrtfinale Kupa prvaka 1995. protiv Ajaxa?','Hajduk Split','Dinamo Zagreb','Rijeka','Osijek'],
['Koji je hrvatski nogometaš postigao pogodak protiv Brazila u četvrtfinalu SP-a 2022.?','Bruno Petković','Andrej Kramarić','Mario Pašalić','Ivan Perišić'],
['Koji je hrvatski igrač zabio pogodak protiv Japana na SP-u 2022.?','Ivan Perišić','Andrej Kramarić','Bruno Petković','Luka Modrić'],
['Koji je hrvatski igrač postigao dva pogotka protiv Kanade na SP-u 2022.?','Andrej Kramarić','Marko Livaja','Ivan Perišić','Bruno Petković'],
['Koji je hrvatski nogometaš zabio pobjednički pogodak protiv Maroka za broncu 2022.?','Mislav Oršić','Joško Gvardiol','Andrej Kramarić','Ivan Perišić'],
['Koji je hrvatski branič postigao prvi pogodak u utakmici za broncu na SP-u 2022.?','Joško Gvardiol','Mislav Oršić','Ivan Perišić','Andrej Kramarić'],
['Koji je hrvatski vratar obranio jedanaesterac u raspucavanju protiv Japana na SP-u 2022.?','Dominik Livaković','Danijel Subašić','Stipe Pletikosa','Ivica Ivušić'],
['Koliko je jedanaesteraca Dominik Livaković obranio u raspucavanju protiv Japana 2022.?','3','2','1','4'],
['Koji je hrvatski nogometaš postigao izjednačujući pogodak protiv Brazila u produžetku 2022.?','Bruno Petković','Andrej Kramarić','Ivan Perišić','Mario Pašalić'],
['Koji je hrvatski nogometaš postigao pogodak protiv Kanade u prvoj minuti utakmice SP-a 2022.?','Andrej Kramarić','Marko Livaja','Ivan Perišić','Joško Gvardiol'],
['Koji je hrvatski sportaš osvojio olimpijsko zlato u jedrenju u klasi Finn 2004.?','Karolina Savić','Nijedan hrvatski jedriličar','Tonči Stipanović','Ivan Kljaković Gašpić'],
['Koji je hrvatski jedriličar osvojio olimpijsko srebro u Laseru u Rio de Janeiru 2016.?','Tonči Stipanović','Ivan Kljaković Gašpić','Milan Vujasinović','Mate Arapov'],
['Koji je hrvatski jedriličar osvojio olimpijsko srebro u Laseru u Tokiju 2020.?','Tonči Stipanović','Ivan Kljaković Gašpić','Milan Vujasinović','Šime Fantela'],
['Koji je hrvatski jedriličarski dvojac osvojio olimpijsko zlato u klasi 470 u Riju 2016.?','Šime i Mihovil Fantela','Tonči Stipanović i Ivan Kljaković','Petar i Ivan Mrduša','Matija i Luka Bilobrk'],
['Koji je hrvatski jedriličar osvojio svjetsko zlato u klasi 49er 2018.?','Šime Fantela','Tonči Stipanović','Mihovil Fantela','Ivan Kljaković Gašpić'],
['Koji je hrvatski plivač osvojio olimpijsku medalju u Pekingu 2008.?','Duje Draganja','Nikša Roki','Gordan Kožulj','Mario Todorović'],
['U kojoj je disciplini Duje Draganja osvojio olimpijsko srebro 2004.?','50 m slobodno','100 m slobodno','100 m leptir','200 m mješovito'],
['Koji je hrvatski plivač osvojio svjetsko zlato na 50 m slobodno na SP-u 2009.?','Nijedan hrvatski plivač','Duje Draganja','Gordan Kožulj','Mario Todorović'],
['Koji je hrvatski biciklist nastupao na Tour de Franceu i Giro d’Italia?','Kristijan Đurasek','Matija Kvasina','Vladimir Miholjević','Robert Kišerlovski'],
['Koji je hrvatski biciklist ostvario pobjedu na etapi Giro d’Italia 2013.?','Robert Kišerlovski','Kristijan Đurasek','Matija Kvasina','Vladimir Miholjević'],
['Koji je hrvatski borac osvojio UFC naslov u poluteškoj kategoriji 2024.?','Nijedan hrvatski borac','Mirko Filipović','Igor Pokrajac','Dražen Forgač'],
['Pod kojim je nadimkom poznat hrvatski MMA borac Mirko Filipović?','Cro Cop','The Croatian Hammer','Dalmatian','Storm'],
['Koji je hrvatski MMA borac osvojio PRIDE Grand Prix 2006.?','Mirko Filipović','Stipe Miočić','Igor Vovchanchyn','Igor Pokrajac'],
['Koji je hrvatski borac osvojio UFC naslov teške kategorije 2016.?','Stipe Miočić','Mirko Filipović','Igor Pokrajac','Filip Hrgović'],
['Koji je hrvatski borac američkog podrijetla postao UFC prvak teške kategorije?','Stipe Miočić','Mirko Filipović','Filip Hrgović','Ante Delija'],
['Koji je hrvatski atletičar osvojio srebro u bacanju kugle na SP-u 2017.?','Stipe Žunić','Filip Mihaljević','Marin Premeru','Nedžad Mulabegović'],
['Koji je hrvatski atletičar osvojio europsko zlato u bacanju kugle 2024.?','Filip Mihaljević','Stipe Žunić','Marin Premeru','Nedžad Mulabegović'],
['Koji je hrvatski sportaš osvojio olimpijsko zlato u karateu u Tokiju 2020.?','Ivan Kvesić','Jelena Pehar','Nijedan hrvatski karatist','Anđelo Kvesić'],
['Koji je hrvatski karatist osvojio svjetsko zlato u kategoriji do 84 kg 2018.?','Ivan Kvesić','Anđelo Kvesić','Enes Garibović','Mario Vukoja'],
['Koji je hrvatski sportaš osvojio olimpijsko zlato u streljaštvu?','Nijedan hrvatski strijelac','Snježana Pejčić','Josip Glasnović','Giovanni Cernogoraz'],
['Koji je hrvatski strijelac osvojio olimpijsko zlato u trapu u Londonu 2012.?','Giovanni Cernogoraz','Josip Glasnović','Snježana Pejčić','Mirjana Mačić'],
['Koji je hrvatski strijelac osvojio olimpijsko srebro u Pekingu 2008.?','Snježana Pejčić','Giovanni Cernogoraz','Josip Glasnović','Anton Glasnović'],
['Koji je hrvatski strijelac osvojio olimpijsko zlato u trapu u Riju 2016.?','Josip Glasnović','Giovanni Cernogoraz','Snježana Pejčić','Anton Glasnović'],
['Koji je hrvatski sportaš osvojio olimpijsko zlato u dizanju utega?','Nijedan hrvatski dizač utega','Nikola Vuković','Petar Đurić','Ivan Ivančić'],
['Koji je hrvatski šahist bio svjetski prvak u brzopoteznom šahu 2013.?','Nijedan hrvatski šahist','Ivan Šarić','Zdenko Kožul','Alojzije Janković'],
['Koji je hrvatski šahist osvojio naslov europskog prvaka 2014.?','Ivan Šarić','Zdenko Kožul','Hrvoje Stević','Davorin Kuljašević'],
['Koji je hrvatski šahist postao velemajstor i osvojio Svjetsko juniorsko prvenstvo 2006.?','Ivan Šarić','Zdenko Kožul','Hrvoje Stević','Alojzije Janković']
];
if(Q.length!==100)throw new Error('PatriaSoul sport_bank: očekivano 100 pitanja, pronađeno '+Q.length);
window.PATRIA_EXTRA_QUESTIONS=window.PATRIA_EXTRA_QUESTIONS||{};
window.PATRIA_EXTRA_QUESTIONS.sport=Q.map((x,i)=>({id:'sport_'+String(i+1).padStart(3,'0'),question:x[0],answers:x.slice(1),correctIndex:0}));
})();
