// PatriaSoul — PWA cache layer.
// Network-first: live site always wins; cache is fallback when offline.
// v39 also sanitizes legacy placeholder labels from cached/live assets.
const CACHE='patriasoul-shell-v39';
const SHELL=['/','/index.html','/404.html','/manifest.json','/patriasoul-global.css','/patriasoul-modern.css','/style.css','/responsive.css','/site-navigation.js','/logo-navigation.css','/editorial-media.js','/pwa.js','/gradovi.html','/gradovi.js','/grad.html','/quiz.html','/quiz.js','/quiz.css','/brani-svoj-grad.html','/patriasoul-city-questions.js','/patriasoul-city-game.js','/patriasoul-profile.js','/levels.js','/badges.js','/leaderboard.js','/brigade.html','/brigade.js','/domovina.html','/povijest.html','/bastina.html','/branitelji.html','/domovinski-rat.html','/postrojbe.html','/operacije.html','/vukovar.html','/spomenici.html','/vjera.html','/vijesti.html','/video.html','/galerija.html','/rang-lista.html','/profil.html','/krajevi-i-geografija.html','/dalmacija.html','/istra.html','/kvarner-i-primorje.html','/lika-i-gorski-kotar.html','/zagorje-i-prigorje.html','/slavonija-i-baranja.html','/posavina-i-pokuplje.html','/podravina-i-bilogora.html','/medimurje.html'];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(SHELL).catch(()=>undefined)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
async function sanitize(response){if(!response||!response.ok)return response;const type=response.headers.get('content-type')||'';if(!/(javascript|html|css|text)/i.test(type))return response;const text=await response.text();if(!/privremena ilustracija/i.test(text))return new Response(text,{status:response.status,statusText:response.statusText,headers:response.headers});const clean=text.replace(/\s*[·•]\s*privremena ilustracija\b/gi,'').replace(/\bprivremena ilustracija\b/gi,'');const headers=new Headers(response.headers);headers.delete('content-length');return new Response(clean,{status:response.status,statusText:response.statusText,headers});}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET'||new URL(request.url).origin!==location.origin)return;event.respondWith(fetch(request).then(async response=>{const clean=await sanitize(response);if(clean.ok){const copy=clean.clone();caches.open(CACHE).then(cache=>cache.put(request,copy)).catch(()=>undefined)}return clean}).catch(()=>caches.match(request).then(async cached=>cached?sanitize(cached):caches.match('/404.html'))));});
