// PatriaSoul Vrijeme — Weather App UX + DHMZ podaci, bez geolokacije
(function(){
  'use strict';
  const FEED='weather-feed.json', CITIES='weather-cities.json', DEFAULT_CITY='Zagreb', STORAGE_KEY='patriasoul-weather-city';
  const $=id=>document.getElementById(id); let cities=[],feed={stations:{},alerts:[]};
  const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const normalize=v=>String(v??'').trim().toLocaleLowerCase('hr-HR');
  function icon(condition){const t=normalize(condition);if(t.includes('grmljav')||t.includes('sijev'))return '⛈️';if(t.includes('pljus')||t.includes('kiš'))return '🌧️';if(t.includes('snij'))return '❄️';if(t.includes('magl'))return '🌫️';if(t.includes('obla'))return '☁️';if(t.includes('vedr')||t.includes('sunč'))return '☀️';return '🌤️';}
  function isDay(){const h=new Date().getHours();return h>=6&&h<20;}
  function stationFor(city){if(!city)return null;const stations=feed?.stations||{},station=city.station||'';const direct=stations[station]||stations[city.name]||stations[normalize(city.name)];if(direct)return direct;const target=normalize(station||city.name);const key=Object.keys(stations).find(name=>{const c=normalize(name);return c===target||c.includes(target)||target.includes(c)});return key?stations[key]:null;}
  function formatTemperature(v){if(v===null||v===undefined||v==='')return '—';const n=Number(v);return Number.isFinite(n)?`${Math.round(n)}°C`:'—';}
  function formatWind(v){return v===null||v===undefined||v===''?'—':String(v);}
  function card(city,featured){const w=stationFor(city);return `<article class="wx-card ${featured?'wx-main':''}"><div class="wx-card-top"><span class="wx-region">${featured?'ODABRANO':'HRVATSKA'}</span><span class="wx-source">DHMZ</span></div><div class="wx-city"><h2>${esc(city.name)}</h2><span class="wx-icon" aria-hidden="true">${icon(w?.condition)}</span></div><div class="wx-temp">${esc(formatTemperature(w?.temp))}</div><p class="wx-condition">${esc(w?.condition||'Podaci nisu dostupni')}</p><div class="wx-details"><span>💨 ${esc(formatWind(w?.wind))}</span><span>💧 ${w?.humidity!=null?esc(w.humidity)+'%':'—'}</span></div><a class="wx-city-link" href="grad.html?city=${encodeURIComponent(city.name)}">Profil grada →</a></article>`;}
  function render(list,label){const c=$('wx-list');if(!c)return;const safe=Array.isArray(list)?list.filter(Boolean).slice(0,12):[];if(!safe.length){c.innerHTML='<div class="wx-empty">Nema dostupnih podataka za odabrani grad.</div>';if($('wx-count'))$('wx-count').textContent='Podaci trenutno nisu dostupni.';return;}c.innerHTML=safe.map((city,i)=>card(city,i===0)).join('');if($('wx-count'))$('wx-count').textContent=label||`Prikazano ${safe.length} lokacija.`;}
  function alertText(a){return typeof a==='object'?(a.text||a.description||a.message||''):String(a||'');}
  function renderAlerts(){const box=$('wx-alerts');if(!box)return;const seen=new Set(),alerts=(Array.isArray(feed?.alerts)?feed.alerts:[]).filter(a=>{const text=alertText(a).replace(/\s+/g,' ').trim(),key=normalize(text);if(!key||seen.has(key))return false;seen.add(key);return true;});if(!alerts.length){box.hidden=true;box.innerHTML='';return;}box.hidden=false;box.innerHTML=`<strong>🚨 DHMZ upozorenja</strong><ul>${alerts.slice(0,5).map(a=>`<li>${esc(alertText(a))}</li>`).join('')}</ul>`;}
  function findCity(name){return cities.find(city=>normalize(city?.name)===normalize(name));}
  function setupControls(){const control=document.querySelector('.wx-control'),select=$('wx-city');if(!control||!select||$('wx-search'))return;const input=document.createElement('input');input.id='wx-search';input.className='wx-input';input.type='search';input.setAttribute('list','wx-city-list');input.placeholder='Upiši hrvatski grad…';input.autocomplete='off';input.setAttribute('aria-label','Upiši hrvatski grad');const list=document.createElement('datalist');list.id='wx-city-list';const button=document.createElement('button');button.id='wx-search-button';button.className='wx-button';button.type='button';button.textContent='Prikaži vrijeme';control.insertBefore(input,select);control.insertBefore(list,select);control.insertBefore(button,select);const submit=()=>{const value=input.value.trim();if(!value)return;const city=findCity(value)||cities.find(c=>normalize(c.name).startsWith(normalize(value)));if(city){localStorage.setItem(STORAGE_KEY,city.name);location.href=`vrijeme.html?city=${encodeURIComponent(city.name)}`;return;}input.setCustomValidity('Grad nije pronađen. Odaberi hrvatski grad iz prijedloga.');input.reportValidity();};button.addEventListener('click',submit);input.addEventListener('keydown',e=>{input.setCustomValidity('');if(e.key==='Enter'){e.preventDefault();submit();}});input.addEventListener('input',()=>input.setCustomValidity(''));}
  function populateCitySelect(){const select=$('wx-city');if(!select||!cities.length)return;const stored=localStorage.getItem(STORAGE_KEY),current=new URLSearchParams(location.search).get('city')||stored||DEFAULT_CITY,sorted=[...cities].filter(c=>c?.name).sort((a,b)=>String(a.name).localeCompare(String(b.name),'hr'));select.innerHTML='<option value="">Odaberi grad…</option>'+sorted.map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join('');const selected=findCity(current)||findCity(DEFAULT_CITY)||sorted[0];if(selected)select.value=selected.name;const dl=$('wx-city-list');if(dl)dl.innerHTML=sorted.map(c=>`<option value="${esc(c.name)}"></option>`).join('');const search=$('wx-search');if(search)search.value=selected?.name||'';}
  function renderSelectedCity(){const params=new URLSearchParams(location.search),requested=params.get('city')||localStorage.getItem(STORAGE_KEY)||DEFAULT_CITY,selected=findCity(requested)||findCity(DEFAULT_CITY)||cities[0];if(!selected){render([],'Nema dostupnih gradova.');return;}localStorage.setItem(STORAGE_KEY,selected.name);const w=stationFor(selected),day=isDay(),panel=$('wx-selected-panel');if(panel){panel.classList.toggle('is-day',day);panel.classList.toggle('is-night',!day);}if($('wx-selected-city'))$('wx-selected-city').textContent=selected.name;if($('wx-selected-temp'))$('wx-selected-temp').textContent=formatTemperature(w?.temp);if($('wx-selected-condition'))$('wx-selected-condition').textContent=w?.condition||'Podaci nisu dostupni';if($('wx-selected-icon'))$('wx-selected-icon').textContent=icon(w?.condition);if($('wx-selected-wind'))$('wx-selected-wind').textContent=w?.wind||'—';if($('wx-selected-humidity'))$('wx-selected-humidity').textContent=w?.humidity!=null?`${w.humidity}%`:'—';if($('wx-selected-station'))$('wx-selected-station').textContent=w?.station||selected.station||'DHMZ';if($('wx-location'))$('wx-location').textContent=`Prognoza i mjerenja za ${selected.name}`;if($('wx-day-state'))$('wx-day-state').textContent=day?'☀️ DAN':'🌙 NOĆ';render([selected],`Odabrano mjesto: ${selected.name}`);}
  function renderHighlights(){const names=['Zagreb','Split','Rijeka','Osijek','Zadar','Šibenik','Dubrovnik','Pula'];const highlights=names.map(findCity).filter(Boolean),c=$('wx-highlights');if(c)c.innerHTML=highlights.map(city=>card(city,false)).join('');}
  async function fetchJson(url){const r=await fetch(`${url}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`Neuspješno učitavanje: ${url} (${r.status})`);return r.json();}
  function bind(){const city=$('wx-city');if(city)city.addEventListener('change',e=>{const value=e.target.value;if(value){localStorage.setItem(STORAGE_KEY,value);location.href=`vrijeme.html?city=${encodeURIComponent(value)}`;}});}
  async function init(){try{[cities,feed]=await Promise.all([fetchJson(CITIES),fetchJson(FEED)]);cities=Array.isArray(cities)?cities:[];feed=feed&&typeof feed==='object'?feed:{stations:{},alerts:[]};setupControls();populateCitySelect();bind();renderAlerts();renderSelectedCity();renderHighlights();if($('wx-updated')){const d=feed.updatedAt?new Date(feed.updatedAt):null;$('wx-updated').textContent=d&&!Number.isNaN(d.getTime())?`Ažurirano ${d.toLocaleString('hr-HR')}`:'Čeka se osvježavanje podataka';}}catch(error){console.error('[PatriaSoul Vrijeme]',error);if($('wx-list'))$('wx-list').innerHTML='<div class="wx-empty">Vrijeme se trenutno ne može učitati. Provjeri vezu i pokušaj ponovno.</div>';if($('wx-highlights'))$('wx-highlights').innerHTML='';if($('wx-location'))$('wx-location').textContent='⚠️ Podaci o vremenu trenutno nisu dostupni';if($('wx-updated'))$('wx-updated').textContent='Greška pri učitavanju podataka';}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
