<?php
if(!defined('ABSPATH'))exit;
function ps_setup(){add_theme_support('title-tag');add_theme_support('post-thumbnails');add_theme_support('custom-logo');}
add_action('after_setup_theme','ps_setup');
function ps_assets(){wp_enqueue_style('ps-style',get_stylesheet_uri(),array(),'1.0');wp_enqueue_script('ps-home',get_template_directory_uri().'/assets/home.js',array(),'1.0',true);}
add_action('wp_enqueue_scripts','ps_assets');
function ps_cards(){return array(
'hrvatska'=>array('Istraži Hrvatsku','Hrvatska','🇭🇷','Zemlja, regije, simboli i vodiči.','/hrvatska/'),'gradovi'=>array('Istraži Hrvatsku','Gradovi','🏙️','Istraži hrvatske gradove i njihove priče.','/gradovi/'),'krajevi'=>array('Istraži Hrvatsku','Krajevi i geografija','🗺️','Veliki geografski vodič Hrvatske.','/krajevi-i-geografija/'),'povijest'=>array('Istraži Hrvatsku','Povijest','📜','Razdoblja, događaji, vladari i ljudi.','/povijest/'),
'domovinski_rat'=>array('Domovina','Domovinski rat','🇭🇷','Kronologija i ključne teme rata.','/domovinski-rat/'),'branitelji'=>array('Domovina','Branitelji','🛡️','Branitelji, priče, postrojbe i tragovi.','/branitelji/'),'sjecanje'=>array('Domovina','Sjećanje','🕯️','Spomenici, memorijali i mjesta sjećanja.','/spomenici/'),'postrojbe'=>array('Domovina','Postrojbe i operacije','⚔️','Postrojbe, brigade, operacije i bojišta.','/postrojbe/'),
'hrvatski_kviz'=>array('Kvizovi','Hrvatski kviz','🧠','Provjeri znanje o Hrvatskoj.','/quiz/'),'brani_grad'=>array('Kvizovi','Brani svoj grad','🛡️','Prepoznaj gradove i brani rezultat.','/brani-svoj-grad/'),'dnevni_kviz'=>array('Kvizovi','Dnevni kviz','📅','Novi izazov svaki dan.','/dnevni-kviz/'),'izazovi'=>array('Kvizovi','Izazovi','🏆','XP, značke i rang-lista.','/izazovi/'),
'vijesti'=>array('Hrvatska danas','Vijesti','📰','Aktualne hrvatske teme.','/vijesti/'),'aktualnosti'=>array('Hrvatska danas','Aktualnosti','✦','Što se događa danas.','/aktualnosti/'),'kultura'=>array('Hrvatska danas','Kultura','🎭','Kultura, umjetnost i baština.','/kultura/'),'sport'=>array('Hrvatska danas','Sport','⚽','Hrvatski sport i sportske priče.','/sport/'),
'evandelje'=>array('Vjera i duhovnost','Evanđelje','✝️','Božja riječ i dnevno Evanđelje.','/evandelje/'),'molitve'=>array('Vjera i duhovnost','Molitve','🙏','Molitve za svaki dan.','/molitve/'),'svetci'=>array('Vjera i duhovnost','Svetci','🕊️','Svetci i njihovi životi.','/svetci/'),'blagdani'=>array('Vjera i duhovnost','Blagdani','🕯️','Liturgijski i hrvatski blagdani.','/blagdani/'));}
function ps_img($k){$id=(int)get_theme_mod('ps_img_'.$k,0);if($id){$u=wp_get_attachment_image_url($id,'large');if($u)return $u;}$b='https://raw.githubusercontent.com/Patriasoul/patriasoul/main/images/';$f=array('domovinski_rat'=>'domovinski-rat-hero.svg','branitelji'=>'branitelji-hero.svg','postrojbe'=>'brigade-hero.svg','hrvatski_kviz'=>'PATRIA_SOUL_ORIGINAL_ISPRAVLJEN_GRB.png','brani_grad'=>'brigade-hero.svg');return $b.(isset($f[$k])?$f[$k]:'Bastina.jfif');}
