<?php get_header(); $cards=ps_cards(); $hero_id=(int)get_theme_mod('ps_hero_image',0); $hero=$hero_id?wp_get_attachment_image_url($hero_id,'full'):'https://raw.githubusercontent.com/Patriasoul/patriasoul/main/images/Bastina.jfif'; $title=get_theme_mod('ps_hero_title','Hrvatska. Povijest. Znanje. Identitet.'); $text=get_theme_mod('ps_hero_text','Digitalni prostor koji povezuje hrvatsku povijest, baštinu, vjeru, gradove, branitelje i znanje.'); ?>
<section class="ps-hero"><div class="ps-hero-bg" style="background-image:url('<?php echo esc_url($hero); ?>')"></div><div class="ps-wrap ps-hero-content"><span class="ps-kicker">🇭🇷 Hrvatska · povijest · znanje · identitet</span><h1>Patria<span>Soul</span></h1><h2><?php echo esc_html($title); ?></h2><p><?php echo esc_html($text); ?></p><div class="ps-actions"><a class="ps-btn ps-btn-primary" href="<?php echo esc_url(home_url('/quiz/')); ?>">🧠 Igraj kviz</a><a class="ps-btn ps-btn-ghost" href="#istrazi">🏙️ Istraži Hrvatsku</a></div></div></section>
<?php $groups=array('Istraži Hrvatsku'=>'istrazi','Domovina'=>'domovina','Kvizovi'=>'kvizovi','Hrvatska danas'=>'danas','Vjera i duhovnost'=>'vjera'); foreach($groups as $name=>$id): ?>
<section id="<?php echo esc_attr($id); ?>" class="ps-section <?php echo $id==='domovina'||$id==='kvizovi'?'alt':''; ?>"><div class="ps-wrap"><div class="ps-head"><div><span class="eyebrow"><?php echo esc_html($name); ?></span><h2><?php echo esc_html($name); ?></h2></div><p><?php echo esc_html($id==='istrazi'?'Od Hrvatske i gradova do geografije i povijesti.':($id==='domovina'?'Domovinski rat, branitelji i mjesta sjećanja.':($id==='kvizovi'?'Znanje pretvoreno u igru, izazov i napredak.':($id==='danas'?'Aktualnosti, kultura, vijesti i sport.':'Evanđelje, molitve, svetci i blagdani.')))); ?></p></div><div class="ps-grid">
<?php foreach($cards as $k=>$v){if($v[0]===$name)get_template_part('parts/card',null,array('key'=>$k,'card'=>$v));} ?>
</div></div></section>
<?php endforeach; ?>
<section class="ps-section"><div class="ps-wrap"><div class="ps-feature"><div class="ps-feature-copy"><span class="eyebrow">PatriaSoul</span><h2>Čuvamo ono što vrijedi zapamtiti.</h2><p>Projekt iz repozitorija povezuje hrvatsku povijest, gradove, baštinu, branitelje, spomenike, kvizove, medije i vjeru u jednu digitalnu cjelinu.</p><div class="ps-actions"><a class="ps-btn ps-btn-primary" href="<?php echo esc_url(home_url('/gradovi/')); ?>">Istraži gradove →</a><a class="ps-btn ps-btn-ghost" href="<?php echo esc_url(home_url('/branitelji/')); ?>">Branitelji →</a></div></div><div class="ps-feature-image" style="background-image:url('<?php echo esc_url(ps_img('hrvatska')); ?>')"></div></div></div></section>
<section class="ps-final"><div class="ps-wrap ps-final-box"><div class="cross">✝</div><blockquote>„Ja sam svjetlost svijeta. Tko ide za mnom, neće hodati u tami, nego će imati svjetlost života.”</blockquote><cite>Ivan 8,12</cite></div></section>
<?php get_footer(); ?>
